krymskiy_sviatoslav/task_01
Friend-LGA/msu_course_cpp_323_2022 pull request #1
Opened 2022-09-05 07:12 UTC by ludmik

2022-09-11 11:40 UTC, Friend-LGA requested changes
1) Бинарника быть не должно в ПР (пулл реквесте)
2) Название бранча неверное (`krymskiy_sviatoslav/task_01`) - добавь подчеркивание

2022-09-11 11:40 UTC, Friend-LGA commented on krymskiy_sviatoslav/README.md
> +![Screenshot](screenshot)
И где скриншот? Не вижу

2022-09-11 11:40 UTC, Friend-LGA commented on krymskiy_sviatoslav/README.md
> +# Krymskit Sviatoslav
Опечатка

2022-10-18 20:09 UTC, ludmik commented on krymskiy_sviatoslav/README.md
> +![Screenshot](screenshot)
Подчеркивание в названии ведь вроде как есть или я не туда смотрю? Сравнил с остальными, вроде такие же имена ветки.

2022-10-22 06:33 UTC, Friend-LGA requested changes
Справа сверху, в списке ревьюеров, если твой ПР (пулл реквест) готов к проверке, не забывай нажимать кнопку "re-request review". Я проверяю только те ПР, которые запросили ревью.

2022-10-22 06:33 UTC, Friend-LGA commented on .gitignore
> +.krymskiy_sviatoslav/hello_world
Не надо изменять гитигнор, все равно название изменится

2022-10-22 08:23 UTC, Friend-LGA requested changes

2022-10-22 08:23 UTC, Friend-LGA commented on .gitignore
> +# Temp, add here your `temp` folders
Изменения в файле все ещё есть, а их быть не должно

2022-10-23 08:38 UTC, Friend-LGA approved these changes

2022-10-23 08:40 UTC, Friend-LGA commented
Я отправил на гитхабе тебе приглашение в коллабораторы, прими его, после этого ты сможешь замерджить данный ПР. Тут будет кнопка `merge`

2022-10-23 08:43 UTC, merged