kucherov_sergeev/task_06
Friend-LGA/msu_course_cpp_323_2022 pull request #100
Opened 2022-11-13 15:57 UTC by BasilKucherov

2022-11-13 16:24 UTC, fedyasa approved these changes

2022-11-13 16:45 UTC, Friend-LGA requested changes

2022-11-13 16:45 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +                      std::lock_guard lock(graph_mutex);
Изменяется? `const`

2022-11-13 16:45 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +              std::lock_guard lock(graph_mutex);
Аналогично

2022-11-13 16:45 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +            std::lock_guard lock(graph_mutex);
Ангалогично

2022-11-13 16:45 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  }
1) `if (condition == false)` записывается как `if (!condition)`
2) `jobs` у нас разделяемый ресурс, раз так было бы неплохо добавить блокировку. Но это очень не эффективно в бесконечном цикле, поэтому лучше подумать об альтернативной логике, например использовать `atomic`

2022-11-13 16:45 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
>      generate_grey_edges(graph);
Вы внутри `generate_grey_edges` исчпользуете хитрую логику чтобы получить id корневой вершины, при чем используете там 0 как `magic number`. Много лучше будет передать туда реальные данные
```suggestion
    const auto root_id = graph.add_vertex();
    generate_grey_edges(graph, root_id);
```

2022-11-13 16:45 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  int new_vertices_count = params_.new_vertices_count();
`const`

2022-11-13 16:45 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +                          bool one_vertex_start = false) {
1) Очень много переменных. Можно сделать этот метод членом класса, чтобы у него был доступ к `params`, таким образом сократим количество переменных.
2) Что за `one_vertex_start`, перемудрили, не думаю что оно вообще нужно

2022-11-13 16:45 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +      std::lock_guard lock(jobs_mutex);
1) Изменяется?
2) Почему снаружи лямбды? Что он тут синхронизирует? Выглядит так что он должен быть внутри лямбды.

2022-11-13 16:45 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +    threads.emplace_back(std::thread(worker));
`emplace_back` принимает аргументы конструктора, а вы тут используете конструктор перемещения, в этом нет необходимости, просто передайте `worker` и все

2022-11-13 16:45 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  graph_mutex.lock();
Вручную манипулировать блокировкой запрещено, нужно использовать `lock_guard`, исправьте везде.
Чтобы вызывать в контексте, можно делать так:
```cpp
...
{
  const std::lock_guard lock(graph_mutex);
  ...
}
...
```

2022-11-13 16:45 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  Graph::Depth current_depth = graph.get_vertex_depth(root_vertex_id);
const

2022-11-14 07:47 UTC, BasilKucherov commented on kucherov_sergeev/graph_generator.cpp
> +  int attempts_number = (one_vertex_start) ? (1) : (new_vertices_count);
<img width="442" alt="image" src="https://user-images.githubusercontent.com/112848146/201602579-359fbbb7-64f1-41d5-823f-7a70f83c5b06.png">
Я считал, что `generate_grey_branch` ответственен и за создание 'корня' своей ветки (Thread 1 должен создать Vertex 1, Thread 2 создает Vertex 2, ...), а потом уже создают по `new_vetrtices_count`.

2022-11-16 06:20 UTC, fedyasa approved these changes

2022-11-19 10:21 UTC, Friend-LGA requested changes

2022-11-19 10:21 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +              const auto to_vertex_id = get_random_vertex_id(to_vertex_ids);
Зачем поменяли местами? Зачем `get_random_vertex_id` выполнять внутри блокировки?

2022-11-19 10:21 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +                                         const Graph::VertexId root_id) const {
аргументы по значению не указываются как конст

2022-11-19 10:21 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  const Graph::Depth current_depth = graph.get_vertex_depth(root_vertex_id);
Почему убрали блокировку? `get_vertex_depth` использует разделяемые ресурсы, верно?

2022-11-19 10:21 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  int attempts_number = (one_vertex_start) ? (1) : (new_vertices_count);
Все верно. Подумайте, как реализовать данную логику без обсуждаемого усложнения.
Почему вы используете `one_vertex_start` только в одном условии? Если глобально посмотреть на картину, пораждаемые дальше ветви также, имеют только одну корневую вершину, верно?
В этом смысл использования рекурсии, так как у нас самоподобная структура, в виде фрактала.
А следовательно в рекурсивной функции не должно быть никакой условной логики, они все должны обрабатываться одинаково.

2022-11-19 17:48 UTC, fedyasa approved these changes

2022-11-21 06:16 UTC, Friend-LGA requested changes

2022-11-21 06:16 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  if (get_random_bool(new_vertex_probability)) {
Чем увеличивать вложенность, лучше делать ранний выход
```cpp
if (!statement) return;
```

2022-11-21 06:16 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
>                            int new_vertices_count,
Тебе, скорее всего, понадобится прокидывать сюда ещё и глубину вершины, это будет уже очень много аргументов, лучше будет сделать метод членом класса и забирать эти данные напрямую из `params`

2022-11-21 06:16 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +    const std::lock_guard lock(graph_mutex);
Блокировки добавляют задержки, при любой возможности мы хотим их избегать, попробуй переписать логику так, чтобы избавиться от этой блокировки.

2022-11-21 07:08 UTC, Friend-LGA approved these changes

2022-11-21 07:08 UTC, merged