kuzminskiy_stafeev/task_07
Friend-LGA/msu_course_cpp_323_2022 pull request #103
Opened 2022-11-18 16:06 UTC by KuzmaLine

2022-11-18 16:30 UTC, Jecteroid approved these changes

2022-11-20 22:14 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph_generator.cpp
> +    workers_.emplace_back(tmp);
Вопрос решён)

2022-12-05 20:33 UTC, Friend-LGA requested changes

2022-12-05 20:33 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.hpp
> +class GraphGenerationController {
`GraphGenerator` и `GraphGenerationController` - разные классы и сущности, зачем вы их объединили в один файл? Разъедините. В `graph_generator.[cpp|hpp]` вообще изменений не должно быть, по-хорошему.

2022-12-05 20:33 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +    stop();
Вы же тут вызываете `stop`, а не `join`, логично было бы тогда проверить на правильный статус, а не на низкоуровневый `joinable`

2022-12-05 20:33 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  state_ = State::ShouldTerminate;
будет не лишним также добавить ассерт на проверку статуса

2022-12-05 20:33 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +        state_ = State::Idle;
Логику статусов, лучше реализовать немного по-другому. Смотрите, у нас есть у воркера определенный интерфейс: `start()`, `stop()`, вот в зависимости от этого интерфейса у него и меняется статус. Когда кто-то вызвал `start()` - он сказал воркеру, что тот должен работать. Когда был вызван `stop()`, значит воркер должен остановиться. И вот к `Idle` он возвращается уже после `Terminate`

2022-12-05 20:33 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  }
Заполнить массив воркеров имеет смысл при создании контроллера. А вот запустить их уже на этапе генерации

2022-12-05 20:57 UTC, Friend-LGA requested changes
Задание читали? У вас логгер вызывается только из одного потока? Его тоже нужно синхронизировать.

2022-12-06 11:13 UTC, KuzmaLine commented
> Задание читали? Логгер тоже нужно сделать потокобезопасным.

Вы хотите, чтобы я внутрь логгера просто добавил мьютексы или запуск самого логгера?

2022-12-11 11:08 UTC, Friend-LGA requested changes
> Вы хотите, чтобы я внутрь логгера просто добавил мьютексы или обращение к самому логгера?

Внутрь самого логгера

2022-12-11 11:08 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generation_controller.cpp
> +  const auto get_job_callback = [this]() -> std::optional<JobCallBack> {
`this` вы захватили чтобы иметь доступ к `jobs_`? Целый `this` нам для этого не нужен, захватывать такие переменные можно так:
```cpp
[&jobs = jobs_]
```

2022-12-11 11:08 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generation_controller.cpp
> +  }
Раз мы знаем количество объектом, можем мы использовать `workers_.reserve(threads_count_);`?

2022-12-11 11:08 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generation_controller.cpp
> +        const std::lock_guard<std::mutex> guard(log_mutex);
Почему именно `log_mutex`? Откуда такая информация что мьютекс связан с логом?

2022-12-11 11:24 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generation_controller.cpp
> +  thread_ = std::thread([this]() {
Аналогично, захватывать целый `this` нет необходимости

2022-12-11 11:24 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generation_controller.cpp
> +                        &graphs_ready_count, &log_mutex, i, this]() {
Аналогично, захватывать целый `this` нет необходимости

2022-12-11 14:27 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph_generation_controller.cpp
> +  }
В list нельзя зарезервировать количество элементов

2022-12-12 06:10 UTC, Friend-LGA requested changes

2022-12-12 06:10 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_logger.cpp
>    const auto& current_date_time = get_current_date_time();
Лишняя логика внутри лока

2022-12-12 06:10 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generation_controller.cpp
> +      gen_started_callback(i);
Зря ты совсем блокировки убрал

2022-12-12 07:10 UTC, Friend-LGA approved these changes

2022-12-12 07:12 UTC, merged