fedotov_chuvashov/task_07
Friend-LGA/msu_course_cpp_323_2022 pull request #104
Opened 2022-11-18 17:31 UTC by wowonline

2022-11-19 10:54 UTC, Friend-LGA requested changes
Что у вас там с форматированием? Проверка на линтер не прошла.

2022-12-05 20:55 UTC, Friend-LGA requested changes

2022-12-05 20:55 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.hpp
> +class GraphGenerationController {
`GraphGenerator` и `GraphGenerationController` - разные классы и сущности, зачем вы их объединили в один файл? Разъедините. В `graph_generator.[cpp|hpp]` вообще изменений не должно быть, по-хорошему.

2022-12-05 20:55 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +        state_ = State::Working;
Логику статусов, лучше реализовать немного по-другому. Смотрите, у нас есть у воркера определенный интерфейс: `start()`, `stop()`, вот в зависимости от этого интерфейса у него и меняется статус. Когда кто-то вызвал `start()` - он сказал воркеру, что тот должен работать. Когда был вызван `stop()`, значит воркер должен остановиться. И вот к `Idle` он возвращается уже после `Terminate`

Соответственно, статус должен изменяться сразу при вызове `start`

2022-12-05 20:55 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +  if (thread_.joinable())
Вы же тут вызываете `stop`, а не `join`, логично было бы тогда проверить на правильный статус, а не на низкоуровневый `joinable`

2022-12-05 20:55 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +      gen_started_callback(i);
А вы уверены, что внутри коллбэка у вас потокобезопасная логика?

2022-12-05 20:55 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +      gen_finished_callback(i, std::move(graph));
анаогичный вопрос

2022-12-05 20:55 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +  }
Заполнить массив воркеров имеет смысл при создании контроллера. А вот запустить их уже на этапе генерации

2022-12-05 20:55 UTC, Friend-LGA commented on fedotov_chuvashov/main.cpp
> +using namespace uni_course_cpp;
`using namespace` использовать запрещено

2022-12-05 20:55 UTC, Friend-LGA commented on fedotov_chuvashov/main.cpp
>                                         std::string content,
строка - это не примитивный тип, а значит и передавать её нужно как?

2022-12-05 20:57 UTC, Friend-LGA requested changes
Задание читали? Логгер тоже нужно сделать потокобезопасным.

2022-12-11 11:29 UTC, Friend-LGA requested changes
1) Файл нужно называть 1 в 1 как и название класса, только, естественно, следуя конвенции. Если у вас класс называется полностью `GraphGenerationController` то и файл, соответственно, должен быть назван аналогично `graph_generation_controller`

2) Ещё раз спрашиваю, задание внимательно читали?
    ```cpp
    Worker::~Worker() {
      // Деструктор обязан очищать все ресурсы, которыми владеет объект
      stop();
    }
    ```

2022-12-11 11:29 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.hpp
> +#include <optional>
Зачем они тут добавились?

2022-12-11 11:29 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +#include <functional>
Зачем изменили?

2022-12-11 11:29 UTC, Friend-LGA commented on fedotov_chuvashov/logger.cpp
>    std::cout << string;
Что-то я в прошлом задании проглядел, почему у вас `get_current_date_time` не используется?

Edit: воу воу воу, нашел, вы его извне вызываете. Ну c'mon, это же отвественность логгера подставлять дату к логам. зачем при каждом вызове логгера, внешний пользователь должен сам из логгера вызывать генерацию даты, это безумие.

2022-12-11 11:29 UTC, Friend-LGA commented on fedotov_chuvashov/graph_gen_controller.cpp
> +    : thread_(), get_job_callback_(get_job_callback) {}
1) `thread_` итак создастся, без вызова в конструкторе.
2) nit: Конструкторы без тела могут быть записаны в `hpp`

2022-12-11 11:29 UTC, Friend-LGA commented on fedotov_chuvashov/graph_gen_controller.cpp
> +  thread_ = std::thread([this]() {
`this` вы захватили чтобы иметь доступ к `state_` и `get_job_callback_`? Целый `this` нам для этого не нужен, захватывать такие переменные можно так:
```cpp
[&state = state_, &get_job_callback = get_job_callback_]
```

2022-12-11 11:29 UTC, Friend-LGA commented on fedotov_chuvashov/graph_gen_controller.cpp
> +  const auto worker_callback = [this]() -> std::optional<JobCallback> {
Аналогично, захватывать целый `this` нет необходимости

2022-12-11 11:29 UTC, Friend-LGA commented on fedotov_chuvashov/graph_gen_controller.cpp
> +                        &graphs_generated, i, this]() {
Аналогично, захватывать целый `this` нет необходимости

2022-12-11 11:29 UTC, Friend-LGA commented on fedotov_chuvashov/graph_gen_controller.cpp
> +      auto graph = graph_generator_.generate();
Почему генерация графа находится под мьютексом, чтобы избежать выйгрыша в производительности?

2022-12-11 11:29 UTC, Friend-LGA commented on fedotov_chuvashov/graph_gen_controller.cpp
> +  }
Раз мы знаем количество объектом, можем мы использовать `workers_.reserve(threads_count_);`?

2022-12-11 18:06 UTC, wowonline commented on fedotov_chuvashov/graph_gen_controller.cpp
> +  }
workers_ это deque

2022-12-12 06:45 UTC, Friend-LGA requested changes

2022-12-12 06:45 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generation_controller.cpp
>        gen_started_callback(i);
Коллбэки потокобезопасные?

2022-12-12 06:45 UTC, Friend-LGA commented on fedotov_chuvashov/main.cpp
>                                         uni_course_cpp::Logger& logger) {
А где логгер исползуется?

2022-12-12 07:16 UTC, Friend-LGA requested changes

2022-12-12 07:16 UTC, Friend-LGA commented on fedotov_chuvashov/logger.cpp
> +  std::lock_guard<std::mutex> lock(logger_mutex_);
const

2022-12-12 07:16 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generation_controller.cpp
> +        ++graphs_generated;
Вынеси из лока

2022-12-12 07:20 UTC, Friend-LGA approved these changes

2022-12-12 07:22 UTC, merged