matveev_burikova/task_07
Friend-LGA/msu_course_cpp_323_2022 pull request #106
Opened 2022-11-19 12:58 UTC by matvlaale

2022-11-19 13:03 UTC, AnnaBurikova approved these changes

2022-12-05 20:18 UTC, Friend-LGA requested changes

2022-12-05 20:18 UTC, Friend-LGA commented on matveev_burikova/graph_generation_controller.cpp
> +          printf("{%d gen_started}\n", index);
У нас вроде есть логгер, который все это печатает? Зачем ещё лишние логи?

2022-12-05 20:18 UTC, Friend-LGA commented on matveev_burikova/graph_generation_controller.hpp
> +    void start(std::atomic<int>& waiting_jobs_count);
Что это за интерфейс такой? Зачем воркеру об этом знать? Он просто выполняет работу, у него же есть `get_job_callback_`, этого для него должно быть более чем достаточно.
`waiting_jobs_count` - это какая-то внешняя информация

2022-12-05 20:18 UTC, Friend-LGA commented on matveev_burikova/graph_generation_controller.cpp
> +        waiting_jobs_count = waiting_jobs_count - 1;
Если хотите контролировать количество выполненных работ, это должно быть сделано на более высоком уровне

2022-12-05 20:18 UTC, Friend-LGA commented on matveev_burikova/graph_generation_controller.cpp
> +    worker.~Worker();
Зачем вызывать деструктор? Он итак автоматически вызывается при удалении объекта. Вы должны оперировать нормальным интерфейсом. Что вы тут пытаетесь сделать? Наверное просто остановить всех воркеров, верно?

2022-12-05 20:18 UTC, Friend-LGA commented on matveev_burikova/graph_generation_controller.cpp
> +          gen_started_callback(index);
А мы уверены, что внутри коллбэка у нас потокобезопасная логика?

2022-12-05 20:18 UTC, Friend-LGA commented on matveev_burikova/graph_generation_controller.cpp
> +          gen_finished_callback(index, std::move(graph));
аналогичный вопрос

2022-12-05 20:18 UTC, Friend-LGA commented on matveev_burikova/graph_generation_controller.cpp
> +    workers_.emplace_back(get_job_callback);
Заполнить массив воркеров имеет смысл при создании контроллера. А вот запустить их уже на этапе генерации

2022-12-05 20:18 UTC, Friend-LGA commented on matveev_burikova/main.cpp
> +const int handle_threads_count_input() {
нельзя возвращать конст данные по значению из функции. Так получается что вы за внешнего пользователя решаете, какими должны быть его данные.

2022-12-10 13:57 UTC, AnnaBurikova approved these changes

2022-12-11 11:57 UTC, Friend-LGA requested changes

2022-12-11 11:57 UTC, Friend-LGA commented on matveev_burikova/graph_generation_controller.cpp
> +      callback_mutex.lock();
Обсуждали уже в прошлых задачах, что вручную нельзя управлять блокировкой. А вдруг у тебя эксепшен вылетит внутри `gen_started_callback()`, что тогда? Тогда у нас останется вечная блокировка.

2022-12-11 11:57 UTC, Friend-LGA commented on matveev_burikova/graph_generation_controller.cpp
> +  assert(state_ != State::Idle);
1) Воу воу воу! Объект должен иметь возможность удалиться в любом случае, блокировать деструктор нельзя.
2) Какой смысл в `assert` и `if` подряд? Они проверяют одно и тоже

2022-12-11 11:57 UTC, Friend-LGA commented on matveev_burikova/graph_generation_controller.cpp
> +using JobCallback = std::function<void()>;
Уже объявлен в `hpp`, дубликат

2022-12-11 11:57 UTC, Friend-LGA commented on matveev_burikova/graph_generation_controller.cpp
> +    workers_.emplace_back(get_job_callback);
Раз мы знаем количество объектом, можем мы использовать `workers_.reserve(threads_count_);`?

2022-12-11 11:57 UTC, Friend-LGA commented on matveev_burikova/graph_generation_controller.cpp
> +    jobs_.emplace_back([this, &gen_started_callback, &gen_finished_callback,
`this` вы захватили чтобы иметь доступ к `graph_generator_`? Целый `this` нам для этого не нужен, захватывать такие переменные можно так:
```cpp
[&graph_generator = graph_generator_]
```

2022-12-11 11:57 UTC, Friend-LGA commented on matveev_burikova/graph_generation_controller.cpp
> +        return;
Статус же должен возвращаться гдле-то в состояние `Idle`? Наверное, здесь?

2022-12-11 12:12 UTC, matvlaale commented on matveev_burikova/graph_generation_controller.cpp
> +using JobCallback = std::function<void()>;
Если его убрать, то программа не видит JOBCALLBACK в типе возвращаемого значеания в слелующей фугнкции

2022-12-11 12:26 UTC, matvlaale commented on matveev_burikova/graph_generation_controller.cpp
> +        return;
Почему он должен возвращаться в Idle? Когда кончились все работы? А тогда когда он считается в состоянии Working, только во время выполнения работы? Или до тех пор, пока все работы не кончатся?

2022-12-11 12:35 UTC, matvlaale commented on matveev_burikova/graph_generation_controller.cpp
> +    workers_.emplace_back(get_job_callback);
Нет не можем, потому что для list такая операция невозможна. А если брать другую структуру, то надо писать отдельно новый конструктор копирования

2022-12-11 13:06 UTC, AnnaBurikova approved these changes

2022-12-12 05:51 UTC, AnnaBurikova approved these changes

2022-12-12 06:03 UTC, Friend-LGA requested changes

2022-12-12 06:03 UTC, Friend-LGA commented on matveev_burikova/graph_generation_controller.cpp
> +  assert(state_ != State::ShouldTerminate);
Почему?

2022-12-12 06:03 UTC, Friend-LGA commented on matveev_burikova/graph_generation_controller.cpp
> +  if (state_ != State::ShouldTerminate)
Аналогично

2022-12-12 06:03 UTC, Friend-LGA commented on matveev_burikova/graph_generation_controller.hpp
> +using JobCallback = std::function<void()>;
Почему здесь?

2022-12-12 07:06 UTC, Friend-LGA approved these changes

2022-12-12 07:07 UTC, merged