mamedov_antyukhov/task_06
Friend-LGA/msu_course_cpp_323_2022 pull request #107
Opened 2022-11-20 18:13 UTC by sm0kebamb0o

2022-11-20 18:17 UTC, chereshnya123 approved these changes

2022-11-21 06:46 UTC, Friend-LGA requested changes

2022-11-21 06:46 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator.hpp
> +                            Graph::Depth cur_depth) const;
Почему публичные? Кто их ещё использует?

2022-11-21 06:46 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator.cpp
> +  }
`assert`

2022-11-21 06:46 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator.cpp
> +  std::atomic<int> jobs_number(new_vertices_count);
Давай единого стиля записи придерживаться

2022-11-21 06:46 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator.cpp
> +      graph.get_vertex_ids_at_depth(kGraphBaseDepth - 1)[0];
Чем выдумывать данные, лучше передать конкретные данные извне

2022-11-21 06:46 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator.cpp
> +  }
```cpp
const Graph::VertexId new_vertex_id = []() {
    const std::lock_guard graph_lock(graph_mutex);
    new_vertex_id = graph.add_vertex();
    graph.add_edge(root_vertex_id, new_vertex_id);
    return ...
}();
```

2022-11-21 07:13 UTC, Friend-LGA approved these changes

2022-11-21 07:16 UTC, merged