mamedov_antyukhov/task 07
Friend-LGA/msu_course_cpp_323_2022 pull request #109
Opened 2022-11-25 19:42 UTC by sm0kebamb0o

2022-11-26 08:00 UTC, chereshnya123 approved these changes

2022-12-05 20:38 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator_controller.cpp
> +#include "graph_generator_controller.hpp"
Вообще, с точки зрения английского языка более правильно будет `graph_generation_controller`, если переводить на русский, у вас написано "граф генератор контроллер", а должно быть "контроллер генерации графа". Более того, у вас класс называется `GraphGenerationController`, а файл `graph_generator_controller`, так делать нельзя, файл должен называться аналогично классу, который он содержит.

2022-12-05 20:40 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator_controller.cpp
> +        state_ = State::Working;
Логику статусов, лучше реализовать немного по-другому. Смотрите, у нас есть у воркера определенный интерфейс: `start()`, `stop()`, вот в зависимости от этого интерфейса у него и меняется статус. Когда кто-то вызвал `start()` - он сказал воркеру, что тот должен работать. Когда был вызван `stop()`, значит воркер должен остановиться. И вот к `Idle` он возвращается уже после `Terminate`

Соответственно, статус должен изменяться сразу при вызове `start`

2022-12-05 20:40 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator_controller.cpp
> +  }
Заполнить массив воркеров имеет смысл при создании контроллера. А вот запустить их уже на этапе генерации

2022-12-05 20:41 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator_controller.cpp
> +      gen_started_callback(i);
А вы уверены, что внутри коллбэка у вас потокобезопасная логика?

2022-12-05 20:41 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator_controller.cpp
> +      gen_finished_callback(i, std::move(graph));
аналогичный вопрос

2022-12-05 20:41 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator_controller.cpp
> +  state_ = State::ShouldTerminate;
Было бы не лишним проверить правильность статуса

2022-12-05 20:41 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator_controller.cpp
> +  thread_ = std::thread([this]() {
Было бы не лишним проверить правильность статуса

2022-12-05 20:47 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator_controller.cpp
> +  thread_ = std::thread([this]() {
Если у нашего объекта есть ресурсы, которые должны быть остановлены вручную, то обязан быть деструктор, который убедится, что все ресурсы удалены.

Представьте что вы вызвали `start` и забыли вызвать `stop`, по идее программа должна будет упасть, так как тред не может быть уничтожен, пока не вызван `join` или `detach`. Класс должен всегда отвечать за свою безопасность

2022-12-05 20:47 UTC, Friend-LGA commented on mamedov_antyukhov/main.cpp
> +                                       std::string graph_description) {
И почему изменили?

2022-12-05 20:57 UTC, Friend-LGA requested changes
Задание читали? У вас логгер вызывается только из одного потока? Его тоже нужно синхронизировать.

2022-12-07 16:08 UTC, sm0kebamb0o commented
Здравствуйте, я не совсем понимаю, что нужно сделать с логгером: если мы хотим, чтобы у нас выводились в файл записи вида: начало генерации i-го графа, конец генерации i-го графа (нет сторонних записей в таком блоке), то тогда придется существенно изменить структуру логгера, при этом  основываясь на логике графа, либо можно было бы поставить мьютексы и программа сведется по большей части к параллельной.

2022-12-11 11:31 UTC, Friend-LGA commented
> Здравствуйте, я не совсем понимаю, что нужно сделать с логгером: если мы хотим, чтобы у нас выводились в файл записи вида: начало генерации i-го графа, конец генерации i-го графа (нет сторонних записей в таком блоке), то тогда придется существенно изменить структуру логгера, при этом основываясь на логике графа, либо можно было бы поставить мьютексы и программа сведется по большей части к параллельной.

Поставьте один мьютекс, внутри логгера

2022-12-11 11:43 UTC, Friend-LGA requested changes
> Здравствуйте, я не совсем понимаю, что нужно сделать с логгером: если мы хотим, чтобы у нас выводились в файл записи вида: начало генерации i-го графа, конец генерации i-го графа (нет сторонних записей в таком блоке), то тогда придется существенно изменить структуру логгера, при этом основываясь на логике графа, либо можно было бы поставить мьютексы и программа сведется по большей части к параллельной.

Поставьте один мьютекс, внутри логгера

2022-12-11 11:43 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generation_controller.cpp
> +    while (state_ != State::ShouldTerminate) {
Какая-то неоднозначная логика. А если `status == Idle`, цикл тоже должен выполняться?
Тут скорее более однозначной записью будет что-то типа
```cpp
while (true) {
  if (state_ == State::ShouldTerminate) {
    state_ = State::Idle;
    return;
  }
}
```

2022-12-11 11:43 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generation_controller.cpp
> +  thread_ = std::thread([this]() {
`this` вы захватили чтобы иметь доступ к `state_` и `get_job_callback_`? Целый `this` нам для этого не нужен, захватывать такие переменные можно так:
```cpp
[&state = state_, &get_job_callback = get_job_callback_]
```

2022-12-11 11:43 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generation_controller.cpp
> +      [this]() -> std::optional<GraphGenerationController::JobCallback> {
Аналогично, захватывать целый `this` нет необходимости

2022-12-11 11:43 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generation_controller.cpp
> +    jobs_.push([&gen_started_callback, &gen_finished_callback, this, i,
Аналогично, захватывать целый `this` нет необходимости

2022-12-11 11:43 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generation_controller.cpp
> +  }
Раз мы знаем количество объектом, можем мы использовать `workers_.reserve(threads_count_);`?

2022-12-11 11:43 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generation_controller.cpp
> +        std::lock_guard<std::mutex> gen_start_lock(gen_mutex);
Изменяется?

2022-12-11 11:43 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generation_controller.cpp
> +        std::lock_guard<std::mutex> gen_finish_lock(gen_mutex);
Аналогично

2022-12-11 16:01 UTC, sm0kebamb0o commented on mamedov_antyukhov/graph_generation_controller.cpp
> +  }
Worker - list, мы конечно можем по идеи resize сделать, но вставка элементов же все равно будет через insert или emplace, поэтому разницы быть не должно

2022-12-11 16:04 UTC, sm0kebamb0o commented on mamedov_antyukhov/graph_generation_controller.cpp
> +    while (state_ != State::ShouldTerminate) {
Вроде бы в 6 задании как раз наоборот меняли ваш вариант на мой)

2022-12-12 06:50 UTC, Friend-LGA requested changes

2022-12-12 06:50 UTC, Friend-LGA commented on mamedov_antyukhov/logger.cpp
>    const std::string current_date_time = get_current_date_time();
1) изменяется?
2) `get_current_date_time` тоже требует синхронизации?

2022-12-12 07:23 UTC, merged