afanasev_krymskiy/task_07
Friend-LGA/msu_course_cpp_323_2022 pull request #116
Opened 2022-12-04 23:55 UTC by nikitanmlk

2022-12-05 06:34 UTC, ludmik approved these changes

2022-12-05 21:02 UTC, Friend-LGA requested changes

2022-12-05 21:02 UTC, Friend-LGA commented on afanasev_krymskiy/graph_generation_controller.cpp
> +    workers_.emplace_back(job_optional);
Заполнить массив воркеров имеет смысл при создании контроллера. А вот запустить их уже на этапе генерации

2022-12-05 21:02 UTC, Friend-LGA commented on afanasev_krymskiy/graph_generation_controller.cpp
> +      gen_started_callback(index);
А вы уверены, что внутри коллбэка у вас потокобезопасная логика?

2022-12-05 21:02 UTC, Friend-LGA commented on afanasev_krymskiy/graph_generation_controller.cpp
> +      gen_finished_callback(index, std::move(graph));
Аналогичный вопрос

2022-12-11 13:47 UTC, nikitanmlk commented on afanasev_krymskiy/logger.cpp
>    const auto result = get_current_date_time() + string;
не нужно, сделаю так:
```suggestion
namespace uni_course_cpp {
void Logger::log(const std::string& string) {
  const auto result = get_current_date_time() + string;
  const std::lock_guard lock(logger_mutex);
```

2022-12-11 19:41 UTC, ludmik approved these changes

2022-12-12 06:38 UTC, Friend-LGA requested changes

2022-12-12 06:38 UTC, Friend-LGA commented on afanasev_krymskiy/graph_generation_controller.hpp
> -#include <mutex>
Почему убрал?

2022-12-12 06:38 UTC, Friend-LGA approved these changes

2022-12-12 06:39 UTC, merged