zhang_xinyu/task_04
Friend-LGA/msu_course_cpp_323_2022 pull request #120
Opened 2022-12-05 20:52 UTC by YamyuCheung

2022-12-05 21:17 UTC, Friend-LGA requested changes
Я вижу, что у тебя в коде много странных, ненужных изменений, не несущих никакой пользы. Только из-за того что ты разбил все на разные файлы, это очень сложно ревьюить.

Объедини код обратно в один общий файл `graph.cpp`, чтобы весь новый код был внизу файла. Так я смогу увидеть все полезные изменения, которые ты внес в задачу.

А разбивать код на файлы будем уже в 5ой задаче.

2022-12-05 21:17 UTC, Friend-LGA commented on zhang_xinyu/graph_printing.hpp
> +#pragma once
`#pragma once` имеет смысл только на первом месте в файле, иначе у нас `#include` может быть вызван множество раз

2022-12-05 21:17 UTC, Friend-LGA commented on zhang_xinyu/graph_json_printing.hpp
> +#pragma once
аналогично

2022-12-05 21:17 UTC, Friend-LGA commented on zhang_xinyu/graph_json_printing.hpp
> +
в файле используются строки, значит должен быть `#include <string>`

2022-12-05 21:17 UTC, Friend-LGA commented on zhang_xinyu/graph_generator.hpp
> +#pragma once
аналогично

2022-12-05 21:17 UTC, Friend-LGA commented on zhang_xinyu/graph.hpp
> +#pragma once
аналогично

2022-12-05 21:17 UTC, Friend-LGA commented on zhang_xinyu/graph.hpp
> +  EdgeId next_edge_id_ = 0;
Что за ненужное переименование?
У тебя было
> ```cpp
> VertexId last_vertex_id_ = 0;
> EdgeId last_edge_id_ = 0;
> ```

2022-12-05 21:17 UTC, Friend-LGA commented on zhang_xinyu/graph.hpp
> +  std::unordered_map<VertexId, Vertex> vertices_;
Аналогично, почему переименовал `vertexes_` в `vertices`? Это бессмысленное изменение.

В коде не должно быть никаких ненужных изменений.
Проверь, больше нет никаких ненужных изменений.

2022-12-12 06:57 UTC, Friend-LGA requested changes

2022-12-12 06:57 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +  const std::unordered_map<VertexId, Vertex>& vertices() const {
Зачем переименовал?

2022-12-12 06:57 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +  const std::unordered_map<EdgeId, Edge>& edges() const { return edges_; }
Зачем переименовал?

2022-12-12 06:57 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +  bool has_edge(EdgeId id) const { return edges_.find(id) != edges_.end(); }
Используется где-нибудь?

2022-12-12 06:57 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +  VertexId next_vertex_id_ = 0;
Зачем переименовал?

2022-12-12 06:57 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +  EdgeId next_edge_id_ = 0;
Аналогично

2022-12-12 06:57 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +  std::unordered_map<VertexId, std::set<EdgeId>> connections_list_;
Зачем переименовал?

2022-12-18 13:40 UTC, Friend-LGA requested changes

2022-12-18 13:40 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +    std::vector<VertexId> EmptyVertex_ = {};
naming convention
https://github.com/Friend-LGA/uni_course_cpp/blob/master/practice/naming_convention.md

2022-12-18 13:40 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +    vertexes_of_depth_.emplace_back(EmptyVertex_);
Зачем 2 раза? Добавь комментарии

2022-12-18 13:40 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +    std::vector<VertexId> EmptyVertex = {};
Аналогично

2022-12-18 13:40 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +  float step = 1.0 / (depth - 2);
const

2022-12-18 13:40 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +    const auto& next_vertexes_depth =
Плохое название, лучше `next_depth_vertex_ids`

2022-12-18 13:40 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +      return "No color";
Лучше просто ронять приложение
```cpp
throw std::runtime_error("Failed to determine color");
```

2022-12-18 13:40 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +  const auto edge_id = edge.id();
Лишняя переменная

2022-12-18 13:40 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +bool is_number(std::string s) {
1) Давай не будем называть переменные одной буквой
2) Не примитивный тип передается как? По const ссылке

2022-12-18 14:11 UTC, Friend-LGA requested changes

2022-12-18 14:11 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +    std::vector<VertexId> empty_vertex_ = {};
naming convention
Зачем тут `_` на конце?

2022-12-18 14:11 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> -    vertexes_of_depth_.emplace_back(EmptyVertex_);
Почему убрал?
```suggestion
    // why?
    vertexes_of_depth_.emplace_back(EmptyVertex_);
    // why?
    vertexes_of_depth_.emplace_back(EmptyVertex_);
```

2022-12-18 14:11 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +    std::vector<VertexId> empty_vertex_ = {};
Аналогично

2022-12-18 14:30 UTC, YamyuCheung commented on zhang_xinyu/graph.cpp
> -    vertexes_of_depth_.emplace_back(EmptyVertex_);
// Потому что согласно условию задачи: "что в граф добавляется новая вершина и грань, соединяющая эти две вершины."

2022-12-18 15:10 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> -    vertexes_of_depth_.emplace_back(EmptyVertex_);
```
vertexes_of_depth_ ==
[[depth_0] [depth_1] [depth_2] [depth_3]]

[]
vertexes_of_depth_.emplace_back(EmptyVertex_);
[[depth_0]]
vertexes_of_depth_.emplace_back(EmptyVertex_);
[[depth_0] [depth_1]]
```

2022-12-18 15:12 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> -    vertexes_of_depth_.emplace_back(EmptyVertex_);
```
vertexes_of_depth_ ==
[[depth_1] [depth_2] [depth_3]]

[]
vertexes_of_depth_.emplace_back(EmptyVertex_);
[[depth_1]]
```

2022-12-18 15:18 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +  vertexes_of_depth_[kBaseDepth].emplace_back(vertex_id);
Получается, что ты кладешь вершину в вектор по индексу 1, тогда как внутри `vertexes_of_depth_` у тебя только один вектор, и значит доступен только индекс 0

Либо тебе нужно добавить 2 пустых вектора, чтобы был доступен индекс 1
Либо тебе нужно добавить 1 пустой вектор и использовать индекс 0

2022-12-18 15:42 UTC, Friend-LGA requested changes

2022-12-18 15:42 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +static constexpr Graph::Depth kBaseDepth = 0;
```suggestion
static constexpr Graph::Depth kBaseDepth = 1;
```

2022-12-18 15:42 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +    vertexes_of_depth_.emplace_back(empty_vertex);
Второй пустой вектор на индексе `kBaseDepth`

2022-12-18 15:42 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +    return vertexes_of_depth_.size() ? vertexes_of_depth_.size() - 1 : 0;
```suggestion
return vertexes_of_depth_.size() ? vertexes_of_depth_.size() : 0;
```

2022-12-18 15:52 UTC, Friend-LGA requested changes

2022-12-18 15:52 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +    //[[depth_0] [depth_1]]
1) Напиши на англ языке, так чтобы было понятно, словами
2) Комментарий пишется над строкой, а не под ней

2022-12-18 15:54 UTC, Friend-LGA requested changes
Падает
![Screenshot 2022-12-18 at 18 53 46](https://user-images.githubusercontent.com/5897136/208307448-31efec3f-8ead-4a78-8082-b1f12dbb95d7.png)

2022-12-18 16:05 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +    //[[depth_0] [depth_1]]
```
// add empty vector to keep vertices at depth 0 of the graph ... bla bla bla
```

2022-12-18 16:09 UTC, Friend-LGA requested changes
Лишние комментарии убери.

2022-12-18 16:09 UTC, Friend-LGA commented on zhang_xinyu/graph.cpp
> +    // add empty vector to keep vertices at depth 0 and depth 1 of the graph
Не правда, эта строка не связана с глубиной 0

2022-12-18 16:14 UTC, Friend-LGA approved these changes

2022-12-18 16:22 UTC, merged