kucherov_sergeev/task_07
Friend-LGA/msu_course_cpp_323_2022 pull request #121
Opened 2022-12-10 14:40 UTC by BasilKucherov

2022-12-11 12:05 UTC, Friend-LGA requested changes

2022-12-11 12:05 UTC, Friend-LGA commented on kucherov_sergeev/graph_generation_controller.cpp
> +  }
Просто скрываете происходящее, это выглядит не очень. То есть кто-то вызовет `start()`, а у вас ничего не произойдет. Не очень-то ожидаемое поведение. Вместо `if` лучше использовать здесь `assert` чтобы программа падала в такой неожидаемой ситуации

2022-12-11 12:05 UTC, Friend-LGA commented on kucherov_sergeev/graph_generation_controller.cpp
> +    while (true) {
`this` вы захватили чтобы иметь доступ к `state_` и `get_job_callback_`? Целый `this` нам для этого не нужен, захватывать такие переменные можно так:
```cpp
[&state = state_, &get_job_callback = get_job_callback_]
```

2022-12-11 12:05 UTC, Friend-LGA commented on kucherov_sergeev/graph_generation_controller.cpp
> +  const auto job_optional = [this]() -> std::optional<JobCallback> {
Аналогично, захватывать целый `this` нет необходимости

2022-12-11 12:05 UTC, Friend-LGA commented on kucherov_sergeev/graph_generation_controller.cpp
> +                        &current_jobs_count, &jobs_mutex, this]() {
Аналогично, захватывать целый `this` нет необходимости

2022-12-11 12:05 UTC, Friend-LGA commented on kucherov_sergeev/graph_generation_controller.cpp
> +      auto graph = graph_generator_.generate();
Почему генерация графа находится под мьютексом, чтобы избежать выйгрыша в производительности?

2022-12-11 12:05 UTC, Friend-LGA commented on kucherov_sergeev/graph_generation_controller.cpp
> +  std::mutex jobs_mutex;
`jobs_mutex` скорее подразумевает, что он синхронизирует вызовы к `jobs`, в у вас скорее `callback_mutex` или что-то в этом роде

2022-12-11 12:05 UTC, Friend-LGA commented on kucherov_sergeev/graph_generation_controller.cpp
> +  if (state_ == State::ShouldTerminate) {
Похоже на ошибочку. Какое здесь условие должно быть?

2022-12-11 12:05 UTC, Friend-LGA commented on kucherov_sergeev/graph_generation_controller.cpp
> +  if (state_ == State::Working) {
Аналогично, будет надежнее использовать `assert`

2022-12-11 17:06 UTC, BasilKucherov commented on kucherov_sergeev/graph_generator.cpp
> +#include <optional>
Вот вывод с проверки на компиляцию коммита https://github.com/Friend-LGA/msu_course_cpp_323_2022/pull/121/commits/ec5e8db494c3f447e6c1482e5c15e7279e6a1db4 :
```
kucherov_sergeev/graph_generator.cpp:187:28: error: no template named 'function' in namespace 'std'
  using JobCallback = std::function<void()>;
                      ~~~~~^
kucherov_sergeev/graph_generator.cpp:188:25: error: use of undeclared identifier 'JobCallback'
  auto jobs = std::list<JobCallback>();
                        ^
kucherov_sergeev/graph_generator.cpp:207:57: error: no template named 'optional' in namespace 'std'
                                 &jobs_mutex]() -> std::optional<JobCallback> {
                                                   ~~~~~^
kucherov_sergeev/graph_generator.cpp:207:66: error: use of undeclared identifier 'JobCallback'
                                 &jobs_mutex]() -> std::optional<JobCallback> {
                                                                 ^
kucherov_sergeev/graph_generator.cpp:216:21: error: no member named 'nullopt' in namespace 'std'
        return std::nullopt;
               ~~~~~^
5 errors generated.
Error: Process completed with exit code 1.
```

После исправления других реджектов я попробовал убрать эти библиотеки, но получил те же ошибки компиляции. Почему оно компилировалось успешно в прошлых заданиях я не знаю.

2022-12-11 17:54 UTC, fedyasa approved these changes

2022-12-12 07:04 UTC, Friend-LGA approved these changes

2022-12-12 07:04 UTC, merged