zhang _xinyu/task_06
Friend-LGA/msu_course_cpp_323_2022 pull request #138
Opened 2022-12-19 18:30 UTC by YamyuCheung

2022-12-21 11:36 UTC, Friend-LGA requested changes

2022-12-21 11:36 UTC, Friend-LGA commented on zhang_xinyu/graph_generator.cpp
> +constexpr Graph::Depth kRedEdgesDiff = 2;
Объясни, для чего нужна каждая константа, что она обозначает?

2022-12-21 11:36 UTC, Friend-LGA commented on zhang_xinyu/graph_generator.cpp
> +  std::atomic<bool> should_terminate(false);
Расскажи, зачем нужна эта переменная и почему она `atomic`?

2022-12-21 11:48 UTC, YamyuCheung commented on zhang_xinyu/graph_generator.cpp
> +  std::atomic<bool> should_terminate(false);
prevent race-conditions

2022-12-21 11:53 UTC, YamyuCheung commented on zhang_xinyu/graph_generator.cpp
> +  std::atomic<bool> should_terminate(false);
сохраняться значение new_vertexes_count

2022-12-21 11:55 UTC, YamyuCheung commented on zhang_xinyu/graph_generator.cpp
> +  std::atomic<bool> should_terminate(false);
сохраняться значение jobs_count(new_vertexes_count)

2022-12-21 12:08 UTC, YamyuCheung commented on zhang_xinyu/graph_generator.cpp
> +  std::atomic<bool> should_terminate(false);
prevent race condition

2022-12-21 12:13 UTC, YamyuCheung commented on zhang_xinyu/graph_generator.cpp
> +constexpr Graph::Depth kRedEdgesDiff = 2;
Значения
По возможности работать на этапе компиляции

2022-12-21 18:15 UTC, YamyuCheung commented on zhang_xinyu/graph_generator.cpp
> +  std::atomic<bool> should_terminate(false);
нужна для слежки состояния worker

2022-12-23 10:48 UTC, Friend-LGA approved these changes

2022-12-23 10:48 UTC, merged