Stafeev/task 01
Friend-LGA/msu_course_cpp_323_2022 pull request #16
Opened 2022-09-10 23:13 UTC by Jecteroid

2022-09-11 12:12 UTC, Friend-LGA requested changes
1) Переименуй ветку как в задании написано (аналогично с твоими одногруппниками)
2) Аналогично переименуй ПР (пулл реквест)
3) `g++` старой версии, обнови

2022-09-11 12:12 UTC, Friend-LGA commented on Stafeev_Artem/hello_world.cpp
> +}
Видишь красный знак, наведи на него мышку - высветится ошибка

2022-09-11 12:12 UTC, Friend-LGA requested changes
Название папки маленькими буквами

2022-09-11 15:39 UTC, Jecteroid commented
Исправил

2022-09-11 15:41 UTC, Jecteroid reviewed
Исправил

2022-09-12 06:20 UTC, Friend-LGA requested changes
Переименуй папку маленькими буквами

2022-09-12 06:35 UTC, Jecteroid reviewed
переименовал папку

2022-09-12 06:36 UTC, Friend-LGA approved these changes

2022-09-12 06:40 UTC, Jecteroid reviewed
исправил

2022-09-12 07:18 UTC, merged