stafeev_artem/task_02
Friend-LGA/msu_course_cpp_323_2022 pull request #34
Opened 2022-09-16 20:14 UTC by Jecteroid

2022-09-17 20:37 UTC, Friend-LGA requested changes
1) Обнови на общий мастер и удали `hello_world` программу первой задачи
2) Проверка на линтер не прошла, мой косяк, видимо из-за отсутствующего файла `.clang-format`, я его добавил, обновись на свежий мастер и проверка должна пройти успешно.

2022-09-17 20:37 UTC, Friend-LGA commented on stafeev_artem/task_02.cpp
> +enum { kVerticesCount = 13 };
1) Читай `rules` и `с vs с++`, голый `C` использовать запрещено
2) Зачем тебе `enum` вообще? Тебе нужна константа, лучше `constexpr` и скорее не локальный, а статичный

2022-09-17 20:37 UTC, Friend-LGA commented on stafeev_artem/task_02.cpp
> +#include <iostream>
Зачем?

2022-09-17 20:37 UTC, Friend-LGA commented on stafeev_artem/task_02.cpp
> +  using EdgeId = int;
Эти псевдонимы публичные или приватные?

2022-09-17 20:37 UTC, Friend-LGA commented on stafeev_artem/task_02.cpp
> +  void add_vertex() {}
?

2022-09-17 20:37 UTC, Friend-LGA commented on stafeev_artem/task_02.cpp
> +    edges.emplace(edges.end(), (Edge(count++, from_vertex_id, to_vertex_id)));
1) Лучше просто `emplace_back` использовать
```suggestion
    edges.emplace_back(count++, from_vertex_id, to_vertex_id);
```
2) Лучше выделить логику по генерации нового уникального id в отдельную функцию, например
```cpp
EdgeId get_new_edge_id() {
  return count++;
}
```

2022-09-17 20:37 UTC, Friend-LGA commented on stafeev_artem/task_02.cpp
> +  std::vector<Edge> edges;
Читай `naming_convention`

2022-09-17 20:37 UTC, Friend-LGA commented on stafeev_artem/task_02.cpp
> +  EdgeId count = 0;
1) Что за `count`? Обычно так называют размер массива, что в данном случае не применимо, так как в таком варианте было бы разумнее вернуть `edges.size()`, следовательно твоя переменная означает что-то другое, а что - совершенно не понятно. Назови переменную более выразительно, чтобы код можно было читать и понимать что он делает.
2) `EdgeId` не может называться `count` чисто логически.

2022-09-18 13:37 UTC, Jecteroid commented
> 1. Не проходит проверка сборки программы
> 2. Обнови на общий мастер и удали `hello_world` программу первой задачи
> 3. Проверка на линтер не прошла, мой косяк, видимо из-за отсутствующего файла `.clang-format`, я его добавил, обновись на свежий мастер и проверка должна пройти успешно.

Не понял как сделать второй пункт. Где этот hello_world удалить, что-то запутался.

2022-09-19 07:00 UTC, Friend-LGA requested changes

2022-10-02 07:29 UTC, Friend-LGA requested changes

2022-10-02 07:29 UTC, Friend-LGA commented on stafeev_artem/task_02.cpp
> +  EdgeId k_edges_count_ = 0;
Ну что это такое? Зачем этот `k_` префикс? Чем эти переменные отличаются от тех же `edges_` и `vertices_`?

2022-10-02 07:29 UTC, Friend-LGA commented on stafeev_artem/task_02.cpp
> +                    [&id](Vertex vert) { return vert.id() == id; })) {
Передавать и захватывать примитивные данные нужно по значению, а не по ссылке
```suggestion
                    [id](Vertex vert) { return vert.id() == id; })) {
```

2022-10-02 07:29 UTC, Friend-LGA commented on stafeev_artem/task_02.cpp
> +    return false;
Зачем тебе здесь `if`? Упрости запись:
```cpp
if (statement) {
  return true;
}
return false;
```
```cpp
return statement;
```

2022-10-03 10:53 UTC, Friend-LGA requested changes

2022-10-03 10:53 UTC, Friend-LGA commented on stafeev_artem/task_02.cpp
> +  EdgeId edges_count_ = 0;
1) `count` значит "количество". Как переменная с типом `id` может обозначать количество?
2) Эта переменная логически хранит не количество
3) Если бы ты хотел вернуть количество то это можно было бы сделать просто выполнив `edges_.size()` в таком случае в лишней переменной не было бы смысла.

2022-10-03 10:53 UTC, Friend-LGA commented on stafeev_artem/task_02.cpp
> +                       [id](Vertex vert) { return vert.id() == id; });
1) Не примитивные данные лучше передавать по конст ссылке
2) Переименуй переменную и старайся избегать сокращений без крайней необходимости
```suggestion
                       [id](const Vertex& vertex) { return vertex.id() == id; });
```

2022-10-09 06:42 UTC, Friend-LGA approved these changes

2022-10-09 10:00 UTC, merged