Ilichev_iurii/task_02
Friend-LGA/msu_course_cpp_323_2022 pull request #36
Opened 2022-09-17 22:35 UTC by gilerby

2022-09-19 06:51 UTC, Friend-LGA requested changes

2022-09-19 06:51 UTC, Friend-LGA commented on ilichev_iurii/graph.cpp
> +    return;
1) `throw std::error...`
2) Используй ассерты

2022-09-19 06:51 UTC, Friend-LGA commented on ilichev_iurii/graph.cpp
> +  auto edge = Edge(next_edge_id_++, from_vertex_id, to_vertex_id);
`const`?

2022-09-21 17:32 UTC, gilerby commented on ilichev_iurii/graph.cpp
> +  auto edge = Edge(next_edge_id_++, from_vertex_id, to_vertex_id);
исправил

2022-10-02 07:56 UTC, Friend-LGA requested changes

2022-10-02 07:56 UTC, Friend-LGA commented on ilichev_iurii/graph.hpp
> +  bool edge_correctness(VertexId from_vertex_id, VertexId to_vertex_id);
1) Плохое название "корректность грани", функция, в общем случае, должна называться как действие, например "проверить корректность грани" - `check_edge_correctness`
2) Слишком общее название, что значит "корректность"? Каждая функция должна проверять какую-то конкретную логику, и это должно быть явно видно из названия. А у тебя здесь выглядит так, что ты смешал разную логику в одной функции, и поэтому не придумал как её правильно назвать. Тут должно быть скорее что-то вроде `has_edge`.

2022-10-02 07:56 UTC, Friend-LGA commented on ilichev_iurii/graph.hpp
> +    Edge();
Зачем пустой конструктор?

2022-10-02 07:56 UTC, Friend-LGA commented on ilichev_iurii/graph.hpp
> +// An undirected graph, there can be only one edge between any two vertices
Никаких лишних комментариев в коде быть не должно, код должен быть достаточно выразительным, чтобы его можно было читать без комментариев. А задание написано в задании.

2022-10-02 07:56 UTC, Friend-LGA commented on ilichev_iurii/graph.hpp
> +  std::map<VertexId, std::list<EdgeId>> vertex_edges_;
Можешь оставить как есть, просто на заметку.
1) Тебе нужна сортировка в мапе? Если нет, то достаточно будет `unordered_map`
2) Почему ты выбрал лист? Чем тебе `vector` не угодил?

2022-10-02 07:56 UTC, Friend-LGA commented on ilichev_iurii/main.cpp
> +const int kVerticesCount = 14;
Читай `common_mistakes` насчет `const vs constexpr`

2022-10-02 07:56 UTC, Friend-LGA commented on ilichev_iurii/graph.cpp
> +  const auto next_vertex_id = VertexId(vertexes_.size());
Воу воу воу, палехче. 
Ты создаешь инт с помощью конструктора из размера массива. Это прям нестандартная запись во-первых, во-вторых у нас нет прямой связи между `id` вершины и размером коллекции, это логически разные сущности. Поэтому ты тут и пытаешься сделать конвертацию одного в другое, это тебе прямо намекает, что эти данные разные. Ты должен завести отдельную переменную, которая будет хранить в себе текущий `id` и возвращать следующее значение.

Для этого лучше будет завести отдельную функцию, например
```cpp
VertexId get_new_vertex_id()
```

2022-10-02 07:56 UTC, Friend-LGA commented on ilichev_iurii/graph.cpp
> +  vertex_edges_.insert({next_vertex_id, {}});
Есть более стандартная запись:
```cpp
vertex_edges_[next_vertex_id] = {};
```

2022-10-02 07:56 UTC, Friend-LGA commented on ilichev_iurii/graph.cpp
> +  // Checking that an edge can be added between these vertices
Опять лишние комментарии

2022-10-02 07:56 UTC, Friend-LGA commented on ilichev_iurii/graph.cpp
> +  assert(edge_correctness(from_vertex_id, to_vertex_id));
Вот оно, ты все проверки смешал в одну кучу, это тебе не поможет дебажить код. Смысл в том, чтобы каждая проверка тестировала минимальную логику, чтобы можно было быстро и легко выявить ошибку.
```suggestion
  assert(has_vertex(from_vertex_id));
  assert(has_vertex(to_vertex_id));
  assert(!has_edge(from_vertex_id, to_vertex_id));
```

2022-10-02 07:56 UTC, Friend-LGA commented on ilichev_iurii/graph.cpp
> +  const auto next_edge_id = EdgeId(edges_.size());
Аналогично

2022-10-02 07:56 UTC, Friend-LGA commented on ilichev_iurii/graph.cpp
> +}
Такие однострочные методы лучше писать напрямую в `.hpp`

2022-10-02 07:56 UTC, Friend-LGA commented on ilichev_iurii/graph.cpp
> +    : id_(id), from_vertex_id_(from_vertex_id), to_vertex_id_(to_vertex_id) {}
Конструктор без логики тоже можно писать напрямую в `.hpp`

2022-10-16 08:57 UTC, Friend-LGA commented
Ушел в академ

2022-10-16 08:57 UTC, closed without merging