Added graph and graph generation
Friend-LGA/msu_course_cpp_323_2022 pull request #39
Opened 2022-09-18 18:21 UTC by matvlaale

2022-09-18 18:22 UTC, matvlaale commented
Wrong naming

2022-09-19 07:26 UTC, Friend-LGA requested changes

2022-09-19 07:26 UTC, Friend-LGA commented on matveev_vladimir/graph.cpp
> +#include <assert.h>
`cassert`

2022-09-19 07:26 UTC, Friend-LGA commented on matveev_vladimir/graph.cpp
> +#include <iostream>
Зачем?

2022-09-19 07:26 UTC, Friend-LGA commented on matveev_vladimir/graph.cpp
> +  bool find_vertex(VertexId id) const {
`has_vertex`

2022-09-19 07:26 UTC, Friend-LGA commented on matveev_vladimir/graph.cpp
> +    if (!find_edge(from_vertex_id, to_vertex_id))
`assert`

2022-09-19 07:26 UTC, Friend-LGA commented on matveev_vladimir/graph.cpp
> +  bool find_edge(VertexId id_from, VertexId id_to) const {
Аналогично

2022-10-02 07:30 UTC, Friend-LGA approved these changes

2022-10-02 09:28 UTC, merged