kovalenko_lev/task_02
Friend-LGA/msu_course_cpp_323_2022 pull request #40
Opened 2022-09-18 20:11 UTC by klevvit

2022-09-18 21:18 UTC, Jedi314 approved these changes

2022-09-19 06:39 UTC, Friend-LGA requested changes

2022-09-19 06:39 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +  void add_vertex() { vertices_.emplace_back(vertices_.size()); }
```
VertexId get_new_vertex_id const;
```

2022-09-19 06:39 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +    edges_.emplace(edges_cnt_, from, to);
1) Без ненужных сокращений `cnt`?

2022-09-19 06:39 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +    }
Используй `assert`

2022-09-19 06:39 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +    ++edges_cnt_;
Аналогично

2022-10-02 08:43 UTC, Friend-LGA requested changes

2022-10-02 08:43 UTC, Friend-LGA commented on kovalenko_lev/edge.hpp
> +  Edge(Id id, Vertex::Id from, Vertex::Id to) : id_(id), from_(from), to_(to) {
`from` и `to` не пойдет, что это значит `от` и `до`? Назови нормально

2022-10-02 08:43 UTC, Friend-LGA commented on kovalenko_lev/edge.hpp
> +  static Id next_id(Id current) { return current + 1; }
1) Ошибаешься, эта логика не относится к грани. Грань вообще не знает что существуют друие грани. Все что она знает, это то что у неё есть какой-то id и id вершин. Все. О том, что есть некий следующий `next_id` может знать только более высокоуровневая сущность, то есть граф.
2) Эта логика не должна быть статик, она локальная для каждого графа. Вершины и грани всегда начинаются с `0` для каждого нового графа.
3) Эта логика должна быть полностью инкапсулирована от внешнего мира, должна гарантировать уникальность созданного `id`. В твоем же случае это не гарантируется, так как есть данные извне `current`, получается я могу 2 раза вызвать этот метод и получить один и тот же `id`, а они должны быть уникальными.

2022-10-02 08:43 UTC, Friend-LGA commented on kovalenko_lev/edge.hpp
> +      std::swap(from, to);
Усложняешь, вряд ли это тебе поможет

2022-10-02 08:43 UTC, Friend-LGA commented on kovalenko_lev/vertex.hpp
> +  static Id next_id(Id current) { return current + 1; }
Аналогично

2022-10-02 08:43 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +    auto vertex_id = generate_vertex_id();
`const`

2022-10-02 08:43 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +    auto edge_id = generate_edge_id();
`const`

2022-10-02 08:43 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +                   std::make_tuple(edge_id, from, to));
Можно стандартную запись использовать, а то это читать невозможно
```cpp
edges_[edge_id] = Edge(edge_id, from, to);
```

2022-10-02 08:43 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
>    void add_edge(Vertex::Id from, Vertex::Id to) {
`from`, `to`, переименуй

2022-10-02 08:43 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +    Vertex::Id ans = next_vertex_id_;
Что за `ans`?

2022-10-02 08:43 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +  mutable Edge::Id next_edge_id_ = 0;
Воу воу, палехче. Давай вот без этого всего. Я про `mutable`

2022-10-02 08:43 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +  Vertex::Id generate_vertex_id() const {
Как оно у тебя `const`, если данные меняются? Кого ты тут обмануть пытаешься?

2022-10-02 08:43 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +  std::map<Vertex::Id, std::set<Edge::Id>> connetions_;
Точно нужна сортировка? Можно более простой `unordered_map`

2022-10-02 08:43 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
>    void add_edge(Vertex::Id from, Vertex::Id to) {
Где ассерты? Был же комментарий
```cpp
assert(has_vertex(from));
assert(has_vertex(to));
assert(!has_edge(from, to))l
```

2022-10-02 08:43 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +  void add_vertex() { vertices_.emplace_back(vertices_.size()); }
Здесь конст был не нужен, опечатка. Ты должен был догадаться, когда тебе пришлось `mutable` добавлять.

2022-10-02 08:43 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +    }
Не исправил

2022-10-09 12:44 UTC, klevvit commented on kovalenko_lev/graph.hpp
> +                   std::make_tuple(edge_id, from, to));
Тогда надо для Edge создавать конструктор без аргументов и оператор присваивания...
Переписал на insert(std::make_pair()), тогда достаточно дефолтного конструктора копирования

2022-10-10 09:31 UTC, Friend-LGA commented on kovalenko_lev/edge.hpp
> +  Edge(Id id, Vertex::Id from, Vertex::Id to) : id_(id), from_(from), to_(to) {
Это как "копать от забора и до обеда". Тебе субъективно понятно, а надо чтобы ни у кого никаких вопросов не вызывало, кто с твоим кодом работать будет.

2022-10-10 09:34 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +    auto vertex_id = generate_vertex_id();
Тут логика простая, если данные не изменяются, значит они константные, значит помечаются как `const`, это делает код более безопасным и улучшает возможности по оптимизации компилятором.

2022-10-10 09:45 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +                   std::make_tuple(edge_id, from, to));
В таком случае можно просто вот так:
```cpp
edges_.emplace(edge_id, Edge(edge_id, from_vertex_id, to_vertex_id))
```
Так должна быть использована `move` семантика и мы тоже избежим создания лишних объектов и копирования. И лишний конструктор в `Edge` не понадобится

2022-10-10 10:51 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +    return to_vertices.find(to_vertex_id) != to_vertices.end();
Ты уверен что тебе нужен метод `get_connected_vertices`?
Не вижу чтобы ты его ещё где-то использовал. Опять усложняешь. Просто обойди коллекцию прямо здесь и верни сразу `boolean`, без вызова лишних методов и создания лишних структур данных.
Можно взять все грани от первой и все грани от второй и проверить есть ли между ними грань с одинаковым `id`

2022-10-10 10:51 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +  std::unordered_set<Vertex::Id> get_connected_vertices(
Лишний метод

2022-10-10 12:15 UTC, klevvit commented on kovalenko_lev/graph.hpp
> +    auto vertex_id = generate_vertex_id();
Оки) По дефолту писать const везде, где это имеет смысл, принято. Буду вырабатывать привычку)

2022-10-10 12:26 UTC, klevvit commented on kovalenko_lev/edge.hpp
> +  Edge(const Edge& other) = default;
As far as I remember, если прописать хотя бы один конструктор, то дефолтные конструкторы не генерируются, если явно их не прописать, как здесь. По поводу `insert` -> `emplace` - действительно, поправил. Конструктор копирования удалять не хочу, кода мало, никому не мешает, а пригодиться в будущем очень даже может

2022-10-10 12:42 UTC, klevvit commented on kovalenko_lev/graph.hpp
> +    return to_vertices.find(to_vertex_id) != to_vertices.end();
Разбить на две функции показалось мне здравой идеей, пожертвовать созданием временной структуры ради более прозрачного кода посчитал разумным. Плюс я мыслил в рамках операций, которые, скорее всего, понадобятся мне в будущем. Если я буду обходить граф (а для чего ещё мне может быть нужен этот граф?), то вполне логично завести метод, который возвращает все вершины, в которые можно попасть из данной.
Идея просмотреть все грани от первой и второй вершины прикольная, но там для оптимальной асимптотики тоже придется сортировать грани одной из двух вершин.

Хмм, возможно, я и правда зря здесь парюсь с асимптотикой, если мы будем использовать лишь небольшие или разреженные графы. Это так?

2022-10-10 12:44 UTC, klevvit commented on kovalenko_lev/graph.hpp
> +        std::make_pair(edge_id, Edge(edge_id, from_vertex_id, to_vertex_id)));
done

2022-10-10 12:45 UTC, klevvit commented on kovalenko_lev/graph.hpp
> +  std::unordered_set<Vertex::Id> get_connected_vertices(
Расписал комментом выше

2022-10-10 12:50 UTC, Friend-LGA commented on kovalenko_lev/edge.hpp
> +  Edge(const Edge& other) = default;
Давай удаляй все лишнее, понадобится - добавишь

2022-10-10 12:52 UTC, klevvit commented on kovalenko_lev/graph.hpp
> +    assert(from_vertex_id >= 0);
упс, это пропустил, ща сделаю

2022-10-10 12:52 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +    return to_vertices.find(to_vertex_id) != to_vertices.end();
Да, ты паришься и усложняешь. Сейчас нет надобности в данном методе, и не факт что появится. Давай возьмем за правило писать только тот код, который актуален на данный момент. А тебе сйечас нужно просто вернуть `boolean` без создания лишних временных структур.

2022-10-10 13:03 UTC, Friend-LGA commented on kovalenko_lev/graph.hpp
> +    return to_vertices.find(to_vertex_id) != to_vertices.end();
Можно не скрещивать первую и вторую, а просто проверить что `from` или `to` равны второй вершине.
Вообще обычно делают как, пишут плюс минут брут форсе решение, которое может быть неоптимальным, но на которое уходит намного меньше времени для написания. А потом, когда утыкаются в узкое место по производительности - тогда уже оптимизируют. Все сразу спланировать заранее невозможно и кусок кода, на который ты сегодня тратишь целый час, завтра уже может быть вообще удален. Поэтому не соит на первом этапе сразу с головой уходить в оптмизацию. Нужно, конечно, очевидные вещи оптимизировать, которые не требуют больших временных затрат.

2022-10-10 13:07 UTC, klevvit commented on kovalenko_lev/graph.hpp
> +    return to_vertices.find(to_vertex_id) != to_vertices.end();
done

2022-10-10 13:07 UTC, klevvit commented on kovalenko_lev/graph.hpp
> +  std::unordered_set<Vertex::Id> get_connected_vertices(
убрал

2022-10-10 13:15 UTC, Friend-LGA approved these changes

2022-10-10 13:31 UTC, merged