mamedov_timur/task_03
Friend-LGA/msu_course_cpp_323_2022 pull request #53
Opened 2022-09-22 14:23 UTC by sm0kebamb0o

2022-10-10 11:38 UTC, Friend-LGA requested changes
1) Ещё не сдал вторую
2) Где твоя пара, переименуй ПР

2022-10-16 10:36 UTC, Friend-LGA requested changes
1) Антюхов ещё не сдал вторую. Мамедов, мог бы и помочь ему, чтобы время не терять.
2) Почему у вас 2 ПРа? Выберите один, а второй закройте.

2022-10-22 07:35 UTC, Friend-LGA requested changes
Так как первая задача в паре - прощаю. Но по логике работы, перед тем, как я начинаю проверять, задача должна быть проверена вторым партнером в паре и должна быть из зааппрувлена (`approved`). То есть второй участник в паре должен сделать ревью, перед тем как его делаю я. Учитывая что вы сделали аналогичные ошибки второй задаче, видно что дополнительно не проверяли задачу.

2022-10-22 07:35 UTC, Friend-LGA commented on mamedov_timur/main.cpp
> +  fout.close();
Он автоматически сам не закрывается?

2022-10-22 07:35 UTC, Friend-LGA commented on mamedov_timur/main.cpp
> +void write_to_file(const std::string& graph_str, const std::string& file_name) {
1) Давайте без ненужных сокращений `str` -> `string`
2) В целом данному методу все равно что за строку писать в файл, поэтому можно вообще просто `graph_str` -> `string`

2022-10-22 07:35 UTC, Friend-LGA commented on mamedov_timur/main.cpp
> +  for (int i = 0; i < 14; i++) {
14 - `magic number`, таких магических цифр в коде быть не должно, все `magic number` обязаны быть вынесены в глобальные константы. Как у вас раньше и было. Зачем изменили?

2022-10-22 07:35 UTC, Friend-LGA commented on mamedov_timur/main.cpp
> +}
Сверьтесь с `main` из задания, чего у вас не хватает?
https://github.com/Friend-LGA/uni_course_cpp/tree/master/practice/task_03

2022-10-22 07:35 UTC, Friend-LGA commented on mamedov_timur/graph.json
> +}
Красный знак видите?

2022-10-22 07:35 UTC, Friend-LGA commented on mamedov_timur/graph.hpp
> +  void add_edge(VertexId first_vertex_id_, VertexId second_vertex_id_);
`naming_convention`

2022-10-22 07:35 UTC, Friend-LGA commented on mamedov_timur/graph.cpp
> +}
Конструкторы с пустым телом и однострочные методы принято записывать в `hpp` файле, так код получается более компактным.

2022-10-22 07:35 UTC, Friend-LGA commented on mamedov_timur/graph.cpp
> +    connections_[second_vertex_id_].emplace_back(new_edge_id);
Плохая практика не писать скобочки, если if и его тело не умещаются в одну строку

2022-10-22 07:35 UTC, Friend-LGA commented on mamedov_timur/graph.hpp
> +  const std::vector<EdgeId>& get_edges_of_vertex(VertexId vertex_id) const;
Вы получаете не грани, а только их `id`, поэтому и метод лучше так назвать.
`get_edge_ids_of_vertex`, или `get_connected_edge_ids`

2022-10-22 07:35 UTC, Friend-LGA commented on mamedov_timur/printing.cpp
> +  const auto connections = graph.get_edges_of_vertex(vertex.id());
1) Это не `connections`, а `edge_ids`
2) Чем делать полную копию данных, лучше взять ссылку

2022-10-22 07:35 UTC, Friend-LGA commented on mamedov_timur/printing.cpp
> +  auto it = connections.begin(), prev_it = it;
1) лучше не инициализировать несколько переменных одной строкой
2) Вам действительно нужна лишняя переменная, можно обойтись без неё?

2022-10-22 07:35 UTC, Friend-LGA commented on mamedov_timur/printing.cpp
> +    json_string << *prev_it << ", ";
```suggestion
    json_string << *std::prev(it) << ", ";
```

2022-10-22 07:35 UTC, Friend-LGA commented on mamedov_timur/printing.cpp
> +  json_string << *prev_it;
А если `connections.size() == 0`?

2022-10-22 07:35 UTC, Friend-LGA commented on mamedov_timur/printing.cpp
> +  const auto edges = graph.get_edges();
Чем делать полную копию данных, лучше взять ссылку, это намного более эффективно.

2022-10-22 07:35 UTC, Friend-LGA commented on mamedov_timur/printing.cpp
> +  json_string << print_edge(prev_it_edges->second, graph) << "\n\t]\n}";
Аналогично

2022-10-22 13:02 UTC, sm0kebamb0o commented on mamedov_timur/printing.cpp
> +  auto it = connections.begin(), prev_it = it;
Здесь вроде бы можно обойтись без лишней переменной, но надо if'ы написать, а, учитывая, что условие будет выполняться для каждого значения edge_id, то должно получиться менее эффективно, чем хранить одну переменную.

2022-10-22 13:38 UTC, sm0kebamb0o commented on mamedov_timur/printing.cpp
> +  json_string << print_edge(prev_it_edges->second, graph) << "\n\t]\n}";
В этих циклах std::prev сделать не получится, ведь там итератор по unordered_map, можно условия написать, но как будто хранить по одной переменной на цикл более эффективно.

2022-10-22 15:57 UTC, chereshnya123 approved these changes

2022-10-23 09:10 UTC, Friend-LGA requested changes

2022-10-23 09:10 UTC, Friend-LGA commented on mamedov_timur/printing.cpp
>    }
Писать неполный `for` считается плохой практикой. Выносить переменные во внешнюю зону видимости считается плохой практикой. Лучше упростить, как-нибудь, например так:
```suggestion
  if (!vertices.empty()) {
    bool is_first_iteration = true;
    for (auto it = vertices.cbegin(); it != vertices.cend(); ++it) {
      if (!is_first_iteration) {
        json_string << ",";
      }
      json_string << print_vertex(it->second, graph);
      is_first_iteration = false;
    }
  }
```

2022-10-23 09:10 UTC, Friend-LGA commented on mamedov_timur/printing.cpp
>    }
Аналогично

2022-10-23 11:21 UTC, chereshnya123 approved these changes

2022-10-24 09:40 UTC, Friend-LGA commented on mamedov_timur/Makefile
> +
Да вы издеваетесь. Свой код сами хоть просматриваете? Видите что ошибка осталась?

2022-10-28 17:01 UTC, chereshnya123 approved these changes

2022-10-29 14:01 UTC, Friend-LGA approved these changes

2022-10-29 15:54 UTC, merged