kucherov_vasilii/task_03
Friend-LGA/msu_course_cpp_323_2022 pull request #54
Opened 2022-09-24 20:17 UTC by BasilKucherov

2022-10-02 12:52 UTC, fedyasa approved these changes

2022-10-03 11:15 UTC, Friend-LGA requested changes
Не надо переименовывать файл без необходимости, из-за этого тяжело видеть внесенные изменения. В дальнейших задачах будем логику разбивать на файлы, тогда это будет актуально.

2022-10-03 11:15 UTC, Friend-LGA commented on kucherov_vasilii/graph_json_printer.cpp
> +void write_to_file(std::string graph_json, std::string file_name) {
Не примитивные данные передаются по `const` ссылке

2022-10-03 11:15 UTC, Friend-LGA commented on kucherov_vasilii/graph_json_printer.cpp
> +  const auto edges = graph.get_edges();
Зачем делать копию, лучше создать `const` ссылки

2022-10-03 11:15 UTC, Friend-LGA commented on kucherov_vasilii/graph_json_printer.cpp
> +  graph_json.pop_back();
А если `vertices.size() == 0` ничего не сомается?

2022-10-03 11:15 UTC, Friend-LGA commented on kucherov_vasilii/graph_json_printer.cpp
> +  const auto edge_vertices_ids = graph.get_edge_vertices_ids(edge);
Аналогично

2022-10-03 11:15 UTC, Friend-LGA commented on kucherov_vasilii/graph_json_printer.cpp
> +  edge_json.pop_back();
Аналогично

2022-10-03 11:15 UTC, Friend-LGA commented on kucherov_vasilii/graph_json_printer.cpp
> +}
Аналогично

2022-10-03 11:15 UTC, Friend-LGA commented on kucherov_vasilii/graph_json_printer.cpp
> +  }
Вы в граф добавили метод, который принимает грань и возвращает присоединенные id вершин. Эти данные уже есть в грани. Какой смысл в данном методе, и какое отношение он имеет к графу?)))

2022-10-03 11:15 UTC, Friend-LGA commented on kucherov_vasilii/graph_json_printer.cpp
> +  }
1) `vertex` - избыточная информация, как вы видите, в методе везде используется только `vertex.id()`, следовательно какие данные нужны этому методу?
2) Название кривоватое, давайте лучше например `get_connected_edge_ids`
3) Обходить все вершины в массиве довольно медленно, особенно если их будет 100500 штук, лучше добавьте лист связности, например `std::unordered_map<VertexId, std::vector<EdgeId>>adjacency_list_`

2022-10-09 17:16 UTC, BasilKucherov commented on kucherov_vasilii/graph_json_printer.cpp
> +  }
```suggestion
  const std::vector<EdgeId>& get_connected_edge_ids(VertexId vertex_id) const {
    return adjacency_list_.at(vertex_id);
  }
```
Переписал `get_vertex_edges_ids` в такую штуку. Вопрос по методу `unordered_map.at()`, судя по документации, он выбросит исключение, если не найдет переданный ключ. С другой стороны возвращать пустой вектор в таком случае неверно, так как в графе могут быть просто вершины без ребер. Собственно вопрос - допустима ли такая реализация, или выброс исключения тоже не очень хорошо?

2022-10-09 21:07 UTC, fedyasa approved these changes

2022-10-10 12:11 UTC, Friend-LGA requested changes
Переименуйте файл обратно, в прошлый раз писал.

2022-10-10 12:11 UTC, Friend-LGA commented on kucherov_vasilii/graph_json_printer.cpp
> +    auto edge_id = get_new_edge_id();
Все что не изменяется должно быть `const`

2022-10-10 12:11 UTC, Friend-LGA commented on kucherov_vasilii/graph_json_printer.cpp
> +    return adjacency_list_.at(vertex_id);
По вашему вопросу, как вариант, можно сделать так:
```suggestion
    if (!adjacency_list_.has(vertex_id)) {
      static const std::vector<EdgeId> empty_result;
      return empty_result;
    }
    return adjacency_list_.at(vertex_id);
```

2022-10-10 12:13 UTC, Friend-LGA commented on kucherov_vasilii/graph_json_printer.cpp
> +  }
Ниже ответил

2022-10-11 04:12 UTC, fedyasa approved these changes

2022-10-16 10:40 UTC, Friend-LGA approved these changes
Исправьте ошибку и можете мерджить

2022-10-16 10:40 UTC, Friend-LGA commented on kucherov_vasilii/graph_generator.cpp
> +    adjacency_list_[to_vertex_id].push_back(edge_id);
Баг. А если `from_vertex_id` == `to_vertex_id`, тогда вы в вектор добавите 2 одинаковых значения.

2022-10-16 10:43 UTC, Friend-LGA approved these changes
И вот эти тоже

2022-10-16 10:43 UTC, Friend-LGA commented on kucherov_vasilii/graph_generator.cpp
> +    for (const auto& edge_id : connected_edge_ids) {
Примитивные данные захватываются по значению
```cpp
for (const auto edge_id : connected_edge_ids) {
```

2022-10-16 10:43 UTC, Friend-LGA commented on kucherov_vasilii/graph_generator.cpp
> +std::string print_edge(const Graph::Edge& edge, const Graph& graph) {
`graph` не используется, зачем он здесь?

2022-10-16 10:56 UTC, Friend-LGA approved these changes
И ещё, перенесите текущий код в новую папку "kucherov_sergeev"

2022-10-16 11:47 UTC, BasilKucherov commented
После переименования папки `kucherov_vasilii` -> `kucherov_sergeev` не прошла проверка на компиляцию (насколько понял он пытался что то скомпилировать в папке `kucherov_vasilii`). В своем репозитории в текущей ветке `kucherov_vasilii/task_03` я нажал `Sync fork` и проверка прошла. Хотелось бы быть уверенным что это ничего не испортит перед мерджем в основную ветку.
<img width="710" alt="image" src="https://user-images.githubusercontent.com/112848146/196033579-5391e288-5fda-4cf5-b2b1-52df1b0ba55f.png">

2022-10-16 12:18 UTC, merged

2022-10-18 09:07 UTC, Friend-LGA commented
🤦