Afanasev nikita/task 02
Friend-LGA/msu_course_cpp_323_2022 pull request #55
Opened 2022-09-25 21:41 UTC by nikitanmlk

2022-10-02 08:50 UTC, Friend-LGA requested changes
1) Перемиенуй ПР аналогично остальным
2) Добавь метку

2022-10-02 10:49 UTC, nikitanmlk commented
> 1. Перемиенуй ПР аналогично остальным
> 2. Добавь метку

сделал

2022-10-10 11:11 UTC, Friend-LGA requested changes

2022-10-10 11:11 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +            vertex_presence_check(from_vertex_id)));
Хитрая запись какая-то, в целом можешь просто оставить без сообщения
```cpp
assert(vertex_presence_check(from_vertex_id));
```
Или, если очень хочется, можно так записать
```cpp
assert(vertex_presence_check(from_vertex_id)) && "vertex_presence_check failed");
```

2022-10-10 11:11 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +  bool vertex_presence_check(VertexId vertex_id) const {
Функции, которые выполняют определенную логику, чаще всего называют глаголом. Как будто ты задаешь вопрос объекту, например так "Граф, есть вершина?", а у тебя получается "Граф, проверка существования вершины".

Чтобы читалось более корректно лучше назвать так:
```cpp
bool check_vertex_presence(VertexId id) const;
```
Или ещё проще
```cpp
bool has_vertex(VertexId id) const;
```

2022-10-10 11:11 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +    for (auto next : edges_) {
Обходить все грани ради проверки только 2ух вершин - это очень неэффективно. Лучше будет хранить лист связности или что-нибудь подобное, чтобы можно было сразу взять все грани от вершины.
```cpp
unordered_map<VertexId, vector<EdgeId>> adjacency_list_;
```

2022-10-10 12:47 UTC, nikitanmlk commented on afanasev_nikita/prog.cpp
> +    return true;
просто не знаю оставить ли предыдущее представление std::vector vertices_, вдруг потом пригодиться

2022-10-10 12:50 UTC, nikitanmlk commented on afanasev_nikita/prog.cpp
> +    return true;
вместо has можно же проверить так: vertices_.find(id) != vertices_.end()

2022-10-10 12:54 UTC, nikitanmlk commented on afanasev_nikita/prog.cpp
> +    return true;
можно использовать обычный map? в таком случае find будет иметь complexity log n, а не n

2022-10-10 12:56 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +    return true;
Дублировать данные нельзя, поэтому либо вектор либо мап, мап выглядит в данной ситуации более эффективным

2022-10-10 13:19 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +    return true;
> можно использовать обычный map? в таком случае find будет иметь complexity log n, а не n
Сложность поиска должна быть константой, где ты такую информацию нашел?

2022-10-10 16:20 UTC, Friend-LGA requested changes

2022-10-10 16:20 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
>    }
```cpp
return vertices_.find(vertex_id) != vertices_.end();
```

2022-10-10 16:20 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +    }
Давай тоже использовать `assert` для проверки входных данных

2022-10-10 16:20 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
>      }
1) Примитивные данные передаются по значению, а не по ссылке
2) `i` и `j`, что это за названия? У тебя же не просто индекс итерации, а реальные данные, так нельзя их называть. В прошлый раз уже аналогичную ошибку обсуждали.
```suggestion
    for (auto from_edge_id : connected_from_edges_ids) {
      for (auto to_edge_id : connected_to_edges_ids) {
        if (from_edge_id == to_edge_id) {
          return true;
        }
      }
    }
```

2022-10-10 16:20 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +  std::map<VertexId, Vertex> vertices_;
Почему в итоге мап решил использовать для вершин, а для листа связности несортированный мап? Может проще везде использовать несортированный, раз нам не нужна сортировка?

2022-10-10 16:26 UTC, nikitanmlk commented on afanasev_nikita/prog.cpp
> +  std::map<VertexId, Vertex> vertices_;
потому что find работает для неотсортированного за n, когда как отсортированный за log n

2022-10-10 16:29 UTC, nikitanmlk commented on afanasev_nikita/prog.cpp
>    }
почему так? если has_vertex у меня отвчает на вопрос: "есть вершина с данным индексом?"

2022-10-10 16:32 UTC, nikitanmlk commented on afanasev_nikita/prog.cpp
> +    }
т.е. assert если выполнено условие в if? могу но не вижу смысла т.к. перед assert(!has_edge(from_vertex_id, to_vertex_id)); были проверены assert(has_vertex(from_vertex_id)); assert(has_vertex(to_vertex_id)); и данная проверка символическая, ее можно убрать

2022-10-10 16:35 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
>    }
При чем здесь это, просто ты написал много лишнего кода, видишь?
```cpp
if (condition) {
  return true;
}
return false;
```
эта запись аналогична данной:
```cpp
return condition;
```

2022-10-10 16:35 UTC, nikitanmlk commented on afanasev_nikita/prog.cpp
> +  std::map<VertexId, Vertex> vertices_;
ну я подумал ускорить поиск асимптотически, переделаю если так не надо было

2022-10-10 16:36 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +    }
Раз ты её добавил, то давай оставим, зачем ты её добавлял, если говоришь что она не нужна?)
Пиши меньше кода, будет меньше вопросов.

2022-10-10 16:37 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +  std::map<VertexId, Vertex> vertices_;
Ты мой комментарий читал к твоему прошлому вопросу?

2022-10-10 16:37 UTC, nikitanmlk commented on afanasev_nikita/prog.cpp
>      }
исправил

2022-10-10 16:39 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +  std::map<VertexId, Vertex> vertices_;
`map.find`: https://en.cppreference.com/w/cpp/container/map/find
`unordered_map.find`: https://en.cppreference.com/w/cpp/container/unordered_map/find

Документация говорит что усредненный поиск константный

2022-10-10 16:39 UTC, nikitanmlk commented on afanasev_nikita/prog.cpp
>    }
да, я понял, можно сократить код

2022-10-10 16:41 UTC, Friend-LGA requested changes

2022-10-10 16:41 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +    assert(!(adjacency_list_.find(from_vertex_id) == adjacency_list_.end() ||
Обсуждали уже что каждое условие должно быть в отдельном ассерте. Иначе теряется смысл. Ты должен с помощью ассерта быстро отловить ошибку, а если у тебя в ассерте проверяется несколько условий, то не будет очевидно, где именно случилась ошибка

2022-10-10 16:51 UTC, Friend-LGA approved these changes

2022-10-10 16:58 UTC, merged