tsybina_kovalenko/task_03
Friend-LGA/msu_course_cpp_323_2022 pull request #59
Opened 2022-10-03 18:51 UTC by klevvit

2022-10-04 20:45 UTC, Jedi314 commented
Добавь graph.json в ПР

2022-10-04 22:19 UTC, Jedi314 reviewed
Всё ок. Проблем не вижу.

2022-10-08 17:29 UTC, Jedi314 approved these changes

2022-10-09 06:52 UTC, Friend-LGA requested changes
Коваленко ещё не сдал вторую. Как сдаст - запросите ревью снова - тогда буду проверять.

2022-10-16 10:32 UTC, Friend-LGA requested changes

2022-10-16 10:32 UTC, Friend-LGA commented on tsybina_olga/graph_generation.cpp
> +  });
Вы для каждой вершины каждый раз будете обходить все грани? Это неэффективно. Лучше добавьте лист связности, чтобы можно было сразу забирать нужные грани:
```cpp
std::unordered_map<VertexId, std::vector<EdgeId>> adjacency_list_;
```

2022-10-16 10:32 UTC, Friend-LGA commented on tsybina_olga/graph_generation.cpp
> +                [&](const auto& vertex) {
Плохая практика захватывать в лямбду сразу все, лучше писать каждый захваченный аргумент индивидуально
https://github.com/Friend-LGA/uni_course_cpp/blob/master/practice/common_mistakes.md#lambda-capture-list

2022-10-16 12:31 UTC, klevvit commented on tsybina_olga/graph.json
> +{"vertices":[{"id":0,"edge_ids":[0,1,2]},{"id":1,"edge_ids":[0,3,4,5]},{"id":2,"edge_ids":[1,6,7]},{"id":3,"edge_ids":[2,8]},{"id":4,"edge_ids":[3,9]},{"id":5,"edge_ids":[4,10]},{"id":6,"edge_ids":[5
Что за красный знак?

2022-10-16 12:32 UTC, klevvit commented on tsybina_olga/graph_generation.cpp
> +  auto edges_end() const { return edges_.end(); }
Понял, справедливо)

2022-10-16 12:36 UTC, klevvit commented on tsybina_olga/graph_generation.cpp
> +  out.close();
Ага, привычка явно прописывать close, как только заканчиваешь работать с файлом

2022-10-21 11:43 UTC, klevvit commented on tsybina_olga/Makefile
> +TARGET = run
@Jedi314 тебе нужен clang-format? У меня всё на сочетания клавиш настроено, поэтому для меня прописывать его в makefile пользы-удобства особо не даст

2022-10-21 11:54 UTC, klevvit commented on tsybina_olga/graph.json
> +{"vertices":[{"id":0,"edge_ids":[0,1,2]},{"id":1,"edge_ids":[0,3,4,5]},{"id":2,"edge_ids":[1,6,7]},{"id":3,"edge_ids":[2,8]},{"id":4,"edge_ids":[3,9]},{"id":5,"edge_ids":[4,10]},{"id":6,"edge_ids":[5
пофикшено, добавил \n в конец вывода в файл

2022-10-21 12:10 UTC, klevvit commented on tsybina_olga/graph_generation.cpp
> +  auto edges_end() const { return edges_.end(); }
fixed

2022-10-21 12:12 UTC, klevvit commented on tsybina_olga/graph_generation.cpp
> +                [&](const auto& vertex) {
Повникал, почитал про for_each и понял, что он здесь неуместен, лучше заменить их на range-based for loops

2022-10-21 12:48 UTC, klevvit commented on tsybina_olga/graph_generation.cpp
> +  });
done

2022-10-23 11:33 UTC, Jedi314 commented on tsybina_olga/Makefile
> +TARGET = run
Мне не нужен

2022-10-23 11:34 UTC, Jedi314 approved these changes

2022-10-24 09:56 UTC, Friend-LGA requested changes

2022-10-24 09:56 UTC, Friend-LGA commented on tsybina_olga/graph_generation.cpp
> +    connections_[to_vertex_id].push_back(edge_id);
А если `from_vertex_id == to_vertex_id`?

2022-10-24 09:56 UTC, Friend-LGA commented on tsybina_olga/graph_generation.cpp
> +  for (const auto& edge_id : graph.connections().at(vertex.id())) {
примитивные данные передаются по значению, а не по ссылке

2022-10-25 00:13 UTC, klevvit commented on tsybina_olga/graph_generation.cpp
> +  for (const auto& edge_id : graph.connections().at(vertex.id())) {
справедливо

2022-10-25 00:13 UTC, klevvit commented on tsybina_olga/graph_generation.cpp
> +    connections_[to_vertex_id].push_back(edge_id);
справедливо

2022-10-25 08:58 UTC, Jedi314 approved these changes

2022-10-26 08:31 UTC, Jedi314 approved these changes

2022-10-29 13:59 UTC, Friend-LGA approved these changes
Исправьте и можете мерджить

2022-10-29 13:59 UTC, Friend-LGA commented on tsybina_olga/graph_generation.cpp
> +    VertexId new_vertex_id = get_new_vertex_id();
`const`

2022-10-29 13:59 UTC, Friend-LGA commented on tsybina_olga/graph_generation.cpp
> + private:
Опааа, вот это я проглядел))

2022-10-30 10:45 UTC, merged