matveev_burikova/task_04
Friend-LGA/msu_course_cpp_323_2022 pull request #64
Opened 2022-10-15 12:07 UTC by matvlaale

2022-10-22 07:46 UTC, Friend-LGA requested changes
1) Жду ревью и аппрува от второга участника вашей группы, после этого уже сам буду проверять.
2) Обновитесь на мастер, я там создал вашу папку `matveev_burikova`, и перенесите ваши изменения туда

2022-10-22 08:52 UTC, matvlaale commented
> 1. Жду ревью и аппрува от второга участника вашей группы, после этого уже сам буду проверять.
> 2. Обновитесь на мастер, я там создал вашу папку `matveev_burikova`, и перенесите ваши изменения туда

Мы делали ревью до коммита через другие сервисы. Надеемся, просто approve сейчас будет достаточно

2022-10-22 08:54 UTC, AnnaBurikova approved these changes

2022-10-23 08:47 UTC, AnnaBurikova approved these changes

2022-10-23 10:38 UTC, Friend-LGA requested changes

2022-10-23 10:38 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +    Vertex() {}
Пустых конструкторов быть не должно

2022-10-23 10:38 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +  void add_vertex(Depth depth) {
Глубина вершины не должна передаваться извне, а должна рассчитываться при создании новой грани.
Все вершины при создании попадают изначально на глубину 1, и при создании грани их глубина меняется. В задании об этом написано.

2022-10-23 10:38 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +    }
1) Вынесите определение цвета в отдельную функцию. Логику по возможности всегда нужно разбивать на небольшие функции.
2) Что-то вы тут намудрили, в задании полная логика была написана

2022-10-23 10:38 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +  VertexId get_last_vertex_id() const { return last_vertex_id_; }
Это внутренняя логика, она не должна быть публичной, это нарушает инкапсуляцию.

2022-10-23 10:38 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +  }
Аналогично, это внутренняя логика, только сам граф в ответе за то, на какой глубине находится вершина, извне не должно быть возможности изменять глубину вершины.

2022-10-23 10:38 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +  VertexId num_vertices_ = 0;
Зачем эта переменная? достаточно проверить `vertices_.size()`

2022-10-23 10:38 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +  EdgeId num_edges_ = 0;
Аналогично

2022-10-23 10:38 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +  VertexId last_vertex_id_ = -1;
Тоже ненужная переменная, при создании грани мы всегда знаем  к какой вершине мы присоединяем новую, поэтому лишние переменные не нужны

2022-10-23 10:38 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +        std::bernoulli_distribution d(1 - i * step);
Так как логика получения рандобного значения повторяется во всех методах генерации, имеет смысл эту логику вынести в отдельную свободную функцию, например
```cpp
bool check_probability(double probability);
```

2022-10-23 10:38 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +          graph.add_vertex_id_on_depth(i + 2, graph.get_last_vertex_id());
Эта логика должна выполняться внутри `add_edge`

2022-10-23 10:38 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +          std::rand() % vertex_ids_on_following_depth.size();
Про `std::rand` написано в задании, читайте внимательнее

2022-10-23 10:38 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +void GraphGenerator::generate_yellow_edges(Graph& graph) const {
Очень длинный метод. Что-то вы тут перемудрили. Упростите, или разбейте на несколько методов.

2022-10-23 10:38 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
>  std::string print_graph(const Graph& graph) {
Забыли глубину графа распечатать

2022-10-23 18:47 UTC, matvlaale commented on matveev_burikova/graph.cpp
> +  VertexId get_last_vertex_id() const { return last_vertex_id_; }
Нам нужна эта переменная для генерации серых вершин, поскольку нужно знать id последней сгенерированной вершины. Если стоит по-другому как-то получать этот id, напишите, пожалуйста

2022-10-23 18:49 UTC, AnnaBurikova approved these changes

2022-10-23 19:06 UTC, AnnaBurikova approved these changes

2022-10-24 10:46 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +  VertexId get_last_vertex_id() const { return last_vertex_id_; }
Его вообще не нужно получать извне, граф сам должен рассчитать глубину новой вершины, в зависимости от той, к которой она присоединена. Это его внутренняя логика, у него есть все данные, для этого не нужны публичные методы.

2022-10-24 11:01 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +  }
Эти методы, будучи отдельными могут привести к проблемам, так как у нас есть только 2 варианта логики:
1) Добавляется новая вершина на глубину 1
2) Обновляется глубина у вершины, при этом она удаляется со старой глубины и добавляется на новую глубину

Вся эта логика связана и не должна иметь разных интерфейсов

2022-10-24 11:02 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +  void remove_vertex_id_from_depth(Depth depth, VertexId vertex_id) {
Аналогично, лучше не создавать отдельную функцию, так как логика связана

2022-10-24 11:02 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +    auto iterator = find(vertices_on_depth_[depth].begin(),
const?

2022-10-24 11:04 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +    Graph::Depth with_depth) {
Усложнили, передали в метод слишком много ненужной информации
```suggestion
const std::vector<Graph::VertexId> get_unconnected_vertex_ids(
    Graph::VertexId id,
    const std::vector<Graph::VertexId>& ids_list) {
```

2022-10-24 11:04 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +const bool check_probability(const double probability) {
1) Аргументы, передающиеся по значению, не обозначаются `const`
2) Возвращаемое значение из функции вообще нельзя делать конст, если оно передается по значению, иначе можно поломать внешнюю логику

2022-10-24 11:04 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +const int get_random_number(const int minimum, const int maximum) {
аналогично

2022-10-24 11:06 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
>    for (Graph::Depth i = 0; i < depth; ++i)
Лучше испоьзовать более осмысленное название для индекса `i -> current_depth`

2022-10-24 11:07 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
>      for (const auto& from_vertex_id : vertex_ids_on_current_depth) {
Примитивные данные передаются по значению, а не по ссылку

2022-10-24 11:07 UTC, matvlaale commented on matveev_burikova/graph.cpp
> +  VertexId get_last_vertex_id() const { return last_vertex_id_; }
> Его вообще не нужно получать извне, граф сам должен рассчитать глубину новой вершины, в зависимости от той, к которой она присоединена. Это его внутренняя логика, у него есть все данные, для этого не нужны публичные методы.

Так мы не глубину передаём, а передаём, повторюсь, last vertex id. Id последней вершины. Никаких глубин, ничего больше

2022-10-24 11:09 UTC, matvlaale commented on matveev_burikova/graph.cpp
> +  VertexId get_last_vertex_id() const { return last_vertex_id_; }
> Его вообще не нужно получать извне, граф сам должен рассчитать глубину новой вершины, в зависимости от той, к которой она присоединена. Это его внутренняя логика, у него есть все данные, для этого не нужны публичные методы.

Ну, у нас логика создания грани такова, что нужны id двух вершин. При создании графа один id у нас есть, но второй id нам неизвестен, а он нужен, иначе мы не создадим грань. И мы получаем из графа только last vertex id, чтобы создать серые грани в генераторе

2022-10-24 11:11 UTC, matvlaale commented on matveev_burikova/graph.cpp
> +  VertexId get_last_vertex_id() const { return last_vertex_id_; }
> Его вообще не нужно получать извне, граф сам должен рассчитать глубину новой вершины, в зависимости от той, к которой она присоединена. Это его внутренняя логика, у него есть все данные, для этого не нужны публичные методы.

Повторюсь, мы не передаём глубину, к глубине нет доступа извне, мы передаём только и исключительно last vertex id (, id последней созданной вершины)

2022-10-24 11:11 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
>        }
Неверная логика, грань должна создаваться не с каждой из `unconnected` вершин, а при проверке вероятности она создается с одной из `unconnected` вершин.

А у вас вероятность проверяется для каждой и `unconnected`, значит у вас может быть создано больше одной желтой грани из данной вершины, а такого быть не должно.

2022-10-24 11:14 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
>          auto new_to_vertex_number =
const?

2022-10-24 11:14 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
>          auto to_vertex_id = not_connected_vertex_ids[new_to_vertex_number];
Аналогично

2022-10-24 11:14 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
>        auto to_vertex_id = vertex_ids_on_following_depth[new_to_vertex_number];
const?

2022-10-27 19:24 UTC, AnnaBurikova approved these changes

2022-10-29 23:12 UTC, Friend-LGA requested changes
1) При вводе неверных данных их нужно обрабатывать
![Снимок экрана 2022-10-30 020812](https://user-images.githubusercontent.com/5897136/198855774-e12f4922-2dde-4207-bc3d-720634b676c0.png)
2) Запрашиваю граф с глубиной 0, создается граф с глубиной 1. Если глубина 0, к тому же, вершин быть не должно.
![Снимок экрана 2022-10-30 021058](https://user-images.githubusercontent.com/5897136/198855803-39d4a48f-2fff-4e2b-b9be-3c797881861f.png)

2022-10-29 23:12 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
>            get_random_number(0, vertex_ids_on_following_depth.size() - 1);
Метод `get_random_number` везде используется только для получения `random_vertex_id`, следовательно логично будет сделать метод `get_random_vertex_id(list)`, вместо `get_random_number(start, end)`

2022-10-30 08:24 UTC, AnnaBurikova approved these changes

2022-10-31 08:16 UTC, Friend-LGA approved these changes
🎉

2022-10-31 08:19 UTC, merged