kuzminskiy_stafeev/task_04
Friend-LGA/msu_course_cpp_323_2022 pull request #69
Opened 2022-10-17 10:14 UTC by KuzmaLine

2022-10-22 08:21 UTC, Friend-LGA requested changes
1) `classes` - плохое название. Это как если вектор называть вектором, не несет в себе никакой полезной информации. Если хотите разбивать все на файлы, тогда уж все и разбивайте. 
- `graph.hpp|cpp`
- `graph_geenrator.hpp|cpp`
- ...

2) Если данные константные, не забывайте `const`

2022-10-22 08:21 UTC, Friend-LGA commented on kuzminskiy_stafeev/classes.hpp
> +  Depth max_depth_ = 0;
Почему именно `max`? У графа нет `max_depth` или `min_depth`, у него есть просто `depth`, которую вы можете получить из вашей карты глубин
```cpp
return vertices_of_depth_.size();
```

2022-10-22 08:21 UTC, Friend-LGA commented on kuzminskiy_stafeev/classes.cpp
> +  const auto& depth = params_.depth();
Примитивные данные передаются по значению, а не по ссылке

2022-10-22 08:21 UTC, Friend-LGA commented on kuzminskiy_stafeev/classes.cpp
> +        if (d(gen)) {
Вынесите логику по проверки вероятности в общую свободную внешнюю функцию, которую вы сможете везде использовать 
```suggestion
        if (check_probability(probability))
```
```cpp
bool check_probability(double probability);
```

2022-10-22 08:21 UTC, Friend-LGA commented on kuzminskiy_stafeev/classes.cpp
> +    for (auto from_vertex_id : vertices_on_cur_depth) {
Можем мы обойтись без лишних переменных?
```suggestion
for (auto from_vertex_id : graph.get_vertex_ids_at(current_depth)) {
```

2022-10-22 08:21 UTC, Friend-LGA commented on kuzminskiy_stafeev/classes.cpp
> +  for (Graph::Depth i = 1; i <= depth; i++) {
Тут скорее не просто перечисление по индексу, а обход глубин, будет лучше дать больше информации и назвать переменную например `current_depth`

2022-10-22 08:21 UTC, Friend-LGA commented on kuzminskiy_stafeev/classes.cpp
> +    vertices_on_cur_depth = vertices_on_next_depth;
Без обоих переменных можно обойтись

2022-10-22 08:21 UTC, Friend-LGA commented on kuzminskiy_stafeev/classes.cpp
> +        auto to_vertex_id = next_vertices_depth[rand_pos];
Немного неверно, логика такая:
1) находите все `unconnected_vetrex_ids` на следующей глубине
2) Выбираете из них одну рандомную.

А не наоборот.

P.S. вынесите логику по поиску `unconnected_vertex_id` в отдельную свободную функцию

2022-10-22 08:21 UTC, Friend-LGA commented on kuzminskiy_stafeev/classes.cpp
> +        auto rand_pos = std::rand() % next_vertices_depth.size();
Слишком Сишно. Используйте `std::uniform_int_distribution`

2022-10-22 14:34 UTC, Jecteroid approved these changes

2022-10-23 09:29 UTC, Friend-LGA requested changes
Ещё проверьте `naming_convention`, у вас что-то тут полный бардак.

2022-10-23 09:29 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.hpp
> +  void set_vertex_depth(const VertexId id, const Depth depth);
Если аргумент передается по значению, то `const` не указывается

2022-10-23 09:29 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.hpp
>  #include <unordered_map>
Должны быть перечислены только те библиотеки, которые используются именно в этом файле.

2022-10-23 09:29 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.cpp
> +  vertices_.insert(std::make_pair(vertex_id, vertex));
1) Я не пойму, что за ненужные изменения относительно старого кода? Там было написано по-другому. Изменения в ПР должны непосредственно относиться к реализации новой логики, никаких ненужных изменений быть не должно.
2) `vertex` не может быть ссылкой на временные данные
3) В переменной `vertex` нет необходимости.

2022-10-23 09:29 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.cpp
> +                     const VertexId& to_vertex_id) {
Почему вдруг
```cpp
void add_edge(VertexId from_vertex_id, VertexId to_vertex_id)
```
превратилось в
```cpp
void Graph::add_edge(const VertexId& from_vertex_id,
                     const VertexId& to_vertex_id) {
```

Если что, я про аргументы функции.

Что-то вы намудрили, это невозможно ревьюить, миллион ненужных изменений.

Вот что мы с вами сделаем:
1) Объедините все файлы обратно в `gen_graph.cpp`
2) Порядок кода сделайте как было раньше в `gen_graph.cpp`
3) Весь новый код соответственно добавьте в конец файла.

Вы меня порадовали, когда решили разбить все на отдельные файлы, но внесли кучу ненужны и ошибочных изменений, которые невозможно ревьюить теперь. Так что эта задача пусть останется одним файлом, а вот в 5ой задаче как раз будет необходимо все разбить на файлы, там и разобьете тогда.

Плохо что Стафеев зааппрувил код, пропустив все эти ошибки. Нужно лучше проверять, чтобы не терять потом время.

2022-10-23 12:59 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph.cpp
> +                     const VertexId& to_vertex_id) {
Вы предлагаете мне переписывать всё часа 2 минимум, делая файл строк на 500, когда это не требуется, потому что вам тяжело проверить программу, разбитую на отдельные файлы? Я не понимаю, вашей проблемы и переписывать я так не буду, я лучше разобью её уже согласно 5 задаче. Или вам документацию и комментарии написать?

2022-10-23 13:04 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph.hpp
> +  void set_vertex_depth(const VertexId id, const Depth depth);
Почему?

2022-10-23 13:12 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph.cpp
> +  vertices_.insert(std::make_pair(vertex_id, vertex));
Да, там было написано по другому, но вы попросили меня избавиться от max_depth_, это повлекло изменение почти всего кода, потому что эта переменная была безумна важна.

2022-10-23 18:52 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph.cpp
> +                     const VertexId& to_vertex_id) {
И я вернул кучу "ненужных и ошибочных изменений"

2022-10-24 10:00 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.hpp
> +  void set_vertex_depth(const VertexId id, const Depth depth);
Согласен, на мой взгляд тоже было бы логично делать их конст. Так принято в cpp сообществе, я ссылки оставлял на гайдлайны, можете почитать, если интересно:
https://github.com/Friend-LGA/uni_course_cpp#guidlines-coding-standards-naming-conventions

Вообще идея в том, что `const` в интерфейсе функции не добавляет дополнительной полезной информации, если аргумент передается по значению, а следовательно нужды в нем нет. Если же передается по ссылке, то напротив, если конст есть, значит ссылка не изменяется, а если конст отсутсвует, значит это `in-out` аргумент.

2022-10-24 10:03 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.cpp
> +                     const VertexId& to_vertex_id) {
2 часа? Там делов минут на 10. Нужно быть шустрее. А то что "требуется" определяю я. 
Хорошо, если действительно все подобные изменения исправили, то можете не разбивать.

2022-10-24 10:04 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph.hpp
> +  void set_vertex_depth(const VertexId id, const Depth depth);
В любом случае, я это везде исправил.

2022-10-24 10:41 UTC, Friend-LGA requested changes
1) Программа должна взаимодействовать с пользователем, если что-то запрашивайте - нужно сообщить что ожидается, например "Введите ожидаемую глубину графа" или что-то подобное
    <img width="911" alt="Screenshot 2022-10-24 at 16 34 31" src="https://user-images.githubusercontent.com/5897136/197507713-2dc397e0-4a83-451d-a3ce-3deb6625b523.png">
2) При неверном вводе должно выводиться сообщение с ошибкой и повторный запрос данных, а у вас что-то выполняется
    <img width="1250" alt="Screenshot 2022-10-24 at 16 34 59" src="https://user-images.githubusercontent.com/5897136/197507764-d72fc5b4-84e7-4135-bcbd-7c559aa2a321.png">
3) При запрашиваемой нулевой глубине генерируется граф с глубиной 1
    <img width="794" alt="Screenshot 2022-10-24 at 16 35 40" src="https://user-images.githubusercontent.com/5897136/197507940-139957a8-4d8c-4009-9689-e8792adbf0e8.png">

2022-10-24 10:41 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +int random(int a, int b) {
Назовите переменные более выразительно

2022-10-24 10:41 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +                                              cur_depth + 1);
Слишком много логики переложили на функцию `unconnected_vertices_ids_on_depth`, видите, у неё даже название получилось излишне сложным.
Можно упростить, например так:
```suggestion
        const auto& unconnected_vertex_ids =
            get_unconnected_vertex_ids(from_vertex_id, graph.vertices_of_depth(cur_depth + 1));
```
```cpp
std::vector<VertexId> get_unconnected_vertex_ids(VertexId id, std::vector<VertexId> ids_list) { ... }
```

2022-10-24 10:41 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +          const auto to_vertex_id = unconnected_vertices_ids[rand_pos];
А тут наоборот, у вас функция `random()` как таковая нигде не используется сама по себе, везде только чтобы получить в итоге `vertex_id`, в таком случае, вам нужна не функция получения простого рандомного числа, а функция, которая возвращает рандомный `vertex_id`
```suggestion
          const auto to_vertex_id = get_random_vertex_id(unconnected_vertices_ids);
```

2022-10-24 10:41 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.cpp
> +  }
Длинная функцию. Когда есть возможность сложную логику разбить на более маленькие кусочки просто логики, всегда нужно разбивать.
Вынесите логику определения цвета в отдельную вспомогательную функцию.

2022-10-24 10:41 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.cpp
> +  Graph::Depth base_depth = 0;
`base_depth` всегда 1, нет смысла её менять.
Все новые вершины попадают на глубину 1

2022-10-24 10:41 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.cpp
> +    }
Глубина не может отличаться больше чем на 1, верно? Тогда зачем нам тут цикл? Если разница больше чем 1, то это скорее баг, который стоило бы отловить.

2022-10-24 10:41 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.cpp
> +bool Graph::is_connected(Graph::VertexId from_vertex_id,
Выглядит так, что данная функция не будет правильно работать для зеленых граней (та, которая имеет связь сама к себе), в этом случае всегда будет пересечение, так как сеты будут одинаковыми.

2022-10-24 10:41 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.hpp
> +  }
В интерфейса принято записывать только однострочные функции. Все что более сложное должно быть в `cpp`

2022-10-24 10:41 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.hpp
> +#include <cassert>
ассертов не должно быть в `hpp`

2022-10-24 11:09 UTC, Friend-LGA commented
И проверьте весь свой код на соответствие `naming_convention`, у вас есть ошибки

2022-10-29 22:55 UTC, Friend-LGA requested changes
> И проверьте весь свой код на соответствие `naming_convention`, у вас есть ошибки

> И проверьте весь свой код на соответствие `naming_convention`, у вас есть ошибки

> И проверьте весь свой код на соответствие `naming_convention`, у вас есть ошибки

> И проверьте весь свой код на соответствие `naming_convention`, у вас есть ошибки

> И проверьте весь свой код на соответствие `naming_convention`, у вас есть ошибки

Ни одну их ошибок наименования не исправили, хотя я каждый раз об этом пишу.

2022-10-29 22:55 UTC, Friend-LGA commented on kuzminskiy_stafeev/main.cpp
> +  }
Лучше чтобы `handle_depth_input` и `handle_new_vertices_count_input` сами отлавливали свои ошибки, а не перекладывать эту ответственность на `main`

2022-10-29 22:55 UTC, Friend-LGA commented on kuzminskiy_stafeev/main.cpp
>    return input;
`return`  после `throw` не имеет смысла, выполнение до него не дойдет

2022-10-29 22:55 UTC, Friend-LGA commented on kuzminskiy_stafeev/main.cpp
>    return input;
аналогично

2022-10-29 22:55 UTC, Friend-LGA commented on kuzminskiy_stafeev/main.cpp
> +#include <exception>
`stdexcept` не достаточно?

2022-10-29 22:55 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.cpp
> +}
Используются только переданные в функцию аргументы, следовательно это свободная функция, нет никакого резона для неё принадлежать графу, никаких внутренних данных графа тут не используется. `is_connected` можно просто вызвать на графе `graph.is_connected`. До этого она была записана в правильном месте, зря перенесли.

2022-10-29 22:55 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +        const auto& unconnected_vertices_ids = graph.get_unconnected_vertex_ids(
Ссылку на временные данные делать нельзя, нужно передавать по значению.

2022-10-29 22:55 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.hpp
> +  Edge::Color define_color(VertexId from_vertex_id, VertexId to_vertex_id);
метод константный

2022-10-29 22:55 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.cpp
> +    set_vertex_depth(to_vertex_id, from_vertex_depth + 1);
Метод `define_color` должен **только** определять цвет, он не должен вызывать никакую дополнительную логику, это нарушение зоны ответственности и неожиданное поведение.

2022-10-29 22:55 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.cpp
> +  Graph::Depth base_depth = 1;
1) константа
2) Все что не является дефолтным значением, является так называемым "магическим числом" (`magic number`), все такие числа должны быть вынесены в глобальные константы

2022-10-30 11:27 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph.cpp
> +}
Не согласен, т.к. is_connected берёт информацию обо всех рёбрах, связанных с графом, из-за чего мне придётся передавать в аргументы ещё и const Graph& graph и возникает тогда вопрос, как лучше писать
graph.get_unconnected_vertex_ids(vertex_id, vertex_ids_on_depth)
или
get_unconnected_vertex_ids(graph, vertex_id, vertex_ids_on_depth)

2022-10-30 13:15 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph.cpp
> +}
Прошу прощения, не до конца дочитал, исправил

2022-10-31 08:30 UTC, Friend-LGA requested changes
1) При вводе неверного значение, не нужно валить программу, нужно сообщить об этом пользователю и запросить данные заново. Другими словами, поведение программы должно быть одинаковым при вводе `-10` и `qwer`
![Screenshot 2022-10-31 at 11 27 18](https://user-images.githubusercontent.com/5897136/198964957-57cdf50c-0d70-4ba0-a30f-49e2e1978033.png)
2) У вас программа не работает
![Screenshot 2022-10-31 at 11 28 25](https://user-images.githubusercontent.com/5897136/198965011-7399a9b2-ecae-40fd-93a4-83c7d85a9f77.png)

2022-10-31 08:30 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.cpp
> +const Graph::Depth kBaseDepth = 1;
[const-vs-constexpr](https://github.com/Friend-LGA/uni_course_cpp/blob/master/practice/common_mistakes.md#const-vs-constexpr)

2022-10-31 08:30 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.cpp
> +  const auto pull_edges_to = connections_list_.at(to_vertex_id);
Чем передавать данные по значению и делать копию, лучше передавать данные по ссылке

2022-10-31 08:30 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.cpp
> +  auto edge_color = define_color(from_vertex_id, to_vertex_id);
Меняется?

2022-10-31 09:35 UTC, Friend-LGA requested changes
Работает через раз
![Screenshot 2022-10-31 at 12 35 22](https://user-images.githubusercontent.com/5897136/198977390-0031fdaa-bbb6-4b1f-8bd6-3e740dd7e10b.png)

2022-11-01 19:04 UTC, Friend-LGA approved these changes

2022-11-01 19:04 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +       cur_depth++) {
Считается плохой практикой использовать не стандартную запись `for`, или, другими словами, усложнять её. Лучше было доп. условие уже внутри `for` проверить.
Типа
```cpp
for () {
  if (is_created) break;
}
```

2022-11-01 19:11 UTC, merged