krymskiy_sviatoslav/task_02
Friend-LGA/msu_course_cpp_323_2022 pull request #76
Opened 2022-10-21 12:09 UTC by ludmik

2022-10-22 06:44 UTC, Friend-LGA requested changes
Запроси ревью, после того как первая задача будет принята

2022-10-23 09:13 UTC, Friend-LGA requested changes
1) Добавь метку с номером задачи к ПР
2) После того как замерджил первую задачу нужно обновить свой код на свежий мастер, в `workflow`(https://github.com/Friend-LGA/uni_course_cpp/blob/master/practice/workflow.md) есть инструкция
3) Бинарников в ПР быть не должно
4) Линтер не прошел проверку
5) Лишних изменений быть не должно

2022-10-24 09:39 UTC, Friend-LGA requested changes

2022-10-24 09:39 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.hpp
> +#define GRAPH_GENERATOR_HPP
Используй просто `#pragma once`

2022-10-24 09:39 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.hpp
> +  struct Edge;
Нет смысла прятать интерфейс публичных структур в `cpp`, запиши их интерфейс прямо здесь

2022-10-24 09:39 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.hpp
> +  std::vector<Edge> graphEdges;
Читай [`naming_convention`](https://github.com/Friend-LGA/uni_course_cpp/blob/master/practice/naming_convention.md)

2022-10-24 09:39 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.hpp
> +  const std::vector<Graph::Edge>& get_edges() const;
Не используются

2022-10-24 09:39 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.cpp
> +}
Видишь красный знак? Он означает что в конце файла не хватает символа новой строки. Все текстовые файлы должны заканчиваться на символ новой строки.

2022-10-24 09:39 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.cpp
> +  int kVerticesCount = 14;
Это скорее не переменная, а глобальная константа, так как её значение приходить из описания задачи. Вынеси её в глобальную область и сделай константой.
Читай [`const vs constexpr`](https://github.com/Friend-LGA/uni_course_cpp/blob/master/practice/common_mistakes.md#const-vs-constexpr)
Да и вообще `common_mistakes` почитай весь файл.

2022-10-24 09:39 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.cpp
> +  Vertex(VertexId id) : id_(id) {}
Как в задаче было написано?
[`читай`](https://github.com/Friend-LGA/uni_course_cpp/blob/master/practice/common_mistakes.md#explicit-keyword)

2022-10-24 09:39 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.cpp
> +  graphVertices.push_back(vertex);
1) Нет прямой связи между размером коллекции и `id` вершины. У них даже тип данных разный. Есть только косвенная связь, на которую лучше не полагаться, так как это может сыграть злую шутку.

Добавь член класса в граф, который будет хранить текущий `id` и приватный метод, который будет возвращать новый `id`, таким образом мы инкапсулируем данную логику.
```cpp
VertexId get_new_vetrex_id() const; 
```

2) Все константные данные должны быть помечены как `const`. Кроме аргументов функций и возвращаемых значений функций.

3) Не создавай лишних переменных, если в них нет необходимости.

2022-10-24 09:39 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.cpp
> +  if (from_vertex_id >= verticesAmount || to_vertex_id >= verticesAmount) {
Если хочешь добавить проверку, то:
1) Лучше использовать `assert`, так как эти проверки в первую очередь должны помочь отловить баги, которых в продакшене быть не должно, а следовательно мы не хотим добавлять нагрузку в продакшене. `assert` как раз и созданы для того чтобы работать только в дебаг билдах, а в продакшене они отключаются и не выполняются. `#include <cassert>`
2) Для каждого условия должна быть отдельная проверка.
3) Лучше вынести эту логику в удобный интерфейс проверки
```cpp
bool has_vertex(VetrexId id) const;
```
```cpp
assert(has_vertex(from_vertex_id));
```

2022-10-29 13:55 UTC, Friend-LGA requested changes

2022-10-29 13:55 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.hpp
> +  bool valid_vertex(VertexId id) const;
1) `valid` - слишком абстрактное понятие, то что ты добавляешь в методы класса, является его интерфейсом, нужно понимать что именно делает каждый конкретный метод. 
2) `valid vertex` переводится как "правильная вершина". Это звучит криво, то есть в коде ты пишешь "граф.валидная_вершина(5)", это звучит как утверждение, а должно звучать как вопрос, например "граф.валидна_ли_вершина(5)", поэтому и метод должен называться соответственно: `is_vertex_valid()`, а учитывая предыдущее замечание, будет лучше что-нибудь типа `has_vertex`

2022-10-29 13:55 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.hpp
> +  VertexId get_new_vertex_id() const;
Этот интерфейс не может быть публичным, он реализует внутреннюю логику графа, если открыть к ней доступ извне графа, то внешний пользователь сможет поломать внутреннюю структуру графа.

2022-10-29 13:55 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.hpp
> +  void update_current_vertex_id();
`id` не должен обновляться никогда, он задается единственный раз при создании и навсегда остаётся таковым. в этом смысл поля `id`

И уж тем более, эта логика не должна быть публичной.

2022-10-29 13:55 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.hpp
> +  int current_vertex_id_ = 0;
У нас есть специальный псевдоним для данного типа данных

2022-10-29 13:55 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.hpp
> +  std::vector<Edge> graph_edges_;
Эти переменные итак принадлежат графу, они являются членами класса "Граф", зачем в названии указывать это дополнительно? Это лишняя ненужная информация, которая усложняет чтение и написание.

2022-10-29 13:55 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.cpp
> +  const auto graph = generate_graph();
Зачем нам переменная, которую мы не используем?

2022-10-29 13:55 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.cpp
> +  update_current_vertex_id();
Смысл  вынести логику по генерации нового `id` в отдельную функцию в том, чтобы гарантировать её надежность и безопасность. Разбивать эту логику на 2 части `get_new_vertex_id + update_current_vertex_id` нивелирует наши благие начинания. Если ты разделяешь "неразделяемую" логику на 2 части, то усложняешь себе жизнь и увеличиваешь вероятность потенциальных ошибок, если кто-то забудет вызвать одну из двух функций

2022-10-29 13:55 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.cpp
> +  graph_vertices_.push_back(vertex);
[Читай](https://github.com/Friend-LGA/uni_course_cpp/blob/master/practice/common_mistakes.md#push-vs-emplace)
Я тебе в прошлый раз советовал прочитать этот файл, повторяю.

2022-10-29 13:55 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.cpp
> +  Edge edge(graph_size, from_vertex_id, to_vertex_id);
Я для кого комментарий в прошлый раз писал?
> 1) Нет прямой связи между размером коллекции и `id` вершины. У них даже тип данных разный. Есть только косвенная связь, на которую лучше не полагаться, так как это может сыграть злую шутку.

2022-10-29 13:55 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.cpp
> +  return id < vertices_amount;
Опять же
> 1) Нет прямой связи между размером коллекции и `id` вершины. У них даже тип данных разный. Есть только косвенная связь, на которую лучше не полагаться, так как это может сыграть злую шутку.

Тебе нужно проверить, реально ли в векторе есть вершина с данным `id`

2022-10-29 13:55 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.cpp
> +  return current_vertex_id_;
Чтобы вернуть данные и увеличить счетчик одним действием - можно сделать так
```suggestion
  return current_vertex_id_++;
```

2022-10-29 13:55 UTC, Friend-LGA commented on krymskiy_sviatoslav/graph_generator.cpp
> +#include <iostream>
Используется?

2022-10-29 14:03 UTC, ludmik commented on krymskiy_sviatoslav/graph_generator.hpp
> +  bool valid_vertex(VertexId id) const;
Понял, спасибо.

2022-10-29 14:06 UTC, ludmik commented on krymskiy_sviatoslav/graph_generator.hpp
> +  VertexId get_new_vertex_id() const;
Как я понял, Вы имеете в виду только последние два метода. Ведь первые два нужны, чтобы в функции main добавить ребра с вершинами, они должны быть публичными.

2022-10-29 14:17 UTC, ludmik commented on krymskiy_sviatoslav/graph_generator.cpp
> +  update_current_vertex_id();
Понял.

2022-10-31 06:53 UTC, Friend-LGA approved these changes

2022-10-31 06:56 UTC, merged