kucherov_sergeev/task_04
Friend-LGA/msu_course_cpp_323_2022 pull request #79
Opened 2022-10-22 16:08 UTC by BasilKucherov

2022-10-22 17:26 UTC, fedyasa approved these changes

2022-10-23 10:19 UTC, Friend-LGA requested changes

2022-10-23 10:19 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  std::unordered_map<Depth, std::vector<VertexId>> depth_vertices_list_;
Глубина увеличивается от 0 и вверх. Зачем использовать `unordered_map`? Более эффективно будет использовать обычный `vector`
```suggestion
  std::vector<std::vector<VertexId>> depth_vertices_list_;
```

2022-10-23 10:19 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  EdgeId add_edge(const VertexId from_vertex_id, const VertexId to_vertex_id) {
Откуда здесь взялись константы? Раньше было правильно без них, зачем добавили?

2022-10-23 10:19 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  }
1) Чем миллион раз вызывать `adjacency_list_.find(first_vertex_id)`, вынесите их в переменные.
2) Для зеленых граней будет работать? Что-то непохоже. Например `is_vertices_connected(0, 0)` будет всегда возвращать `true`, так как список граней будет одинаковым.

2022-10-23 10:19 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +                             const VertexId second_vertex_id) const {
Аналогично

2022-10-23 10:19 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  Depth get_vertex_depth(const VertexId vertex_id) const {
Аналогично

2022-10-23 10:19 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +                                   const VertexId to_vertex_id) const {
Аналогично....

2022-10-23 10:19 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  void set_vertex_depth(const VertexId vertex_id, const Depth depth) {
...

2022-10-23 10:19 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  const float red_edge_probability_ = 0.33;
Опять же, они должны быть просто глобальными константами. Нет смысла усложнять класс лишними переменными.

2022-10-23 10:19 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +      const auto& next_depth_vertex_ids =
Переменная не используется...

2022-10-23 10:19 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +          }
Вынесите в отдельную свободную функцию функцию `get_unconnected_vertex_ids`

2022-10-23 10:19 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +                to_vertex_ids[get_random_int(0, to_vertex_ids.size() - 1)];
У вас нигде не используется `get_random_int` сама по себе, везде чтобы получить `id`, тогда проще будет изменить `get_random_int` на `get_random_vertex_id(list)`

2022-10-23 10:19 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +std::string print_edge_color(const Graph::Edge::Color& color) {
Я в задании ошибся. `enum class` тоже считается примитивным типом, и лучше его передавать по значению.

2022-10-23 10:36 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +      return "\"invalid color\"";
Почему тут двойные кавычки, этот метод просто переводить `Edge::Color` в строку, зачем в этой строке ещё и кавычки? Что-то вне зоны ответственности данного метода.

2022-10-23 10:40 UTC, Friend-LGA reviewed
Программа падает 
<img width="1280" alt="Screenshot 2022-10-23 at 16 39 53" src="https://user-images.githubusercontent.com/5897136/197387506-c825cf66-c5d1-42e1-9a59-57ee8dd8ea70.png">

2022-10-23 19:50 UTC, BasilKucherov commented on kucherov_sergeev/graph_generator.cpp
> +  const Depth default_vertex_depth_ = 1;
Не до конца понимаю как это сделать: если поместить в таком виде глобальную переменную над классом `Graph`, то будет ошибка, что `Graph` не определен. Если ставить после, то будет ругаться `set_vertex_depth` в `add_vertex`, так как она использует эту константу.

2022-10-30 16:56 UTC, BasilKucherov commented on kucherov_sergeev/graph_generator.cpp
> +  const Depth default_vertex_depth_ = 1;
Решили, разместив эту константу до реализации функций, но после определения класса. Но если было альтернативное решение, то хотелось бы узнать какое.

2022-10-30 19:41 UTC, fedyasa approved these changes

2022-10-31 08:43 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  const Depth default_vertex_depth_ = 1;
Да, все верно. Сначала идет интерфейс, который описывает все что будет использоваться, а потом реализация, где уже используются все описанные данные. Так что вы верно сделали, добавили константу после интерфейса и перед реализацией. В реальном мире это все ещё должно быть разделено на `hpp` и `cpp`, в таком случае у вас не возникло бы подобной проблемы. В следующей задаче мы как раз и будем это разбирать.

2022-10-31 09:30 UTC, Friend-LGA requested changes
1) При запросе графа с глубиной 0, создается граф с глубиной 1. При 0ой глубине вершин быть не должно.
![Screenshot 2022-10-31 at 12 29 03](https://user-images.githubusercontent.com/5897136/198976351-0273b282-64c6-4069-80bc-37d046013363.png)

2022-10-31 09:30 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +         first_vertex_id) == second_vertex_id) {
Что-то вы тут перемудрили. А если `second_vertex_id == 0`, то ваша логика работать не будет?
Давайте без булевой алгебры.

2022-10-31 09:30 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +Graph::VertexId get_random_vertex_id(std::vector<Graph::VertexId> vertex_ids) {
вектор лучше передавать по ссылке, а не по значению

2022-10-31 09:30 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  }
Лучше `assert`

2022-10-31 09:30 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +std::string print_edge_color(const Graph::Edge::Color color) {
аргументы, передаваемые по значению записываются без конст

2022-10-31 18:17 UTC, BasilKucherov commented on kucherov_sergeev/graph_generator.cpp
> +  }
Переделал, но хотелось бы узнать когда что следует использовать `assert` или `throw std::runtime_error`?

2022-10-31 19:13 UTC, fedyasa approved these changes

2022-11-01 18:26 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  }
Исключение ты выкидываешь, когда хочешь прям уронить программу. В продакшене программа, по факту, вообще должна работать всегда. Можно, конечно, повсюду использовать `try - catch`, но это сильно загрязняет код и немного ухудшает производительность. Ассерты нужно использовать тогда, когда вы хотите проверить свой собственный код на наличие ошибок, чтобы они помогли, в случае чего, быстро найти и устранить баг, а в продакшене они удаляются и не влияют на финальный код. `throw` имеет смысл использовать, если вы пишете библиотеку, которая планируется к использованию большим количеством людей, и вы не знаете точного применения для вашего кода в их проектах, ну типа open source. Ещё его можно использовать там, где требуется `return`, но он не возможен, например в нашем коде по определению цвета грани `determine_edge_color()`.

2022-11-01 18:33 UTC, Friend-LGA approved these changes

2022-11-01 18:38 UTC, merged