zhang_xinyu/task_01
Friend-LGA/msu_course_cpp_323_2022 pull request #8
Opened 2022-09-06 15:44 UTC by YamyuCheung

2022-09-11 11:57 UTC, Friend-LGA requested changes
Проверка на линтер не прошла

2022-09-17 18:38 UTC, Friend-LGA requested changes
1) Все изменения должны относиться только к твоей задаче. Видишь, ты удалил много файлов других студентов? Этого делать не нужно, в твоем ПР (пулл реквесте) должны быть только добавленные тобой файлы.
2) Старая версия `clang++`, должна быть выше `>= 14.0.0`
3) Старая версия `g++`, должна быть выше `>= 12.0.0`

2022-09-18 14:14 UTC, YamyuCheung commented
Проблема с программным обеспечением решена

2022-10-09 06:20 UTC, Friend-LGA requested changes
Проблема осталась, повторяю:
> Все изменения должны относиться только к твоей задаче. Видишь, ты удалил много файлов других студентов? Этого делать не нужно, в твоем ПР (пулл реквесте) должны быть только добавленные тобой файлы.

2022-10-16 08:49 UTC, Friend-LGA approved these changes

2022-10-16 08:52 UTC, Friend-LGA commented
1) Когда вносишь изменения в репозиторий - запрашивай ревью. В секции `Reviewers` справа сверху есть кнопка `re-request review`.
2) Я отправил тебе приглашение стать `collaborator`, прими его, после этого у тебя появится возможность на этой странице нажать кнопку `Merge pull request`, это значит что твои изменения попадут в мастер.

2022-10-16 09:02 UTC, merged