fedotov_chuvashov/task_04
Friend-LGA/msu_course_cpp_323_2022 pull request #80
Opened 2022-10-23 11:38 UTC by Huszar0

2022-10-23 18:27 UTC, wowonline requested changes

2022-10-23 18:27 UTC, wowonline commented on fedotov_chuvashov/graph_generator.cpp
> +}
newline

2022-10-23 18:27 UTC, wowonline commented on fedotov_chuvashov/graph_generator.hpp
> +};
newline

2022-10-23 18:27 UTC, wowonline commented on fedotov_chuvashov/main.cpp
> +}
newline

2022-10-29 22:29 UTC, Friend-LGA requested changes
1) При запуске программы она ожидает ввод данных от пользователя, только вот пользователь не в курсе, что от него ждут, было бы здорово узнать, что нужно вводить
![Снимок экрана 2022-10-30 011737](https://user-images.githubusercontent.com/5897136/198854403-eaae0724-bc01-4400-ac51-b622da008bfa.png)
2) Программа падает при вводе данных, а должна обработать ошибку, сообщить пользователю что данные введены не верно, и запросить их заново.
![Снимок экрана 2022-10-30 011850](https://user-images.githubusercontent.com/5897136/198854444-127ad920-00ab-4a75-8872-a79b0b05a6b5.png)
3) При графе с нулевой глубиной, ожидается что в нем нет вершин, если вершина попадает в граф, то она попадает на первую глубину.
![Снимок экрана 2022-10-30 012050](https://user-images.githubusercontent.com/5897136/198854677-2e434174-340f-4d4d-8495-9b29ee07ed63.png)
4) При задании глубины 1, ожидается что будет только рутовая вершина
![Снимок экрана 2022-10-30 012739](https://user-images.githubusercontent.com/5897136/198854690-712b1ce3-6569-4f58-b879-c6f1a640c4b0.png)

2022-10-29 22:29 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +      if (current_depth + 2 <= graph.depth()) {
1) А не проще ли будет обходить карту глубин, которая у вас `vertices_at_depth`, в таком случае не придется обходить лишние вершины на последних глубинах и можно будет избежать лишней проверки
2) `magic number`

2022-10-29 22:29 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +      1.0 - graph.get_vertex_depth(root_id) / (depth - 1.0);
Все, что не является дефолтным значением, которое обычно `0`, является так называемым магическим числом (`magic number`), которое должно быть вынесено в глобальную константу `constexpr`, чтобы код был более выразительным и понятным. Например тут переменную можно назвать
```cpp
kGreyDepthDifference
```

2022-10-29 22:29 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +  if (depth <= 1) {
magic number

2022-10-29 22:29 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +void generate_yellow_edges(Graph& graph) {
1) Аналогично, будет проще обходить карту глубин
2) Избавьтесь от `magic number`
3) Любую логику, которую можно вынести в отдельную функцию, нужно выносить. Поэтому вынесите логику по получению `unconnected_vertex_ids`

2022-10-29 22:29 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +      Graph::Depth current_depth = graph.get_vertex_depth(vertex_id);
const

2022-10-29 22:29 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +          Graph::VertexId random_vertex_pos =
const

2022-10-29 22:29 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +              get_random_number_between(0, not_connected_vertices.size() - 1);
1) const
2) Метод `get_random_number_between` везде используется только для получения `random_vertex_id`, следовательно логично будет сделать метод `get_random_vertex_id(list)`, вместо `get_random_number_between(start, end)`

2022-11-01 18:59 UTC, Friend-LGA requested changes

2022-11-01 18:59 UTC, Friend-LGA commented on fedotov_chuvashov/graph.cpp
> +                             Graph::Depth old_depth) {
Зачем тут `old_depth`? Усложняете интерфейс метода, когда метод сам может легко узнать эту информацию с помощью `get_vertex_depth(vertex_id)`

Вы даже сам дальше запутались и используете одновременно `old_depth` и `get_vertex_depth()`
> ```cpp
> if (old_depth > 0) {
>   vertices_at_depth_[get_vertex_depth(vertex_id)].erase(vertex_id);
> }
>```

2022-11-01 18:59 UTC, Friend-LGA commented on fedotov_chuvashov/graph.cpp
> +constexpr int kRedDepthDifference = 2;
У нас есть псевдонимы для этих типов данных `Depth`

2022-11-01 18:59 UTC, Friend-LGA commented on fedotov_chuvashov/graph.hpp
> +    const Edge::Color color_ = Color::Grey;
Зачем добавили конст? А остальные приватные члены что, изменяются? В чем между ними разница?

2022-11-01 18:59 UTC, Friend-LGA commented on fedotov_chuvashov/graph.hpp
> +                              adjacency_list_.at(vertex_id).end());
1) Зачем 2 раза запрашиваете `adjacency_list_.at(vertex_id)`. Вынесите в переменную.
2) У вас `adjacency_list_.at(vertex_id)` хранит в себе `EdgeId`, как вы из них получаете `VertexId`? Ничего не напутали?

2022-11-01 18:59 UTC, Friend-LGA commented on fedotov_chuvashov/graph.hpp
> +  std::unordered_map<Depth, std::set<VertexId>> vertices_at_depth_;
Глубина начинается с 0 и увеличивается с шагом в 1. Можно просто использовать `std::vector`

2022-11-01 18:59 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +constexpr float kGreyDepthDifference = 1.0;
1) Опять же, у вас есть псевдоним для этого типа данных
2) Откуда тут взялся `float`?!?!

2022-11-01 18:59 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +constexpr int kRedDepthDifference = 2;
Аналогично

2022-11-01 18:59 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +    Graph& graph,
Граф что, изменяется?

2022-11-01 18:59 UTC, Friend-LGA commented on fedotov_chuvashov/main.cpp
> +constexpr int input_size = 256;
`naming_convention`

2022-11-01 18:59 UTC, Friend-LGA commented on fedotov_chuvashov/printing.cpp
> +         << ", \"edges_ids\": [";
Опечатка, как и в задании сказано, должно быть `edge_ids`, иначе у меня программа не парсит ваш json

2022-11-02 16:50 UTC, Friend-LGA approved these changes
Правьте и можете мерджить

2022-11-02 16:50 UTC, Friend-LGA commented on fedotov_chuvashov/graph.cpp
> +  set_vertex_depth(new_id, 1);
`magic number`
`kGraphBaseDepth` например

2022-11-02 16:50 UTC, Friend-LGA commented on fedotov_chuvashov/graph.cpp
> +  if (new_depth > 1) {
`magic number`

2022-11-02 16:50 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +constexpr Graph::Depth kRedDepthDifference = 2;
Дублирует аналогичную константу из `graph.cpp`
Должна быть только одна. Логично перенести в `graph.hpp`

2022-11-02 16:50 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +constexpr Graph::Depth kYellowDepthDifference = 1;
Дублирует

2022-11-02 16:50 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +constexpr Graph::Depth kYellowDepthShift = 2;
Какая-то выдуманная константа. Откуда взялось 2? У желтых нет связи с цифрой 2.

2022-11-02 16:50 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
>            (graph.depth() - kYellowDepthShift);
Видимо это должно быть так?
```suggestion
          (graph.depth() - kGraphBaseDepth - kYellowDepthDifference);
```

2022-11-02 20:58 UTC, merged