mamedov_antyukhov/task_04
Friend-LGA/msu_course_cpp_323_2022 pull request #81
Opened 2022-10-23 13:32 UTC by sm0kebamb0o

2022-10-23 16:11 UTC, chereshnya123 approved these changes

2022-10-26 17:40 UTC, chereshnya123 approved these changes

2022-10-28 16:56 UTC, chereshnya123 approved these changes

2022-10-29 23:21 UTC, Friend-LGA requested changes
1) Никаких конфликтов с мастером быть не должно
2) Заодно перенесите изменения в новую папку, которую я для вас создал `mamedov_antyukhov`

2022-10-30 10:40 UTC, chereshnya123 approved these changes

2022-10-31 10:21 UTC, Friend-LGA requested changes

2022-10-31 10:21 UTC, Friend-LGA commented on mamedov_antyukhov/graph.cpp
> +  const auto& second_vertex_edges = get_connected_edge_ids(second_vertex_id);
Подмена понятий, это не грани, а их `id`
`edges` -> `edge_ids`

2022-10-31 10:21 UTC, Friend-LGA commented on mamedov_antyukhov/graph.cpp
> +  return std::find_first_of(
А если мы проверяем зеленую грань (если вершина соединена с самой собой `first_vertex_id == second_vertex_id`), то `find_first_of` всегда будет `true`. Значит для зеленых граней данная логика работать не будет.

2022-10-31 10:21 UTC, Friend-LGA commented on mamedov_antyukhov/graph.cpp
> +        if (d(gen)) {
У вас данная проверка на вероятность выполняется в каждом методе, имеет смысл вынести её в отдельный метод, например `check_probability(double probability)`

2022-10-31 10:21 UTC, Friend-LGA commented on mamedov_antyukhov/graph.cpp
> +    for (auto vertex = vertices.begin(); vertex != vertices.end(); ++vertex) {
1) это не вершина, а итератор
2) Чем создавать лишние переменные типа `vertices` и `vertices_next`, можно просто запрашивать у графа вершины с определенной глубины
```suggestion
    for (const auto& vertex : graph.vertex_ids_at_depth(current_depth)) {
```

2022-10-31 10:21 UTC, Friend-LGA commented on mamedov_antyukhov/graph.cpp
> +  for (Graph::Depth temp_depth = 0; temp_depth < max_depth; ++temp_depth) {
Почему "временная глубина", тогда уж лучше "текущая глубина" (`current_depth`)

2022-10-31 10:21 UTC, Friend-LGA commented on mamedov_antyukhov/graph.cpp
> +      for (int j = 0; j < new_vertices_count; ++j) {
Принятый порядок использования индексов итерации такой `i -> j -> k`. Первым идет всегда `i`

2022-10-31 10:21 UTC, Friend-LGA commented on mamedov_antyukhov/graph.cpp
> +    std::bernoulli_distribution d(probability);
Чем хранить `probability` и `step`, можете просто вычислять вероятность здесь, в одно действие?

2022-10-31 10:21 UTC, Friend-LGA commented on mamedov_antyukhov/graph.cpp
> +}
Вынесите вычисление неприсоединенных вершин в отдельную функцию
```cpp
std::vector<VertexId> get_unconnected_vertex_ids(...);
```

2022-10-31 10:21 UTC, Friend-LGA commented on mamedov_antyukhov/graph.cpp
> +  const double probability = 0.1;
Как вы должны были заместить, это константа, значение которой пришло к нам из задания, и данная переменная не вычисляется и не изменяется никогда. Следовательно её лучше вынести в глобальную константу, а не создавать лишнюю локальную переменную.

2022-10-31 10:21 UTC, Friend-LGA commented on mamedov_antyukhov/graph.cpp
> +  const auto& vertices = graph.get_depth_levels();
Подмена понятий, как переменная "вершины" могут хранить в себе "уровни глубины"?

2022-10-31 10:21 UTC, Friend-LGA commented on mamedov_antyukhov/graph.cpp
> +  for (; it_next != vertices.end(); ++it_next, ++it_temp) {
Что-то вы тут усложнили, упростите
Достаточно просто пройтись по вершинам на каждой глубине и соединить их с вершинами на 2 глубины глубже.
Что-то типа
```cpp
for (Depth current_depth = 0; current_depth < graph.depth() - 2; current_depth++) {
  for (const auto vertex_id : graph.vertex_ids_at_depth(current_depth)) {
    ...
  }
}
```

2022-10-31 10:22 UTC, Friend-LGA commented
И уберите лишние изменения из папки "mamedov_timur"

2022-10-31 10:49 UTC, sm0kebamb0o commented on mamedov_antyukhov/graph.hpp
> +  std::unordered_map<VertexId, std::pair<Depth, Depth>> vertices_depth_ = {};
Тогда может я немного не понимаю, как мы добавляем рёбра: например, мы соединили вершину со 2 уровня с вершиной с 4, тогда получается, что последняя вершина теперь имеет глубину 3, но значит ли это, что можем теперь соединить ее красным ребром с вершиной, на уровне 5, или мы считаем, что ее глубина осталась равной 4?

2022-11-02 18:05 UTC, Friend-LGA commented on mamedov_antyukhov/graph.hpp
> +  std::unordered_map<VertexId, std::pair<Depth, Depth>> vertices_depth_ = {};
Только __серые ребра__ изменяют глубину вершин. Если ты соединяешь вершину со 2 и 4 уровней, значит это красное ребро, а такое ребро не влияет на глубину.

2022-11-02 18:37 UTC, Friend-LGA requested changes
1) `0` - это валидное значение, должен сгенерироваться граф с 0ой глубиной без вершин
![Screenshot 2022-11-02 at 21 29 53](https://user-images.githubusercontent.com/5897136/199572642-048c786c-0b37-41c0-a20f-919f91f81c4c.png)
2) Программа падает
![Screenshot 2022-11-02 at 21 31 05](https://user-images.githubusercontent.com/5897136/199572742-9dacecca-89d4-498d-beb7-2b1df955bb79.png)

2022-11-02 18:37 UTC, Friend-LGA commented on mamedov_antyukhov/graph.cpp
> +  if (new_vertex_depth < depth_levels_.size()) {
Очень неочевидная логика
```suggestion
  if (new_vertex_depth < depth_levels_.size() - 1) {
```

2022-11-02 18:37 UTC, Friend-LGA commented on mamedov_antyukhov/printing.cpp
> +      break;
Нет смысла писать `break` after `return`

2022-11-02 18:37 UTC, Friend-LGA commented on mamedov_antyukhov/printing.cpp
> +      return "yellow";
С какого такого перепугу `yellow` - это значение по умолчанию?
```cpp
case Graph::Edge::Color::Yellow:
```

2022-11-02 18:37 UTC, Friend-LGA commented on mamedov_antyukhov/printing.hpp
> +std::string print_edge_color(const Graph::Edge::Color color);
Аргументы, передаваемые по значению не записываются как `const`

2022-11-02 18:37 UTC, Friend-LGA commented on mamedov_antyukhov/graph.json
> +		{ "id":11, "edges_ids": [10, 16], "depth": 5 },
Опечатка, в задании сказано `edge_ids`, так у меня программа ваш `json` не парсит

2022-11-02 18:49 UTC, sm0kebamb0o commented on mamedov_antyukhov/graph.cpp
> +  if (new_vertex_depth < depth_levels_.size()) {
В этой функции потом опять используется переменная new_vertex_depth для записи в вектор, тогда и там придется на один уменьшать. Лучше, наверное, один раз убавить

2022-11-02 19:52 UTC, Friend-LGA approved these changes
Ревью не запросил, повезло что я наткнулся на ваш ПР. Не забывайте ревью запрашивать.

2022-11-02 19:56 UTC, merged