Tsybina_kovalenko/task_04
Friend-LGA/msu_course_cpp_323_2022 pull request #84
Opened 2022-10-30 14:16 UTC by klevvit

2022-10-31 13:19 UTC, Jedi314 approved these changes

2022-11-01 19:16 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +    assert(to_vertex_id < vertices_.size());
Вроде уже обсуждали. Нет прямой связи между размером коллекции и `id`, только косвенная, а это потенциальные проблемы. Нужно проверять реальное вхождение вершины в коллекцию. `find`, например.

Для этого логично будет добавить метод `bool has_vertex(id) const;`

И, надеюсь, вы не собираетесь обходить весь массив для поиска. Лучше будет использовать `unordered_map`

2022-11-01 19:20 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +  VertexId other_end_of(EdgeId edge_id, VertexId vertex_id) const {
1) А если данные `edge_id` и `vertex_id` вообще не связаны? Нужно бы проверить себя. Добавьте хотя бы `assert`
2) Вы пишите публичный интерфейс графа, данный метод реально кому-то будет необходим? Выглядит больше как вспомогательный метод... Перенесите его хотя бы в `private`

2022-11-01 19:24 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +  std::vector<EdgeId> parents_;
Зачем? Оно хоть где-нибудь используется, или так, по-приколу?

2022-11-01 19:25 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +  const auto& vertex_depths() const { return vertex_depths_; }
Обсуждали насчет низкоуровневого интерфейса в прошлый раз. Эти методы выдают приватную информацию, нарушая энкапсуляцию.

2022-11-01 19:26 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +  const auto& max_depth() const { return max_depth_; }
Почему именно `max_depth`? А `min_depth` есть? Просто `depth` будет недостаточно понятно?

2022-11-01 19:27 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +    if (height_difference == 2) {
Любое, случайно встреченное число в коде, называется "магическое число" (`magic number`). Все такие числа должны быть вынесены в глобальные константы. Например `kRedEdgeDepth`

P.S. за некоторым исключением дефолтные значения выносить не обязательно, такие как `0` или `1`. Но только если они логически являются очевидными и дефолтными.

2022-11-01 19:28 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +    if (height_difference == 1 && !is_connected(from_vertex_id, to_vertex_id)) {
`magic number`

2022-11-01 19:30 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +      }
Опять, надуманно, почему 0 обязательно должна быть корневой?

2022-11-01 19:33 UTC, Friend-LGA commented on tsybina_kovalenko/printing.hpp
> +std::string color_name_of(Graph::Edge::Color edge_color) {
Внимательно читали задание?
1) Давайте придерживаться общей стилистики, `print_edge_color` будет лучше вписываться
2) Распечатка цвета грани - это просто 1 слово, оно не имеет прямого отношения к `json`, следовательно и в `namespace json` ему делать нечего. Достаточно просто `namespace printing`

2022-11-01 19:34 UTC, Friend-LGA commented on tsybina_kovalenko/main.cpp
> +GraphGenerator::Params handle_params_input() {
Длинный метод, можно бы разбить на более короткие

2022-11-01 19:36 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +      : params_(std::move(params)), generator_(std::random_device()()) {}
Генератор прям действительно должен быть членом класса? Он что настолько долго создается?

2022-11-01 19:36 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +  static constexpr float RED_EDGE_GENERATION_CHANCE = 0.33f;
`naming convention`

2022-11-01 19:37 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +  mutable std::mt19937 generator_;
Вот оно, начинается, `mutable`, что-то вы тут усложняете. Его локально нельзя прям использовать?

2022-11-01 19:39 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +          if (distribution(generator_)) {
Давай вынесем логику с берноулли в функцию, например `check_probability(float)`

2022-11-01 19:39 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +            auto new_vertex_id = graph.add_vertex();
Изменяется?

2022-11-01 19:40 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +      auto vertex_depth = graph.depth_of(vertex.id());
Изменяется?

2022-11-01 19:41 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +      if (vertex_depth != 1 && vertex_depth != params_.depth()) {
1) `magic number`
2) Всегда проще для восприятия использовать ранний выход, чем увеличивать вложенность
```cpp
for () {
  if (vertex_depth == kGraphDefaultDepth || vertex_depth == params_.depth()) break;
}
```

2022-11-01 19:45 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +          !graph.is_connected(from_vertex_id, vertex.id())) {
Для каждой жёлтой грани будете обходить все вершины да ещё и проверять их глубину? Кажется, можно сделать более эффективно, например хранить в графе карту глубин, чтобы можно было сразу забирать все вершины с определенной глубины
```cpp
std::vector<std::vector<VertexId>> depth_map_;
```

2022-11-01 19:46 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +    }
Вынесите логику по поиску несоединенных вершин в отдельную функцию, например `get_unconnected_vertex_ids`
Тогда метод `add_yellow_edge` вообще не понадобится. Нужно всегда по возможности выделять логику с четкой отвественностью.

2022-11-01 19:49 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +  void add_red_edge(Graph& graph, Graph::VertexId from_vertex_id) const {
Аналогично

2022-11-01 19:49 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +    for (const auto& vertex : graph.vertices()) {
После того, как добавите карту глубин, будет проще обходить именно её, а не все вершины.

2022-11-01 20:23 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +    assert(to_vertex_id < vertices_.size());
ыыыы всё же на unordered_map переезжать, оки)

2022-11-01 20:31 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +           !(depth_of(from_vertex_id) == 1 && depth_of(to_vertex_id) == 1));
Вижу только пути в большее усложнение логики, не понимаю твою идею логику работы графа. Первая добавленная в него вершина становится корневой, верно? В графе присутствует ровно одна корневая вершина? 
Если мы начинаем соединять в случайном порядке, то какая глубина становится у вершины 3? Ведь эта компонента связности не содержит вершину-корень.
По условию задания всем новым вершинам мы лепим глубину 1, можно ли под капотом лепить -1, а при запросе возвращать 1?

2022-11-01 20:44 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +           !(depth_of(from_vertex_id) == 1 && depth_of(to_vertex_id) == 1));
Чтобы избежать всей этой непонятности, я выбрал, пожалуй, самые простые и здравые ограничения: первая добавленная вершина - корневая (айди у неё ноль), а соединять в случайном порядке нельзя, нужно, чтобы одна из двух соединяемых вершин имела вес (не иметь вес == вес = 1). И особым образом обрабатываем корень, т.к. это единственная вершина, которая "имеет вес" и он равен 1, т.е. 1 обозначает реальный вес, а не "отсутствие" веса

2022-11-01 20:52 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +  VertexId other_end_of(EdgeId edge_id, VertexId vertex_id) const {
1. справедливо, assert докинем
2. потенциально вижу его полезным. Запрашивает юзер рёбра, подсоединённые к вершине, чтоб посмотреть их цвета, скажем. А затем хочет пройти дальше по всем жёлтым рёбрам. Т.е. у него есть айди ребра и айди одной вершины, а надо получить другую вершину. Вот и пригодился метод

2022-11-01 20:58 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +  std::vector<EdgeId> parents_;
хе
и правда
используется в методе children_of, чтоб отфильтровывать вершину-родителя. Но в итоге я переделал код, и children_of нигде не используется
Хотя вообще потенциально полезен... нам в будущем не надо будет обходить граф от корня вглубь?

2022-11-01 21:15 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +    if (height_difference == 1 && !is_connected(from_vertex_id, to_vertex_id)) {
ну единица тут не потому что по условию прописано "разность высот = 1", а потому что по условию "непрямой потомок". Если мысленно подставить любое другое число, то возникают вопросы к проверке is_connected, которая становится бессмысленной. То есть "непрямой потомок" не подразумевает какой-то константы, которая теоретически может отличаться от 1, и это имхо ровно случай, когда эта единица "логически является очевидной и дефолтной"

2022-11-01 21:15 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +    if (height_difference == 2) {
Тут по факту

2022-11-01 21:19 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +  const auto& max_depth() const { return max_depth_; }
Потому что лучше отражает суть, что глубина графа - это максимальная глубина среди его вершин. Изначально было просто depth, но, добавив метод `set_depth`, который меняет глубину _вершины_, а не графа, понял, что может возникнуть путаница, поэтому подчеркнул смысл переменной, добавив `max_`. `min_depth` - ну нет, потому что никому не нужна минимальная глубина графа, либо в нём вершин нет, либо она = 1.

2022-11-01 21:21 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +      }
по логике реализации, см. дискуссию [здесь](https://github.com/Friend-LGA/msu_course_cpp_323_2022/pull/84#discussion_r1010871490), хочу понять, какую реализацию хочешь ты

2022-11-01 21:22 UTC, klevvit commented on tsybina_kovalenko/printing.hpp
> +std::string color_name_of(Graph::Edge::Color edge_color) {
1. Оки
2. Оки, справедливо

2022-11-01 21:22 UTC, klevvit commented on tsybina_kovalenko/main.cpp
> +GraphGenerator::Params handle_params_input() {
Разобьем

2022-11-01 21:23 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +  static constexpr float RED_EDGE_GENERATION_CHANCE = 0.33f;
упс, `_` забыл в конце

2022-11-01 21:30 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +      : params_(std::move(params)), generator_(std::random_device()()) {}
Генератор — нет, но вот random_device — [да](https://stackoverflow.com/a/39301751/13356638), он берет чиселку из `/dev/urandom` со всеми накладными. Так как рандомный seed нам нужен каждый раз при инициализации генератора, имеет смысл создать генератор единожды.

2022-11-01 21:32 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +  mutable std::mt19937 generator_;
хехе, неззя, [вот тут](https://github.com/Friend-LGA/msu_course_cpp_323_2022/pull/84#discussion_r1010920390) написал)

2022-11-01 21:34 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +            auto new_vertex_id = graph.add_vertex();
изменяется. даже коммит пришлось амендить, т.к. не хотел работать с const

2022-11-01 21:36 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +          if (distribution(generator_)) {
ы, bernoulli_distribution конструировать придётся при каждом вызове. Ну в целом да, ладно, справедливо

2022-11-01 21:37 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +      auto vertex_depth = graph.depth_of(vertex.id());
а вот тут `const` пропустил, по фактам

2022-11-01 21:44 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +      if (vertex_depth != 1 && vertex_depth != params_.depth()) {
1. Ну не, не magic number, предлагаю вернуться и обсудить после того, как [определимся с логикой](https://github.com/Friend-LGA/msu_course_cpp_323_2022/pull/84#discussion_r1010871490). 
2. Согласен (ты имел в виду `continue`), но, кажется, в прошлом семестре нам рассказывали, что `continue` якобы лучше не юзать, а писать `if` т.к. компиляторы такое оптимизируют лучше. Показалось мне тогда сомнительным утверждением, но копать и разбираться было лень. Теперь, видимо, придётся (( Ну или забить и сделать, как ты хочешь, тож вариант; подумаем 😁

2022-11-01 21:45 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +          !graph.is_connected(from_vertex_id, vertex.id())) {
Хорошая оптимизация, принято

2022-11-01 21:50 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +    }
👌

2022-11-01 21:52 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +  void add_red_edge(Graph& graph, Graph::VertexId from_vertex_id) const {
👌

2022-11-02 16:59 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +  const auto& vertex_depths() const { return vertex_depths_; }
У графа есть что, вершины и грани. Возвращать их это ОК. То что граф для вершин хранит некий мап `vertex_depths_` - это уже дела графа, детали его внутренней реализации, и делая такой интерфейс вы выдаете детали внутренней реализации наружу, что есть плохо.

А та ситуация была не обратная, а скорее ещё более низкоуровневая.

2022-11-02 17:00 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +  std::vector<EdgeId> parents_;
Как глубоко в будущее ты можешь заглянуть?) Нужно писать актуальный код, иначе можно с головой погрязнуть в предположениях, которые никогда никому не понадобятся.

2022-11-02 17:01 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +  VertexId other_end_of(EdgeId edge_id, VertexId vertex_id) const {
Прекрати `overthinking`, это тебе проблем в будущем принесет. Будешь адаптировать свой код под неиспользуемый интерфейс. Вот если понадобится, тогда и добавишь, не переусложняй.

2022-11-02 17:05 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +  const auto& max_depth() const { return max_depth_; }
Думай с точки зрения внешнего пользователя, который только видит публичный интерфейс, это самое главное. Для него существует какая-нибудь другая глубина графа, кроме как непосредственно глубина? Нет. Значит `depth` наилучшее название, наиболее четко отражающая суть. То что у тебя есть некая приватная логика, это не должно влиять на публичный интерфейс. Назови `set_vertex_depth`, вот это будет более оправданно.
У графа нет ни минимальной глубины, ни максимальной глубины, есть просто глубина.

2022-11-02 17:10 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +    if (height_difference == 1 && !is_connected(from_vertex_id, to_vertex_id)) {
Тут скорее я бы опирался на следующую логику: "почему грань желтая? Потому что она соединяет вершины с разницей в глубине == 1". В таком контексте 1 приобретает определенный смысл, аналогичный 2 для красных граней. Дргуими словами, каждая грань имеет определунную заданную глубину, на которую она соединяет вершины, и было бы не лишним, все эти константы вынести.

Иначе 1 может быть использована как для серых, так и для желтых граней, где гарантия что ты не ошибся? Если ты конкретно напишешь `kYellowDepth`, то из кода будет очевидно, что выполняется именно та логика, которая ожидается.

2022-11-02 17:17 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +  VertexId other_end_of(EdgeId edge_id, VertexId vertex_id) const {
Хорошо, просто сносим)

2022-11-02 17:20 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +           !(depth_of(from_vertex_id) == 1 && depth_of(to_vertex_id) == 1));
> Первая добавленная в него вершина становится корневой, верно?

Это я где-то написал в задании? По факту нет. Если нет вершин, граф имеет глубину 0. Все добавленные в граф вершины попадают на глубину 1, так как это количество шагов требуемых для того чтобы дойти до этих вершин. При создании серого ребра количество шагов от одной вершины до второй увеличивается на 1.

Получается что граф состоит из набора лесов, некоторые из 1 вершины, некоторые из нескольких. Например может быть так:
```
0 -> 5 -> 6 -> 9
1
2 -> 3
4 -> 7
8
10 -> 11 -> 12
```
Получается что в этом случае на 0ой глубине будут `0, 1, 2, 4, 8, 10`, ну и соотвественно на 1ой 2ой и 3ей.

Если ты попробуешь подобную логику реализовать (а по факту так оно и должно быть), то тут можно будет голову сломать. Поэтому мы упрощаем и просто во время генерации каждая новая вершина сразу после создания соединяется с некоторой другой.

А вот то что ты пытаешься сделать - это наложить некие ограничения, которые вообще не факт что нужны, опять `overthinking`. При этом, вводя данные ограничения, ты усложняешь логику. Получается, как говорится "ни рыба ни мясо", вроде и полноценной реализации не добились, но при этом усложнили код.

2022-11-02 17:23 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +           !(depth_of(from_vertex_id) == 1 && depth_of(to_vertex_id) == 1));
Если бы хотелось наложить ограничения, то это нужно было бы делать через интерфейс, например так:
1) При создании графа у него всегда есть корневая вершина
2) Мы не можем просто добавить пустую вершину в граф, нужно обязательно сделать её чьим-то потомком
```cpp
Graph() : root_vertex() {}
add_vertex(VertexId parentId);
```
Но у нас выбран другой подход. Хотя оба из них валидны.

2022-11-02 17:27 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +           !(depth_of(from_vertex_id) == 1 && depth_of(to_vertex_id) == 1));
Понял, в чём у нас расхождение. Что значит "можно дойти до вершин"? Откуда дойти? Например, ты пишешь: `0 -> 5 -> 6 -> 9`, но какая из вершин является начальной, если граф по условию неориентированный? Можно взять любую. То есть в твоей логике, как я понимаю, граф всё же ориентированный, в частности, есть различие между add_edge(5, 6) и add_edge(6, 5). В моей голове такой разницы изначально не было, т.к. в первом, кажется, задании было прописано, что граф неориентированный. Отсюда и overthinking, попытка сочленить ориентированность и твоё представление

2022-11-02 17:27 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +      : params_(std::move(params)), generator_(std::random_device()()) {}
Интересно, ок

2022-11-02 17:28 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +  static constexpr float RED_EDGE_GENERATION_CHANCE = 0.33f;
Нет. `kBlaBlaBla`

2022-11-02 17:30 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +            auto new_vertex_id = graph.add_vertex();
Не верю. Я говорю про `new_vertex_id `, единственное что, он добавялется в очередь, но там должно производиться копирование, соотвественно константа не должна влиять.

2022-11-02 17:33 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +      if (vertex_depth != 1 && vertex_depth != params_.depth()) {
Из моего опыта, читабельность кода привыше всего, покуда не начинаешь овероптимизировать для, например, суперкомпьтеров (что вы должны делать, к слову). Но сначала нужно хороший код писать, а потом оптимизировать, если реально есть необходимость.

2022-11-02 17:39 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +           !(depth_of(from_vertex_id) == 1 && depth_of(to_vertex_id) == 1));
> Что значит "можно дойти до вершин"? Откуда дойти?

Корневой вершины нет, но ведь есть первая глубина (1), где корневая вершина, потенциально, будет находиться. Вот с 1ой глубины и начнем обход. Конкретно в нашем случае, генератор отвечает за то, чтобы на 1ой глубине была только одна вершина, это наши ожидания.

Пример в прошлом комментарии теоретический, так как наш генератор подобный граф создавать не должен, но ничто не мешает создать такой граф другим генератором, или вручную.

2022-11-02 17:42 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +           !(depth_of(from_vertex_id) == 1 && depth_of(to_vertex_id) == 1));
Это как если бы ты писал аналог `std::array` и считал что на первом месте может находиться только, к примеру, цифра 5. Кажется это лишнее, массив не должен решать такие вопросы. Вот и граф наш расценивай как универсальный инструмент.

А вот генератор уже имеет определённую логику, которая накладывает ограничения на получаемый граф.

2022-11-02 19:06 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +  VertexId other_end_of(EdgeId edge_id, VertexId vertex_id) const {
done

2022-11-02 19:18 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +  std::vector<EdgeId> parents_;
зачищено

2022-11-02 19:33 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +  const auto& max_depth() const { return max_depth_; }
fixed

2022-11-02 19:35 UTC, klevvit commented on tsybina_kovalenko/printing.hpp
> +std::string color_name_of(Graph::Edge::Color edge_color) {
done

2022-11-02 19:55 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +      : params_(std::move(params)), generator_(std::random_device()()) {}
Могу, сделаль

2022-11-02 20:27 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +          if (distribution(generator_)) {
сделано

2022-11-02 20:27 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +            auto new_vertex_id = graph.add_vertex();
а о да блин, я про distribution подумал

2022-11-02 20:36 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +      auto vertex_depth = graph.depth_of(vertex.id());
пофиксил

2022-11-02 20:43 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +    if (height_difference == 2) {
fixed

2022-11-02 20:55 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +    if (height_difference == 1 && !is_connected(from_vertex_id, to_vertex_id)) {
аргументы приняты, пофикшено)

2022-11-02 20:56 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +  static constexpr float RED_EDGE_GENERATION_CHANCE = 0.33f;
fixed

2022-11-02 21:28 UTC, Jedi314 commented on tsybina_kovalenko/graph.hpp
> +           !(depth_of(from_vertex_id) == 1 && depth_of(to_vertex_id) == 1));
пофиксили 1 пункт

2022-11-02 21:29 UTC, Jedi314 commented on tsybina_kovalenko/main.cpp
> +GraphGenerator::Params handle_params_input() {
пофикшено

2022-11-05 20:45 UTC, Friend-LGA requested changes
Почему до сих пор не все комментарии исправлены. Исправьте из прошлого ревью, что ещё не исправлено.

2022-11-05 20:45 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +    set_vertex_depth(new_vertex_id, 1);
`magic number`
`kGraphBaseDepth` к примеру

2022-11-05 20:45 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +        set_vertex_depth(non_root_id, 2);
`magic number`

2022-11-05 20:45 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +  static constexpr int kYellowEdgeDepth = 1;
У нас есть специальный псевдоним для данных типов `Graph::Depth`

2022-11-06 18:08 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +  static constexpr int kYellowEdgeDepth = 1;
ну это не совсем так, это разница двух Graph::Depth. Разница двух char - это же не char

2022-11-06 18:10 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +  static constexpr int kYellowEdgeDepth = 1;
я настырный, но сейчас мы объективно в цейтноте, так что просто сделаю, как ты хочешь)

2022-11-06 19:29 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +          !graph.is_connected(from_vertex_id, vertex.id())) {
сделано

2022-11-06 19:35 UTC, Jedi314 commented
> 1. Ошибочный ввод, например `qwer` должен обрабатываться аналогично негативному числу.
>    ![Screenshot 2022-11-01 at 22 51 38](https://user-images.githubusercontent.com/5897136/199326159-2c0396ca-1d42-41ef-8fa8-20857fe92c9f.png)
> 2. При запросе глубины 0, создается граф с глубиной 1
>    ![Screenshot 2022-11-01 at 22 51 51](https://user-images.githubusercontent.com/5897136/199326220-179bf246-34c8-43ed-b4ce-4491db648a90.png)

пофикшен 2 пункт

2022-11-06 19:56 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +    }
done

2022-11-06 19:56 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +    for (const auto& vertex : graph.vertices()) {
done

2022-11-06 19:56 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +  void add_red_edge(Graph& graph, Graph::VertexId from_vertex_id) const {
done

2022-11-06 20:02 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +      if (vertex_depth != 1 && vertex_depth != params_.depth()) {
логика переделана => отвалилась актуальность п.2. п.1 поправил)

2022-11-06 20:42 UTC, Jedi314 approved these changes

2022-11-08 12:44 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +  static constexpr int kYellowEdgeDepth = 1;
Ты был на глубине 5, переместился на глубину 3, соотвественно разница между ними в 2 глубины, верно? Если ты будешь арифметические операции на глубинах делать, все промежуточные значения так же будут являться глубиной.

Если ещё аналогию привести, например в коде ты встретишь
```cpp
Depth initial_depth = 5;
Depth depth = initial_depth + "новая глубина";
```

Как по твоему это выглядит, нормально? Твой `int`, формально, такой же отличающийся от "глубины" тип данных, как и строка. Просто за счет того, что у тебя есть дополнительная информация, ты знаешь, что "глубина" - это и есть `int`, поэтому и можешь делать математические операции над ними. Но с точки зрения внешнего наблюдателя, ты пытаешься выполнять операции над разными типами данных, что в нормальной ситуации является ошибкой и компилятор такого делать не позволяет.

Про чары интересно, глянул, там происходит конвертация в инт. У нас же никакой конвертации нет. Да и в целом не сказал бы что это ожидаемое поведение, в Java, если не ошибаюсь, вполне себе можно чары складывать и отнимать, и получишь чар, просто с другими кодом. А в c++ стандарт решил что должно быть особенное поведение в этом случае, поэтому это скорее исключение, чем правило.

2022-11-08 13:01 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +    Graph::Depth vertex_depth() const { return depth_; }
Что за ненужные изменения?... Чем больше ненужных изменений в коде, тем сложнее делать ревью, в итоге все страдают и вы и я, и время затягивается.

Почему `глубина вершины`??? Мы же в параметрах задаём глубину графа. Плохое переименование. Верните.

2022-11-08 13:04 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +  static constexpr Graph::Depth kYellowEdgeStartDepth = 2;
Понял почему ты про `_` писал. Вообще да... даже не знаю какого `naming convention` в этом случае придерживаться, редко нечто такое втречается. Ок, в следующей задаче (5) это все дело нужно будет перенести в приватный неймспейс, пока оставьте как есть

2022-11-08 13:28 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +  static constexpr int kYellowEdgeDepth = 1;
Сорян, насколько я знаю, `char - char = int` - стандартная штука почти во всех языках, в т.ч. в java. Иначе она не несет смысла: нам важно, что расстояние между `'a'` и `'j'` равно 9, а результат `'j' - 'a' = '\t'` - это странно и бесполезно. Плюс неясно, как быть с `'a' - 'j'` в случаях, когда `char` хранится под капотом как `unsigned char`.
<img width="655" alt="image" src="https://user-images.githubusercontent.com/33697374/200574575-46a829ac-9539-4d63-bb49-81da5db2b79c.png">
Впрочем, к нашей задаче это уже не имеет никакого отношения

2022-11-08 13:41 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +    int depth_jump = depth_of(to_vertex_id) - depth_of(from_vertex_id);
1. Справедливо
2. Упростить и дополнительно подчеркнуть, что при нынешней логике реализации всё полетит к чертям, если передать `from_vertex_id` и `to_vertex_id` не в том порядке

2022-11-08 13:50 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +  Depth depth_ = 0;
Как же? Мы ведь должны [в printing::json::print_graph](https://github.com/Jedi314/msu_course_cpp_323_2022/blob/13af355d08f0d56a85105be0b8d027b799e61d4a/tsybina_kovalenko/printing.hpp#L63) выводить глубину графа. Да, мы можем вычислять максимальную глубину на лету, обходя карту глубин и беря максимальный ключ, но это будет O(n), мы такое не хотим

2022-11-08 13:53 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +    Graph::Depth vertex_depth() const { return depth_; }
Опа, неожиданно, не заметили. Rename в vscode решила переименовать то, что переименовывать не нужно было. Откатываем

2022-11-08 14:18 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +  const auto& depth() const { return depth_; }
1. Вообще не интуитивно, нет чёткой логической связи, что `depth_map_.size()` равен максимальной глубине всего графа. У не знакомого с кодом читателя сразу возникнут вопросы: что, если в depth_map_ есть ключи, под которыми не лежит ни одной вершины? Если бы у нас был `depth_vector_`, тогда мб, но у нас ведь `depth_map_`, тут становится совсем непрозрачно. Что, если где-то используется "техническая" глубина 0 или -1? Надёжней и ясней явно иметь переменную depth_ и обновлять её. 
2. Справедливо

2022-11-08 19:53 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +  const auto& depth() const { return depth_; }
Действительно, проглядел. Лучше использовать не `std::unordered_map` а `std::vector`, глубина начинается с 0 и увеличивается на 1, тут логично использовать вектор, а мап тут ни к чему. То что я писал `depth_map` - подразумевалась карта глубины, то есть просто с английского "map" - "карта", а не тип данных `std::unordered_map`, тем более, что в названии никогда не записывается тип данных переменной, так как на высоком уровне это не считается полезной информацией. Данная карта и репрезентует собой все глубины графа, размер этой карты и есть глубина графа, куда уж логичней. Все вершины, которые находятся в графе попадают на какую-то глубину, прямым отрождением чего и является данная карта. То есть размер этой карты и является глубина графа.

> Что, если где-то используется "техническая" глубина 0 или -1

0 у нас как раз и используется. Если у графа глубина = 0, значит он пустой, если 1 и больше, значит там есть вершины. Данная карта именно то, чем она и является списком глубин графа. Куда уж более прямая логическая связь.

А вот то что ты дублируешь эти данные и заводишь дополнительную переменную, это уже может привести к проблемам. Все данные должны быть уникальными, насколько это возможно.

2022-11-08 19:55 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +  static const std::unordered_set<VertexId> kEmptySet;
`static` на то и статик, что он никогда не удаляется, даже при выходе из функции.

2022-11-08 19:58 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +    int depth_jump = depth_of(to_vertex_id) - depth_of(from_vertex_id);
> Упростить и дополнительно подчеркнуть, что при нынешней логике реализации всё полетит к чертям, если передать from_vertex_id и to_vertex_id не в том порядке

Не обязательно

2022-11-08 20:23 UTC, Friend-LGA requested changes
Дублирование данных (использование дополнительной лишней переменной для хранения глубины графа) - принципиальный момент. Если бы не это - принял.

2022-11-08 20:23 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +    const int depth_jump = depth_of(to_vertex_id) - depth_of(from_vertex_id);
Depth

2022-11-08 20:23 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +    if (params_.depth() <= 1) {
`magic number`, `kGraphBaseDepth`?

2022-11-08 20:23 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +  static constexpr Graph::Depth kYellowEdgeStartDepth = 2;
По факту эти константы не самостоятельные константы, а:
```cpp
static constexpr Graph::Depth kRedEdgeStartDepth = kGraphBaseDepth;
static constexpr Graph::Depth kYellowEdgeStartDepth = kGraphBaseDepth;
```
Следовательно в них вообще нет особого смысла. А то что вы пытаетесь оптимизировать расчет желтых граней и начинаете с 2, это на самом деле не очень хорошо, ибо кто-то другой, когда-нибудь в будущем может изменить формулу вероятности для желтых граней и то, что они не строятся на 1ом урвне будет неожиданным поведением.

Или можно переформулировать так: они все строятся с 1ой глубины, просто у некоторых из них на 1ой глубине вероятность 0. А вы форсите их строиться со 2ой глубины.

2022-11-08 20:23 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +         vertex_depth <= params_.depth() - kYellowEdgeDepthJump;
Так как после генерации серых граней ожидаемая глубина графа и реальная глубина графа могут отличаться, при генерации желтых нужно использовать реальную глубину, иначе можно выйти за пределы.

2022-11-08 20:23 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +         vertex_depth <= params_.depth() - kRedEdgeDepthJump; ++vertex_depth) {
Аналогично, нужно использовать реальную глубину

2022-11-08 20:23 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +  const auto& depth() const { return depth_; }
Вот наглядно ещё объясняю:

Как выглядит карта глубин:
```
0: []
1: [0]
2: [1, 2, 3]
3: [4, 5, 6, 7, 8, 9]
4: [10, 11, 12, 13]
5: [14]
```
Если внимательно посмотреть - это и есть наш граф, это прямая его репрезентацию, только исключающая грани, очевидно, что размер карты и есть глубина графа.

2022-11-08 20:23 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +  std::unordered_map<Depth, std::unordered_set<VertexId>> depth_map_;
Лучше использовать вектор. Глубина начинается 0 и увеличивается на 1, нет нужды в мапе.

2022-11-08 20:26 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +  const auto& depth() const { return depth_; }
Вот наглядно ещё объясняю:

Как выглядит карта глубин:
```
0: []
1: [0]
2: [1, 2, 3]
3: [4, 5, 6, 7, 8, 9]
4: [10, 11, 12, 13]
5: [14]
```
Если внимательно посмотреть - это и есть наш граф, это прямая его репрезентацию, только исключающая грани, очевидно, что размер карты и есть глубина графа.

2022-11-08 23:54 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +  std::unordered_map<Depth, std::unordered_set<VertexId>> depth_map_;
Почему 0? Минимальная глубина ведь всегда 1

2022-11-10 03:20 UTC, klevvit commented on tsybina_kovalenko/graph_generator.hpp
> +         vertex_depth <= params_.depth() - kYellowEdgeDepthJump;
"можно выйти за пределы" нам не грозит, потому что мы не дурацкий вектор используем для карты глубин, а мапу, которая по реализации в худшем случае вернёт пустое множество. (Кстати, вектор для хранения вершин поначалу был ок, а потом пришлось заменить его мапой — почему для карты глубин не так?) Так что здесь это разве что небольшая оптимизация для редких случаев.

Ты называешь нашу реализацию сокрытием багов, я её называю инкапсуляцией: тебе не надо думать о том, что под капотом у графа, об этом уже позаботились разработчики графа. Если у графа нельзя запрашивать глубины, на которых нет ни одной вершины — будьте добры записать это в мануал функции. А иначе я по дефолту предполагаю, что функция умеет обрабатывать слишком большие значения, возвращая корректный ответ на запрос "set со всеми вершин графа на этой глубине" — пустой set.

2022-11-10 03:31 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +  std::unordered_map<Depth, std::unordered_set<VertexId>> depth_map_;
В плане, раз всё же вектор, почему не нумеровать глубину с 0?

2022-11-13 04:59 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +  const auto& depth() const { return depth_; }
Задолбался уже от этих "я хотел, чтобы вы сделали вектор, поэтому переделывайте всё, что уже написали и что хорошо работает, на вектор". Хотя к вектору есть вопросы, как и к мапе.
Окей, я пытался. Последним был в группе, кто говорил, что Лутков классный, что с ним просто дискутировать надо, если вы не согласны, а не молча покоряться и ругаться на него в чат группы. Что ж, ты во всём прав, ложусь на твоё прокрустово ложе.

2022-11-13 05:24 UTC, klevvit commented on tsybina_kovalenko/graph.hpp
> +    const int depth_jump = depth_of(to_vertex_id) - depth_of(from_vertex_id);
да-да, `char - char = char`. Как скажешь.

2022-11-13 14:30 UTC, Jedi314 approved these changes

2022-11-13 19:16 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +  const auto& depth() const { return depth_; }
Твой выбор, как к этому относиться. Хочешь дискуссировать - мы дискуссируем. Хочешь чтобы я с тобой согласился - убеди.

2022-11-13 19:22 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +         vertex_depth <= params_.depth() - kYellowEdgeDepthJump;
Обрабатывать угловые случаи это правильно (но не всегда, зависит от соглашений), что не должно побуждать тебя, делать это целенаправленно. Если у тебя есть реальные ожидаемы данные, то и пользуйся ими, не нужно пользоваться другими, косвенно подходящими, только потому, что у тебя программа их обработает.

2022-11-13 19:27 UTC, Friend-LGA commented on tsybina_kovalenko/graph.hpp
> +  std::unordered_map<Depth, std::unordered_set<VertexId>> depth_map_;
Так и есть, это вектор, нумеруем глубину с 0. `0 глубина = отсутствие вершин`. Можно этот случай обработать как особенный и сдвинуть все глубины на 1 и хранить первую глубину как 0, что не помешает реализовать эту логику через вектор. Только, в таком случае, думаю, появится лишнее усложнение кода, и выйгрыша в производительности тоже не будет, а тогда зачем усложнять?

2022-11-13 19:32 UTC, Friend-LGA commented on tsybina_kovalenko/graph_generator.hpp
> +  static constexpr int kYellowEdgeDepth = 1;
Что как раз и делает этот случай "исключением", а не "правилом", верно?

2022-11-13 20:06 UTC, Friend-LGA approved these changes
Нет смысла агриться и спорить с каждым из моих комментариев просто из-за эмоций. У меня тоже куча дел и я пишу это комментарии не "по приколу", а потому что я взялся поделиться с вами своим опытом, и пытаюсь делать это добросовестно. Вы вольны решать, нужен вам этот опыт или нет. Если ты хочешь дискуссировать, то будь готов отстаивать свою позицию. Если же у тебя на это не хватает времени, то тут на меня злиться бесполезно.

Глобально, у вас есть 3 модели поведения (их, конечно, больше, но эти коррелируют с нашей ситуацией):
1) Углубленно дискуссировать и ждать моих ответов, что может повлечь провал дадлайна, так как я довольно занятой человек.
2) Углубленно дискуссировать, но при этом делать исправления заранее, даже не смотря на то что не согласны, при этом будет возможность и обсудить и не провалить дедлайн.
3) Не дискуссировать и выполнять задачи сразу по моим требованиям не разбираясь что и почему, в этом случае дедлайн провалить маловероятно.

Плюсом было бы, конечно, ещё и посещать занятия, так как мы разбираем спорные моменты. Но понятно, что в текущей ситуации не все так просто, к сожалению.

2022-11-13 20:29 UTC, merged