afanasev_nikita/task_04
Friend-LGA/msu_course_cpp_323_2022 pull request #85
Opened 2022-10-31 03:30 UTC by nikitanmlk

2022-10-31 11:26 UTC, Friend-LGA requested changes
Дальше будете работать вместе с Крымским Святославом. Я переименую ПР и создам для вас новую папку, перенесите изменения в неё (`afanasev_krymskiy`).
Святослав, тебе нужно проверить и зааппрувить данный ПР, перед моей следующей проверкой.
Никита, ты можешь добавить его в коллабораторы в свой форк, и можете работать вместе в одном бранче. Это по желанию.

2022-10-31 11:26 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +  adjacency_list_[vertex_id];
Это что?

2022-10-31 11:26 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +    Graph& graph,
Это `in-out` аргумент? Почему не `const`?

2022-10-31 11:26 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +}
Что за прикол?

2022-10-31 11:26 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +      std::bernoulli_distribution distribution(probability);
У тебя в каждом методе выполняется одинаковая проверка вероятности, вынеси её в отдельную функцию, например `check_probability(double)`

2022-10-31 11:26 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +        for (size_t i = 0; i < params_.new_vertices_count(); ++i) {
Почему `size_t`?

2022-10-31 11:26 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +            std::uniform_int_distribution<> uniform_integer_distribution(
`uniform_integer_distribution` у тебя тоже используется дважды, всю логику. которая используется многократно, нужно не дублировать, а выносить в отдельные функции.
В данном случае что-то типа `get_random_vertex_id(list)`

2022-10-31 11:26 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +#include <functional>
Зачем?

2022-11-01 13:05 UTC, nikitanmlk commented on afanasev_nikita/prog.cpp
> +  adjacency_list_[vertex_id];
- Это вынесенный метод класса `Graph`, это сделано для того чтобы можно было объявить `constexpr Graph::Depth kDefaultDepth` и использовать его в классе `Graph`;
- В самом методе вычисляется новый ID вершины, вершина добавляется в `vertices_` , ID добавляется в `adjacency_list_`, а затем устанавливается ее глубина по умолчанию и возвращается ID.

2022-11-01 14:16 UTC, nikitanmlk commented on afanasev_nikita/prog.cpp
> +}
Да, это лишнее я написал.

2022-11-01 14:19 UTC, nikitanmlk commented on afanasev_nikita/prog.cpp
> +        for (size_t i = 0; i < params_.new_vertices_count(); ++i) {
Логичнее написать `int`?

2022-11-01 14:23 UTC, nikitanmlk commented on afanasev_nikita/prog.cpp
> +#include <functional>
Сначала хотел использовать `std::reference_wrapper` для хранения ссылок на объекты в контейнере, но потом узнал, что можно хранить ID объектов. В общем забыл убрать.

2022-11-01 18:02 UTC, nikitanmlk commented on afanasev_nikita/prog.cpp
> +    Graph& graph,
Исправил.

2022-11-01 18:03 UTC, nikitanmlk commented on afanasev_nikita/prog.cpp
> +            std::uniform_int_distribution<> uniform_integer_distribution(
Сделал.

2022-11-01 18:03 UTC, nikitanmlk commented on afanasev_nikita/prog.cpp
> +  const std::unordered_map<EdgeId, Edge>& get_graph_edges() const {
Исправил.

2022-11-01 20:02 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +  adjacency_list_[vertex_id];
Я про `adjacency_list_[vertex_id];` ты просто получил значение и ни к чему его ни присвоил, это очень странно. Ты, наверное, полагаешься на логику мапа, что при получении значения, если его не существует, он автоматически создаст новое. Но так писать нельзя, это не читаемо. Если хочешь присвоить значение - то присваивай его. `adjacency_list_[vertex_id] = {};`

2022-11-01 20:03 UTC, Friend-LGA commented on afanasev_nikita/prog.cpp
> +        for (size_t i = 0; i < params_.new_vertices_count(); ++i) {
Если `new_vertices_count ` хранит `int`, то да

2022-11-01 20:19 UTC, Friend-LGA requested changes
1) Святослав, перед моим ревью, тебе надо сделать ревью и, если все ОК, зааппрувить. Никита, помоги ему разобраться.
2) Уберите лишние изменения из папки "afanasev_nikita"

2022-11-01 20:19 UTC, Friend-LGA commented on afanasev_krymskiy/prog.cpp
> +  const std::vector<VertexId>& vertices_at_depth(Depth depth) {
Ты просто получаешь вершины с глубины, метод должен быть константным, он не может изменять объект, логически

2022-11-01 20:19 UTC, Friend-LGA commented on afanasev_krymskiy/prog.cpp
> +  Depth depth() const { return current_depth_; }
```cpp
return vertices_at_depth_.size();
```

2022-11-01 20:19 UTC, Friend-LGA commented on afanasev_krymskiy/prog.cpp
> +  Depth current_depth_ = 0;
Все же она тебе не нужна, у тебя же есть `vertices_at_depth_.size()`, это и есть глубина графа

2022-11-01 20:19 UTC, Friend-LGA commented on afanasev_krymskiy/prog.cpp
> +    if (to_vertex_depth - from_vertex_depth == 2) {
Любые числа, встречаемые в коде, если они ни к чему не привязаны, называются `magic number`, такие числа нужно выносить в глобальные константы, например
```cpp
static constexpr Depth kRedEdgeDepth = 2; 
```

2022-11-01 20:19 UTC, Friend-LGA commented on afanasev_krymskiy/prog.cpp
> +    if (to_vertex_depth - from_vertex_depth == 1 &&
`magic number`

2022-11-01 20:19 UTC, Friend-LGA commented on afanasev_krymskiy/prog.cpp
> +  adjacency_list_[vertex_id];
`adjacency_list_[vertex_id];` повторяю, такая запись неприемлема

2022-11-01 20:19 UTC, Friend-LGA commented on afanasev_krymskiy/prog.cpp
> +    const Graph::VertexId vertex_id,
По значению передаются без конст

2022-11-01 20:19 UTC, Friend-LGA commented on afanasev_krymskiy/prog.cpp
> +const std::vector<Graph::VertexId> get_unconnected_vertices_ids(
Возвращать по значению `const` недопустимо, зачем ты решаешь за внешнего пользователя, должна ли изменяться его переменная.

2022-11-01 20:19 UTC, Friend-LGA commented on afanasev_krymskiy/prog.cpp
> +  for (auto vertex_id_depth_greater : vertices_ids) {
конст

2022-11-01 20:19 UTC, Friend-LGA commented on afanasev_krymskiy/prog.cpp
> +      for (auto vertex_id : graph.vertices_at_depth(depth)) {
конст

2022-11-01 20:19 UTC, Friend-LGA commented on afanasev_krymskiy/prog.cpp
> +      float probability =
конст

2022-11-01 20:19 UTC, Friend-LGA commented on afanasev_krymskiy/prog.cpp
> +      float probability = (depth - 1) / (params_.get_depth() - 2.f);
конст

2022-11-01 20:19 UTC, Friend-LGA commented on afanasev_krymskiy/prog.cpp
> +              graph, vertex_id, graph.vertices_at_depth(depth + 1));
`magic number`

2022-11-01 20:19 UTC, Friend-LGA commented on afanasev_krymskiy/prog.cpp
> +            !graph.vertices_at_depth(depth + 2).empty()) {
`magic number`

2022-11-01 20:59 UTC, ludmik approved these changes

2022-11-01 22:25 UTC, ludmik approved these changes

2022-11-01 22:35 UTC, nikitanmlk commented on afanasev_krymskiy/prog.cpp
> +  adjacency_list_[vertex_id];
А что нужно написать? Я не понимаю, что нужно сделать и что не так.

2022-11-01 22:54 UTC, ludmik approved these changes

2022-11-01 22:55 UTC, ludmik approved these changes

2022-11-01 23:02 UTC, ludmik approved these changes

2022-11-02 07:22 UTC, ludmik approved these changes

2022-11-02 17:49 UTC, Friend-LGA commented on afanasev_krymskiy/prog.cpp
> +  adjacency_list_[vertex_id];
Я же оставлял комментарий в прошлый раз. [Вот](https://github.com/Friend-LGA/msu_course_cpp_323_2022/pull/85#discussion_r1010848875)

2022-11-02 17:59 UTC, nikitanmlk commented on afanasev_nikita/prog.cpp
> +  adjacency_list_[vertex_id];
Поменял `adjacency_list_.emplace(vertex_id, std::move(std::vector<VertexId>()))` на `adjacency_list_[vertex_id] = {}`.

2022-11-02 18:03 UTC, Friend-LGA approved these changes

2022-11-02 18:11 UTC, merged