kuzminskiy_stafeev/task_05
Friend-LGA/msu_course_cpp_323_2022 pull request #86
Opened 2022-11-01 19:28 UTC by KuzmaLine

2022-11-01 19:30 UTC, Jecteroid approved these changes

2022-11-05 21:39 UTC, Friend-LGA requested changes

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.hpp
>  };
Задавать лишнюю ненужную информацию в c++ не принято, достаточно просто пустого массива

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.hpp
> +    return edges_of_color_.at(color);
Можно сделать так:
```suggestion
    if (edges_of_color_.find(color) == edges_of_color_.end()) {
      static const std::array<EdgeId> empty_result();
      return empty_result;
    }
    return edges_of_color_.at(color);
```

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_0.json
> +{"depth":4,"vertices":[{"id":12,"edge_ids":[11,16],"depth":4},{"id":11,"edge_ids":[10,19],"depth":4},{"id":10,"edge_ids":[9,17,18,21],"depth":4},{"id":9,"edge_ids":[8,12,15],"depth":4},{"id":8,"edge_
`json` теперь должны храниться в папке `temp`, а следовательно, не попадать в репозиторий

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.hpp
> +  std::unordered_map<Edge::Color, int> edges_of_color_ = {
Возвращать количество граней - это очень специфическая логика, более универсально будет возвращать все `id` граней определенного цвета
```cpp
std::unordered_map<Edge::Color, std::vector<EdgeId>> edge_ids_of_color_;
```

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.cpp
>  static constexpr Graph::Depth kBaseDepth = 1;
Все локальные для файла константы и функции принято записывать в приватный неймспейс

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph.hpp
>  #pragma once
`#pragma once` всегда должна быть на первом месте!!!
Иначе код, написанный до, может быть включен множество раз

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_json_printing.hpp
> +#include <iomanip>
Это зачем здесь появилось?

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_printing.cpp
> +}
Не относится к распечатке графа, это скорее общая логика, перенесите её в `main.cpp`

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_printing.cpp
> +}
Тем более не относится к графу, это логика логгера, он к каждому сообщению добавялет дату. В приватный неймспейс внутри логгера.

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_printing.hpp
> +#include <sstream>
Всё лишнее

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/main.cpp
> -#include <stdexcept>
`std::runtime_error` все ещё используется, почему убрали?

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_logger.hpp
> +  }
1) Зачем поинтер?
2) В `hpp` только однострочные методы
2) Мjжно проще
```suggestion
  static Logger& get_logger() {
    static Logger instance;
    return instance;
  }
```

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_logger.hpp
> +};
Это что-то лишнее

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_logger.hpp
> +  static Logger* _instance;
Это не нужно

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_logger.hpp
> +  std::ofstream ofs;
1) Назовите переменную получше
2) Задавать путь лучше в конструкторе
```cpp
Logger() : ofstream(config::kLogFilePath) {}
```

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_logger.hpp
> +#include "graph.hpp"
Вряд ли они все нужны будут в `hpp` файле

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_logger.cpp
> +Logger* Logger::_instance = NULL;
Это не будет нужно

2022-11-05 21:39 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +}  // namespace
```cpp
generate_green_edges
generate_yellow_edges
generate_red_edges
```
тоже свободные функции, могут быть убраны из интерфейса и перенесены в приватный неймспейс

2022-11-05 21:50 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_printing.cpp
> +      "red: " + std::to_string(graph.edges_of_color(Graph::Edge::Color::Red));
У вас есть `print_edge_color`, его и нужно использовать.
Наверное тут можно использовать цикл `for`?

2022-11-06 11:41 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph_generator.cpp
> +}  // namespace
Эти функции принадлежат классу GraphGenerator. Без него невозможно, т.к. по заданию параметры графа находятся в Params.
Если выдвигать их в свободные функции, то тогда вообще надобность в GraphGenerator отпадает, нужен будет только Params.

2022-11-06 13:37 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +}  // namespace
1) Нет, они не используют `params`, у вас, кажется, как раз в этом и была ошибка в прошлом таске, что вы `params` использовали?
2) Нет, не отпадет, покуда есть функция `generate`

2022-11-06 13:40 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph_generator.cpp
> +}  // namespace
Вы мне предлагаете передавать в generate_grey_edges и в остальные depth и new_vertices_count?

2022-11-06 14:07 UTC, Friend-LGA requested changes

2022-11-06 14:07 UTC, Friend-LGA commented on kuzminskiy_stafeev/main.cpp
> +std::string generation_started_string(int i) {
Однобуквенные названия, особенно в интерфейсе недопустимы. Назовите нормально аргумент.

2022-11-06 14:07 UTC, Friend-LGA commented on kuzminskiy_stafeev/main.cpp
> +std::string generation_finished_string(int i,
Аналогично

2022-11-06 14:07 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_logger.hpp
> -  virtual ~Logger(void) {}
> ... это не нужно

относилось только к `static Logger* _instance;`, спрятать конструктор и деструктор нужно обязательно, иначе это будет не синглтон.

2) Деструктор не нужно делать виртуальным, у нас же не используется наследование здесь, `void` не нужен и вместо пустых скобочек лучше писать `default`:

`~Logger() = default;`

2022-11-06 14:13 UTC, KuzmaLine commented on kuzminskiy_stafeev/main.cpp
> +}
Противоречие.
Вы сказали переставить generation_started в main.cpp, который использует get_current_date_time. Из приватного namespace логгера я не смогу его вызвать в main.cpp

2022-11-06 14:35 UTC, KuzmaLine commented on kuzminskiy_stafeev/main.cpp
> +}
К тому же, я не понимаю, почему generation_started - не логика логгера, а get_current_date_time - логика логгера. В чём разница между ними с точки зрения логики?

2022-11-06 14:43 UTC, KuzmaLine commented on kuzminskiy_stafeev/main.cpp
> +}
get_current_date_time - просто берёт текущее время, я не понимаю, какое это отношение имеет к логированию, учитывая то, что generation_started_string вообще сделан исключительно для логгера, но при этом, он отношения к логгеру почему-то не имеет.

2022-11-06 18:42 UTC, Friend-LGA commented on kuzminskiy_stafeev/main.cpp
> +}
Зачем нам логгер? Чтобы отдать ему ответственность по генерированию логов, верно? Все логи имеют дату логирования, соотвественно это задача логгера, подставить дату. Есть 2 пути, написать логику по вычислению текущей даты и времени 1 раз внутри логгера и спрятать эту реализацию от всех других, соотвественно никто не будет вынужден вычислять дату и время, это будет происходить автоматически внутри логгера. Или же при каджом вызове логгера из всех мест программы, где это может потребоваться, необходимо будет каждый раз вычислять текущую дату и время. Какой подход тебе кажется более оптимальным? Верно, реализовать эту логику 1 раз там, где она и требуется, внутри логгера.

2022-11-06 18:53 UTC, KuzmaLine commented on kuzminskiy_stafeev/main.cpp
> +}
Вы не ответили на мой вопрос, когда мне тогда вызвать из main.cpp get_current_date_time

2022-11-06 18:57 UTC, Friend-LGA requested changes
Не работает
![Screenshot 2022-11-06 at 21 56 52](https://user-images.githubusercontent.com/5897136/200189674-f89355f9-7d2f-47af-b06f-7d0879f4291a.png)

2022-11-06 18:57 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_logger.hpp
> +#include "config.hpp"
> Даже несмотря на то, что конструктор однострочный, лучше перенести его в cpp, чтобы избавиться от зависимости в `config.hpp` в интерфейсе.

Конструктор перенесли, а от`#include "config.hpp"` не избавились

2022-11-06 18:57 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_logger.hpp
> +#include "graph.hpp"
Зачем?
А вот `string` не хватает

2022-11-06 19:09 UTC, KuzmaLine commented
> Не работает ![Screenshot 2022-11-06 at 21 56 52](https://user-images.githubusercontent.com/5897136/200189674-f89355f9-7d2f-47af-b06f-7d0879f4291a.png)

Крайне странно.
Во первых мой испольняемый файл называется prog, во вторых, у меня всё создаётся.

2022-11-06 19:19 UTC, Friend-LGA requested changes

2022-11-06 19:19 UTC, Friend-LGA commented on kuzminskiy_stafeev/main.cpp
> +}
Зачем тебе его вызывать из `main`?

2022-11-06 19:19 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_logger.hpp
> +
Да, нужно ещё удалить copy и move конструкторы и операторы
```cpp
  Logger(const Logger& other) = delete;
  void operator=(const Logger& other) = delete;

  Logger(Logger&& other) = delete;
  void operator=(Logger&& other) = delete;
```

2022-11-06 19:21 UTC, KuzmaLine commented on kuzminskiy_stafeev/main.cpp
> +}
![image](https://user-images.githubusercontent.com/109547354/200190602-90055594-a4e7-4966-82c1-d1eabc88cb23.png)

2022-11-06 19:25 UTC, KuzmaLine commented on kuzminskiy_stafeev/main.cpp
> +}
Я не понимаю, как вы себе это представляете. Вы попросили сделать нас метод log, который записывает в log файл то, что хочет main, ТО ЕСТЬ, у вашего логгера цель лишь одна - запись в файл и в стандартный поток вывода строки. Иначе логгер надо переделывать капитально и с нуля, потому что в этом виде мы не понимаем, что вы от нас хотите.
Если логгер сам генерирует строки, значит он сам и думает и автоматически реагирует на события, связанные с графом, иначе, в вашем варианте, логгер лишь пишет и не думает, что и как ему записывать.

2022-11-06 19:28 UTC, KuzmaLine commented on kuzminskiy_stafeev/main.cpp
> +}
Эта функция, по-хорошему, вообще является вспомогательной для generation_started_string и generation_finished_string

2022-11-06 19:30 UTC, Friend-LGA commented on kuzminskiy_stafeev/main.cpp
> +}
Вывод даты логирования - единственная прямая ответственность логгера, больше никакой логики в нем быть не должно.

2022-11-06 19:30 UTC, KuzmaLine commented on kuzminskiy_stafeev/main.cpp
> +}
Вы же просите мягко говоря непростую вещь для языка низкого уровня, а именно регулярное выражение, чтобы метод log делал замену какого-нибудь "<CUR_DATETIME>" на нужную дату, но это неоправданная сложность.

2022-11-06 19:33 UTC, KuzmaLine commented on kuzminskiy_stafeev/main.cpp
> +}
> 

Я ещё с 1 раза это понял, вызвать мне его из main.cpp как?
Вы предлагаете мне заниматься регулярными выражениями?
Не расскажете, как это делать на c++?

2022-11-06 19:34 UTC, KuzmaLine commented on kuzminskiy_stafeev/main.cpp
> +}
А стоп, придумал, как это сделать

2022-11-06 19:58 UTC, Friend-LGA approved these changes
Исправляйте последние замечания и можете мерджить

2022-11-06 19:58 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_logger.cpp
> +  output_fstream_ << get_current_date_time() + " " + str << std::endl;
Дата должна быть одинаковой, 2 раза её получать смысла нет. И операцию сложения 2 раза делать тоже смысла нет.

2022-11-06 19:58 UTC, Friend-LGA commented on kuzminskiy_stafeev/main.cpp
> +    std::cout << graph_json << std::endl;
Сгенерированный граф выводить больше не нужно, иначе невозможно читать вывод.

2022-11-06 20:18 UTC, merged