Realized task 5
Friend-LGA/msu_course_cpp_323_2022 pull request #87
Opened 2022-11-02 16:49 UTC by matvlaale

2022-11-02 17:08 UTC, AnnaBurikova approved these changes

2022-11-05 21:11 UTC, Friend-LGA requested changes

2022-11-05 21:11 UTC, Friend-LGA commented on matveev_burikova/graph_generator.cpp
> +  const Graph::Depth depth = params_.depth();
Аналогично

2022-11-05 21:11 UTC, Friend-LGA commented on matveev_burikova/graph_generator.cpp
> +void GraphGenerator::generate_green_edges(Graph& graph) const {
Не использует никаких дополнительных данных, кроме как переданных в функцию. Это свободная функция и её можно перенести в приватный неймспейс.

2022-11-05 21:11 UTC, Friend-LGA commented on matveev_burikova/graph_generator.cpp
> +void GraphGenerator::generate_yellow_edges(Graph& graph) const {
Аналогично

2022-11-05 21:11 UTC, Friend-LGA commented on matveev_burikova/graph_generator.cpp
> +void GraphGenerator::generate_red_edges(Graph& graph) const {
Аналогично

2022-11-05 21:11 UTC, Friend-LGA commented on matveev_burikova/graph_generator.hpp
> +  void generate_red_edges(Graph& graph) const;
Им нет необходимости быть частью интерфейса

2022-11-05 21:11 UTC, Friend-LGA commented on matveev_burikova/graph_json_printing.cpp
> +#include <fstream>
Зачем?

2022-11-05 21:11 UTC, Friend-LGA commented on matveev_burikova/graph_printing.cpp
> +}*/
???

2022-11-05 21:11 UTC, Friend-LGA commented on matveev_burikova/graph_printing.hpp
> +// void write_to_file(const std::string& content, const std::string& file_name);
???

2022-11-05 21:11 UTC, Friend-LGA commented on matveev_burikova/graph_printing.hpp
> +std::string color_to_string(Graph::Edge::Color color);
Давайте придерживаться единого интерфейса, все методы названы как `pring_something`, будет лоигчным и здесь назвать `print_edge_color`

2022-11-05 21:11 UTC, Friend-LGA commented on matveev_burikova/logger.hpp
> +  }
В `hpp` файле можно записывать только однострочные методы

2022-11-05 21:11 UTC, Friend-LGA commented on matveev_burikova/logger.hpp
> +  void log(const std::string string) const {
По значению?

2022-11-05 21:11 UTC, Friend-LGA commented on matveev_burikova/logger.cpp
> +std::string get_current_date_time() {
В приватный неймспейс

2022-11-05 21:11 UTC, Friend-LGA commented on matveev_burikova/main.cpp
> +using namespace uni_course_cpp;
Использовать `using namespace` запрещено.
Можно так:
```cpp
using Graph = uni_course_cpp::Graph;
```

2022-11-05 21:11 UTC, Friend-LGA commented on matveev_burikova/main.cpp
> +  for (int number_of_graph = 1; number_of_graph < graphs_count + 1;
Почему с 1, а не с 0, зачем усложнять?

2022-11-05 21:34 UTC, Friend-LGA reviewed
И посмотрите, у вас все файлы заканчиваются неверно

2022-11-05 21:36 UTC, Friend-LGA commented on matveev_burikova/logger.hpp
> +    std::ofstream log_file(config::kLogFilePath, std::ios_base::app);
Создавать стрим каждый раз не эффективно, сделайте эту переменную приватным членом класса

2022-11-06 11:33 UTC, matvlaale commented on matveev_burikova/graph.hpp
> +  static const Depth initial_depth;
Её не получится вынести из графа. Чтобы объявить Graph::Depth, нужно это сделать после объявления самих этих класса и типа. Но в том же классе уже в .hpp как значение глубины по умолчанию используется kInitialDepth. Так что либо kInitialDepth жалуется, что не объявлени Graph, либо Graph жалуется что не знает такой переменной

2022-11-06 12:21 UTC, AnnaBurikova approved these changes

2022-11-06 14:15 UTC, Friend-LGA commented on matveev_burikova/graph.hpp
> +  static const Depth initial_depth;
Значит перенесите её инициализацию в `cpp`, например
```cpp
// graph.cpp
namespace {
  using Vertex = uni_course_cpp::Graph::Vertex;
}
Vertex::Vertex(VertexId id) : id_(id), depth_(kInitialDepth) {}
```

2022-11-06 14:30 UTC, Friend-LGA requested changes

2022-11-06 14:30 UTC, Friend-LGA commented on matveev_burikova/config.hpp
> +#include <iostream>
Используются в этом файле?

2022-11-06 14:30 UTC, Friend-LGA commented on matveev_burikova/.gitignore
> -temp
Зачем нужен пустой файл, удалите его

2022-11-06 14:30 UTC, Friend-LGA commented on matveev_burikova/graph.hpp
> +  static constexpr Graph::Depth kInitialDepth = 1;
Написал как решить вашу проблему в прошлом комментарии, перенесите определение конструктора вершины в `cpp` файл

2022-11-06 14:30 UTC, Friend-LGA commented on matveev_burikova/graph_generator.cpp
> +void generate_grey_edges(Graph& graph, const GraphGenerator::Params params) {
1) Значения не предаются как `const`
2) Сложные данные передаются по ссылке
3) `generate_grey_edges` использует приватные данные - `params_`, будет логичным оставить эту функцию методом класса, чем добавлять лишний аргумент.

2022-11-06 14:30 UTC, Friend-LGA commented on matveev_burikova/graph_generator.hpp
> -  void generate_grey_edges(Graph& graph) const;
Эта функция скорее принадлежит классу, чем нет

2022-11-06 14:30 UTC, Friend-LGA commented on matveev_burikova/graph_generator.hpp
> +namespace {
Приватный неймспейс можно записывать только внутри `cpp` файла, в `hpp` файле он аналогичен глобальному скопу, а следовательно не имеет смысла.

Идея в том, что эти функции и константы известны только внутри `cpp` файла, потому он и "приватный неймспейс"

2022-11-06 14:30 UTC, Friend-LGA commented on matveev_burikova/logger.cpp
> +}
Зачем нужен лишний метод, тем более что вся его логика в одну троку, что вполне очевидно. Тем более что вы ещё и расширяете приватный интерфейс класса ради него (!!!). В крайнем случае можно было бы сделать эту функцию частью приватного неймспейса, но и это не требуется в данном случае

2022-11-06 14:30 UTC, Friend-LGA commented on matveev_burikova/logger.hpp
> +}  // namespace
Аналогично

2022-11-06 14:30 UTC, Friend-LGA commented on matveev_burikova/logger.hpp
> +  void log_to_file(const std::string& content) const;
Лишний интерфейс

2022-11-06 14:30 UTC, Friend-LGA commented on matveev_burikova/graph_generator.cpp
> +#include <iomanip>
Используется?

2022-11-06 14:30 UTC, Friend-LGA commented on matveev_burikova/graph.hpp
> +#include <unordered_map>
Все используются в этом файле?

2022-11-06 14:30 UTC, Friend-LGA commented on matveev_burikova/graph.cpp
> +#include "config.hpp"
Используется?

2022-11-06 14:30 UTC, Friend-LGA commented on matveev_burikova/logger.hpp
> +#include "config.hpp"
Используется?

2022-11-06 15:09 UTC, matvlaale commented on matveev_burikova/graph.hpp
> +  static constexpr Graph::Depth kInitialDepth = 1;
Не догадался, что конструктор можно вынести, хотя это очевидно; затупил. Спасибо!

2022-11-06 15:46 UTC, AnnaBurikova approved these changes

2022-11-06 18:36 UTC, Friend-LGA requested changes
Не работает
![Screenshot 2022-11-06 at 21 35 21](https://user-images.githubusercontent.com/5897136/200188816-a43c381b-d38e-4e0e-900c-8b5ac9e97e42.png)

2022-11-06 18:36 UTC, Friend-LGA commented on matveev_burikova/logger.cpp
> -#include <iostream>
1) Зачем убрали, а как же `std::cout << string_with_date_time << std::endl;`
2) `<sstream>` потеряли

2022-11-06 18:36 UTC, Friend-LGA commented on matveev_burikova/logger.hpp
> +#include <iostream>
1) Здесь он зачем
2) Не хватает `<string>`

2022-11-06 18:36 UTC, Friend-LGA commented on matveev_burikova/graph.hpp
>  #include <unordered_map>
`<vector>` потеряли

2022-11-06 18:36 UTC, Friend-LGA commented on matveev_burikova/main.cpp
>  #include <fstream>
`<string>`, `<sstream>` не хватает

2022-11-06 18:45 UTC, Friend-LGA requested changes

2022-11-06 18:45 UTC, Friend-LGA commented on matveev_burikova/graph_printing.cpp
> +  int color_distribution_counts[sizeof(Graph::Edge::Color)] = {0};
только сейчас заметил сишный массив, используйте c++ `std::array`

2022-11-06 19:22 UTC, Friend-LGA requested changes

2022-11-06 19:22 UTC, Friend-LGA commented on matveev_burikova/logger.hpp
> +  void log(const std::string& string) const;
Да, нужно ещё удалить copy и move конструкторы и операторы
```cpp
  Logger(const Logger& other) = delete;
  void operator=(const Logger& other) = delete;

  Logger(Logger&& other) = delete;
  void operator=(Logger&& other) = delete;
```

И сделать конструктор и деструктор приватными:
```cpp
 private:
  Logger();
  ~Logger() = default;
```

2022-11-06 19:22 UTC, Friend-LGA commented on matveev_burikova/logger.cpp
> +std::ofstream log_file(uni_course_cpp::config::kLogFilePath,
Глобальные переменные запрещены. Сделайте его членом класса

2022-11-06 20:10 UTC, matvlaale commented on matveev_burikova/logger.cpp
> +std::ofstream log_file(uni_course_cpp::config::kLogFilePath,
Что делать, если он выдаёт эти ошибки?
![image](https://user-images.githubusercontent.com/63255244/200192697-b975b3db-bb6f-46f1-b0e0-f18b9c19ac8a.png)

2022-11-06 20:39 UTC, AnnaBurikova approved these changes

2022-11-07 06:20 UTC, Friend-LGA requested changes

2022-11-07 06:20 UTC, Friend-LGA commented on matveev_burikova/graph_printing.cpp
> +  std::array<int, sizeof(Graph::Edge::Color)> color_distribution_counts = {0};
Не используйте sizeof от enum, он не гарантирует количество элементов

2022-11-07 06:20 UTC, Friend-LGA commented on matveev_burikova/graph_generator.cpp
> +    if (graph.depth() < current_depth + 2)
`magic number`

2022-11-07 06:20 UTC, Friend-LGA commented on matveev_burikova/logger.hpp
> +#include "config.hpp"
Зачем конфиг?

2022-11-07 06:20 UTC, Friend-LGA commented on matveev_burikova/logger.hpp
> +  std::ofstream log_file;
`naming convention`

2022-11-07 06:20 UTC, Friend-LGA commented on matveev_burikova/logger.hpp
> +  Logger(){};
Инициализируйте `log_file` один раз в конструкторе

2022-11-07 06:37 UTC, AnnaBurikova approved these changes

2022-11-07 06:42 UTC, Friend-LGA requested changes

2022-11-07 06:42 UTC, Friend-LGA commented on matveev_burikova/graph_printing.cpp
> +constexpr std::array<Graph::Edge::Color, 4> color_array = {
`naming convention`
в приватный неймспейс

2022-11-07 06:45 UTC, Friend-LGA approved these changes

2022-11-07 06:46 UTC, merged