Kucherov_sergeev/task_05
Friend-LGA/msu_course_cpp_323_2022 pull request #89
Opened 2022-11-05 15:24 UTC by BasilKucherov

2022-11-05 15:49 UTC, fedyasa approved these changes

2022-11-05 21:56 UTC, Friend-LGA requested changes

2022-11-05 21:56 UTC, Friend-LGA commented on kucherov_sergeev/graph.hpp
> +#include <vector>
Все используются в данном файле?

2022-11-05 21:56 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.hpp
> +#include "graph.hpp"
Аналогичный вопрос

2022-11-05 21:56 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.hpp
> +  void generate_red_edges(Graph& graph) const;
Свободные функции, можно упростить интерфейс и перенести их в приватный неймспейс

2022-11-05 21:56 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +namespace {
Должен быть только один приватный неймспейс

2022-11-05 21:56 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  for (Graph::Depth current_depth = 1; current_depth <= params_.depth();
1 - `magic number`, видимо это `kGraphDefaultDepth`?

2022-11-05 21:56 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  for (Graph::Depth current_depth = 2; current_depth < params_.depth();
1) 2 - `magic number`
2) Выглядит как баг. Заданная глубина и реальная глубина графа могут отличаться. На этапе генерации желтых граней нужно использовать реальную глубину, верно?

2022-11-05 21:56 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +  for (Graph::Depth current_depth = 1; current_depth < params_.depth() - 1;
1) 1 - `magic number`
2) Аналогично, нужно использовать реальную глубину

2022-11-05 21:56 UTC, Friend-LGA commented on kucherov_sergeev/graph_generator.cpp
> +    const auto& to_vertex_ids = graph.get_depth_vertex_ids(current_depth + 2);
2 - `magic number`

2022-11-05 21:56 UTC, Friend-LGA commented on kucherov_sergeev/graph_json_printing.hpp
> +std::string print_edge_color(Graph::Edge::Color color);
Распечатка цвета не относится напрямую к `json`, это общая логика, её лучше перенести просто в `namespace printing`, а не в `namespace printing::json`

2022-11-05 21:56 UTC, Friend-LGA commented on kucherov_sergeev/graph_printing.cpp
> +}  // namespace uni_course_cpp
???

2022-11-05 21:56 UTC, Friend-LGA commented on kucherov_sergeev/graph_printing.cpp
> +      "}}";
У вас есть `print_edge_color`, его и нужно использовать.
Наверное тут можно использовать цикл `for`?

2022-11-05 21:56 UTC, Friend-LGA commented on kucherov_sergeev/logger.hpp
> +  };
1) В `hpp` файле только однострочные методы
2) Конфигурация инстанса должна происходить в конструкторе, он для этого и создан

```cpp
Logger::Logger() : log_file(config::kLogFilePath) {
  if (!log_file.is_open()) {
    throw std::runtime_error("Failed to create file stream");
  }
};
```

2022-11-05 21:56 UTC, Friend-LGA commented on kucherov_sergeev/logger.hpp
> +  void log_to_file(const std::string& string);
Нам реально для этого нужно расширять интерфейс?

2022-11-05 21:56 UTC, Friend-LGA commented on kucherov_sergeev/logger.hpp
> + private:
Чтобы сделать синглтон нужно запретить создавать новые экземпляры класса, это делается так:
```cpp
 private:
  Logger();
  ~Logger() = default;
```

2022-11-05 21:56 UTC, Friend-LGA commented on kucherov_sergeev/logger.hpp
> +  std::ofstream log_file;
`naming convention`

2022-11-05 21:56 UTC, Friend-LGA commented on kucherov_sergeev/main.cpp
> +using namespace uni_course_cpp;
Использовать `using namespace` запрещено.
Можно так:
```cpp
using Graph = uni_course_cpp::Graph;
```

2022-11-06 17:26 UTC, fedyasa approved these changes

2022-11-06 19:28 UTC, Friend-LGA requested changes

2022-11-06 19:28 UTC, Friend-LGA commented on kucherov_sergeev/graph_printing.cpp
> +  std::vector<int> edges_color_distribution(sizeof(Graph::Edge::Color), 0);
Чем конвертировать одно в другое, лучше просто мап использовать
```suggestion
  std::map<Graph::Edge::Color, int> edges_color_distribution;
```

2022-11-06 19:28 UTC, Friend-LGA commented on kucherov_sergeev/graph_printing.cpp
> +std::vector<int> get_edges_color_distribution(const Graph& graph) {
Аналогично, мап

2022-11-06 19:28 UTC, Friend-LGA commented on kucherov_sergeev/graph_printing.cpp
> +  for (int color_number = 0; color_number < sizeof(Graph::Edge::Color);
1) А что если у нас было бы например так:
```cpp
enum class Color {
  Grey = 1,
  Green = 9,
  Yellow = 4,
  Red = 15,
};
```
Будет работать? Не стоит конвертировать `enum`, подумай над альтернативной логикой

2) Не думаю что `sizeof` будет всегда корректно работать с `enum`, лучше его не использовать

2022-11-06 19:28 UTC, Friend-LGA commented on kucherov_sergeev/graph_printing.cpp
> +  if (sizeof(Graph::Edge::Color) != 0) {
У нас вообще не должно быть ситуации, когда нет цветов в enum

2022-11-06 19:28 UTC, Friend-LGA commented on kucherov_sergeev/logger.hpp
>  #include "config.hpp"
Конфиг нам зачем здесь?

2022-11-06 19:28 UTC, Friend-LGA commented on kucherov_sergeev/logger.hpp
Нужно ещё удалить copy и move конструкторы и операторы
```cpp
  Logger(const Logger& other) = delete;
  void operator=(const Logger& other) = delete;

  Logger(Logger&& other) = delete;
  void operator=(Logger&& other) = delete;
```

2022-11-06 19:28 UTC, Friend-LGA commented on kucherov_sergeev/logger.hpp
> +  void operator=(Logger const&){};
1) Констуруктор и оператор копирования должны быть удалены
2) Делать это лучше в public

Выше в комментарии написал

2022-11-06 19:28 UTC, Friend-LGA commented on kucherov_sergeev/main.cpp
> +  std::string file_path =
const

2022-11-07 07:03 UTC, Friend-LGA requested changes

2022-11-07 07:03 UTC, Friend-LGA commented on kucherov_sergeev/graph_printing.cpp
> +std::vector<Graph::Depth> get_vertices_depth_distribution(const Graph& graph) {
Это не глубина, это количество

2022-11-07 07:03 UTC, Friend-LGA commented on kucherov_sergeev/logger.hpp
Ещё нужно удалить `move` конструктор и операторы

2022-11-07 07:25 UTC, Friend-LGA approved these changes

2022-11-07 07:25 UTC, Friend-LGA commented on kucherov_sergeev/graph_printing.cpp
> +constexpr Graph::Edge::Color edge_colors_list[] = {
`std::array`

2022-11-07 07:25 UTC, Friend-LGA commented on kucherov_sergeev/graph_printing.cpp
> +constexpr Graph::Edge::Color edge_colors_list[] = {
`naming convention`

2022-11-07 09:47 UTC, merged