kuzminskiy_stafeev/task_06
Friend-LGA/msu_course_cpp_323_2022 pull request #91
Opened 2022-11-06 20:27 UTC by KuzmaLine

2022-11-11 15:02 UTC, Jecteroid approved these changes

2022-11-12 14:35 UTC, Friend-LGA requested changes

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +        [&]() { generate_grey_branch(graph, graph_mutex, base_vertex_id, 2); });
1) Считается плохой практикой захватывать всё, нужно перечислять все переменные, которые нужны в лямбде
    ```suggestion
            [&graph, &graph_mutex, &base_vertex_id, this]() { generate_grey_branch(graph, graph_mutex, base_vertex_id, 2); });
    ```
    Захват `this` нужен для вызова `generate_grey_branch()`, так как это член класса, то под капотом он вызывается так: `this->generate_grey_branch()`, поэтому нам и нужно захватить `this`
2) 2 - `magic number`

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  std::vector<Graph::VertexId> base_vertex_id = {0};
Если это `base_vertex_id` то тип должен быть `VertexId`, а у вас вектор. Назовите правильно

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +        std::lock_guard<std::mutex> guard(jobs_mutex);
`const`

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +bool has_job(std::mutex& jobs_mutex,
`jobs_mutex` не используется

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +JobCallBack get_job(std::mutex& jobs_mutex, std::list<JobCallBack>& jobs) {
Аналогично

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  auto threads = std::vector<std::thread>();
Так как мы знаем размерность вектора, то нужно либо использовать `std::array`, либо зарезервировать место
```cpp
threads.reserve(threads_count);
```

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +    threads.emplace_back(std::thread(worker));
`emplace_back` итак вызывает конструктор, а у вас получается что вызывается конструктор перемещения, в этом нет нужды. Просто `worker` передайте

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  } else if (cur_depth == 2) {
`magic number`

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  std::lock_guard<std::mutex> guard(graph_mutex);
Изменяется?

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  auto vertex_id = graph.add_vertex();
Изменяется?

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  std::vector<Graph::VertexId> cur_vertex_ids;
Что это знает, "текущие id вершин"?

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +    std::vector<Graph::VertexId> previous_vertex_ids,
Одной предыдущей вершины не достаточно? Зачем целый вектор?

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  }
Эта логика должна выполнять рекурсивно каждый раз? Выглядит как внешняя логика, которая должна выполниться только 1 раз и не имеет прямого отношения к данному методу

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  float prob = (float)(1 - step * (cur_depth - 2));
Изменяются?

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  for (const auto from_vertex_id : previous_vertex_ids) {
Вектор тут не нужен, можно упростить рекурсивную логику и передавать только одну вершину. Для создания ветви одной вершины более чем достаточно

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +        add_grey_edge(graph, from_vertex_id, graph_mutex, cur_vertex_ids);
По логике рекурсии тут должен быть вызов самого метода.
```cpp
if (check_probability(prob)) {
  generate_grey_branch(...);
}
```
Если успешно -> сгенерировать новую ветвь от текущей вершины.
А вы что-то усложнили

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  generate_grey_branch(graph, graph_mutex, cur_vertex_ids, cur_depth + 1);
Это лишнее

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +         cur_vertex_count < new_vertices_count; cur_vertex_count++) {
Можно обойтись без лишней переменной и напрямую использовать здесь `params_.new_vertices_count()`

2022-11-12 14:35 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +                           graph.get_graph_depth());
А эти методы граф не изменяют? Может им тоже нужен `graph_mutex`?

2022-11-12 15:08 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph_generator.cpp
> +        std::lock_guard<std::mutex> guard(jobs_mutex);
Что const?

2022-11-12 15:09 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph_generator.cpp
> +  auto threads = std::vector<std::thread>();
Я пытался так сделать, но тогда по неизвестным для меня причинам происходит segfault

2022-11-12 15:12 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph_generator.cpp
> +    std::vector<Graph::VertexId> previous_vertex_ids,
Потому что это вершины на предущей глубине. Вы предлагаете вызывать функцию рекурсивно для КАЖДОЙ вершины??

2022-11-12 15:12 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph_generator.cpp
> +  }
В задаче написано "использовать рекурсию"

2022-11-12 15:14 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph_generator.cpp
> +  for (const auto from_vertex_id : previous_vertex_ids) {
Логику вы то упростите, но вот производительности желаю удачи, ибо команда call в оперативной памяти крайне время затратна, по сравнению с обращением в массиве по индексу

2022-11-12 15:15 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph_generator.cpp
> +        add_grey_edge(graph, from_vertex_id, graph_mutex, cur_vertex_ids);
Не понял, а к чему мне присоединять вершины, которые ещё не созданы?

2022-11-12 15:15 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph_generator.cpp
> +  generate_grey_branch(graph, graph_mutex, cur_vertex_ids, cur_depth + 1);
И как мне переходить на следующую глубину?

2022-11-12 15:17 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph_generator.cpp
> +                           graph.get_graph_depth());
1 - Нет, этим генераторам мьютекс не нужен, т.к. они не залезают в логику дргу друга и не зависят друг от друга, это можно увидеть в функции define_color

2022-11-12 15:18 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph_generator.cpp
> +    should_terminate = true;
Вы предлагаете использовать сигналы?
Или как я должен дожидаться того, что нити завершат свою работу?

2022-11-13 14:27 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph_generator.cpp
> +    std::vector<Graph::VertexId> previous_vertex_ids,
Я даже провёл эксперимент. 
Вот результат моей программы для параметров 7 8 3
![image](https://user-images.githubusercontent.com/109547354/201526915-2019fc93-adab-4b7d-97c8-d53e36104f98.png)

А вот моей
![image](https://user-images.githubusercontent.com/109547354/201526925-251c7a9b-15a1-413d-930f-3836cdf2d08f.png)

2022-11-13 15:31 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +        std::lock_guard<std::mutex> guard(jobs_mutex);
Переменная `guard` изменяется?

2022-11-13 15:41 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +    std::vector<Graph::VertexId> previous_vertex_ids,
Насколько я слышал, в современных версиях плюсов есть специальные оптимизации для рекурсивных функций. Было бы интересно посмотреть на реальную ситуацию со `stack overflow`, которую ты описываешь. В целом валидная точка зрения, можете оставить так.

2022-11-13 15:42 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  }
> у меня как раз происходит деление на потоки
вот и раздели на 2 куска логики, одна подготовительная - вторая рекурсивная.

2022-11-13 15:45 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  for (const auto from_vertex_id : previous_vertex_ids) {
По дизайну, всегда лучше начинать писать код с более простой логики, и если при выполнении реальной задачи действительно утыкаешься в ограничение, тогда уже оптимизируешь.

В прошлом комменте обсудили, можете оставить как сделали.

2022-11-13 15:46 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +        add_grey_edge(graph, from_vertex_id, graph_mutex, cur_vertex_ids);
Этот комментарий тоже был к той же логике, что уже обсудили, можете оставить как сделали.

2022-11-13 15:46 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  generate_grey_branch(graph, graph_mutex, cur_vertex_ids, cur_depth + 1);
Этот комментарий тоже был к той же логике, что уже обсудили, можете оставить как сделали.

2022-11-13 15:50 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +    should_terminate = true;
> Вы предлагаете использовать сигналы? (Крайне плохая идея)

Нет, я предлагаю вам придумать другую логику, так чтобы `should_terminate = true` задавался снаружи воркера. Попробуйте, даже, если на ваш взгляд это будет не оптимально.

2022-11-13 16:02 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +    graph_mutex.lock();
Нужно всегда использовать `lock_guard`, если не придумали как обернуть только часть логики в него, то это можно сделать так:
```cpp
...
{
  const std::lock_guard lock(graph_mutex);
  ...
  ...
}
...
```

2022-11-13 16:03 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  }
Уже обсуждали, выглядит как внешний кусок логики, не относящийся напрямую к рекурсии, вынесите

2022-11-13 16:04 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +      graph_mutex.lock();
`lock_guard`

2022-11-13 16:06 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  Graph::VertexId root_id = 0;
Это почему вы придумали, что `root_id` это `0`?
Нужно реальные данные использовать, а не выдумывать их
```cpp
// graph.hpp
VertexId add_vertex();

// here
const auto root_id = graph.add_vertex();
```

Теперь вам должно быть очевидно, что тот кусок логики лишний для вашей рекурсии, раз вам результат работы той логики нужен здесь.

2022-11-13 16:08 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
>    }
В бесконечном цикле вызывать блокировку очень не эффективно.
Попробуйте использовать, например `atomic`
К примеру, как-то так:
```cpp
while (some_condition) {
  // waiting for all jobs to be done
}
should_terminate = true;
```

2022-11-13 16:15 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +const int kStartDepth = 2;
1) `constexpr vs const`
2) не `int` а `Depth`
3) Какая-то надуманная константа. 
По-хорошему, к этому моменту у вас уже должна быть константа типа
```cpp
kGraphBaseDepth = 1;
```
Выглядит что тут тоже должна использоваться именно она.

И она так-же должна использоваться в методах, где у вас есть `magic number` `1` как базовая глубина.
Скорее всего это следующие методы:
```cpp
calculate_edge_color
generate_green_edges
generate_yellow_edges
generate_red_edges
```

Возможно ещё где-то, проверьте

2022-11-13 16:20 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph_generator.cpp
>    auto job = jobs.front();
Значит has_job вернёт false

2022-11-13 17:07 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
>    auto job = jobs.front();
Метод `get_job` не знает о существовании `has_job`, поэтому в нем либо такая ситуация должна оборабатываться очевидным образом, либо должен быть добавлен `assert`

2022-11-13 17:23 UTC, Friend-LGA requested changes

2022-11-13 17:23 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +      Graph::VertexId child_id;
Всегда нежелательно оставлять неинициализированную переменную и тем более не `const`
В такой ситуации можно использовать лямбду
```cpp
const auto child_id = [...](...) {
  lock_guard;
  return value;
}();
```

2022-11-13 17:23 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  for (Graph::Depth cur_depth = kGraphBaseDepth + 1; cur_depth <= depth - 1;
Ненужная на данном этапе оптимизация (это я про `+ 1`) Вы это делаете, опираясь на тот факт, что вероятность желтых граней на 1ой глубине будет 0. Но тем самым вы добавляете в программу неожиданное поведение, если кто-то изменит логику рассчета вероятностии желтых граней, ваша логика сломается. Поэтому лучше было бы начать как и везде просто с `kGraphBaseDepth` и просто на этой глубине вероятность будет 0 и ничего не создастся. Это ок. Зато логика будет более надежной.

`depth - 1` - это тоже `magic number`, видимо что-то типа `kYellowEdgeDepth = 1`

2022-11-13 17:23 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +  for (Graph::Depth cur_depth = kGraphBaseDepth; cur_depth <= depth - 2;
2 - `magic number`, например `kRedEdgeDepth = 2`

2022-11-13 17:23 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
>      const auto& deeper_vertices = graph.vertices_of_depth(cur_depth + 2);
аналогично

2022-11-13 17:23 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
>    if (depth == 1) {
`magic number`

2022-11-13 17:23 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +        Graph::VertexId child_id;
Аналогично

2022-11-13 17:23 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +        generate_grey_branch(graph, graph_mutex, child_id, kGraphBaseDepth + 2);
Почему `kGraphBaseDepth + 2`? Можно обойтись без двойки? В крайнем случае можно вынести `magic number`, но оно выглядит подозрительно

2022-11-13 17:23 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
>    const float prob = (float)(1 - step * (cur_depth - 2));
Там вы прибавляете 2, тут вы отнимаете 2, в этом точно есть смысл?

2022-11-13 17:23 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
>      if (jobs.empty()) {
Я не сказал убрать синхронизацию, я сказал подумать об альтернативной безопасной логике, например с использованием `atomic`

2022-11-13 17:34 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph_generator.cpp
>    const float prob = (float)(1 - step * (cur_depth - 2));
Use list A4 with pen and try some mathematics

2022-11-13 18:22 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
>    const float prob = (float)(1 - step * (cur_depth - 2));
Эмпирически мне не интересно, я вам верю, тут просто алгоритм. Меня интересует то, чтобы ваш код нормально читался, а тут получается что что вы извне вызываете `kGraphBaseDepth + 2`, а тут вы делаете `cur_depth - 2`. Соотвественно, если передать `kGraphBaseDepth`, то и здесь будет просто `cur_depth`.
Так понятно?

2022-11-13 18:28 UTC, KuzmaLine commented on kuzminskiy_stafeev/graph_generator.cpp
>    const float prob = (float)(1 - step * (cur_depth - 2));
Моя функция генерации ветвей следит за тем, вершины для какой глубины она сейчас генерит, поэтому нет, такое решение непрактично, ибо эта двойка тогда просто переедет в условие конца генерации ветвей.

2022-11-14 07:19 UTC, Friend-LGA requested changes

2022-11-14 07:19 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +constexpr Graph::Depth kStartThreads = 3;
-

2022-11-14 07:19 UTC, Friend-LGA commented on kuzminskiy_stafeev/graph_generator.cpp
> +      }();
Убери дублирование кода

2022-11-14 14:44 UTC, Friend-LGA approved these changes
Ну вот, смотрите какая красота, все лишние непонятные переменные и действия ушли.
🎉 🎉 🎉

2022-11-14 14:47 UTC, merged