antyukhov_mamedov/task 04
Friend-LGA/msu_course_cpp_323_2022 pull request #93
Opened 2022-11-07 10:18 UTC by chereshnya123

2022-11-07 10:53 UTC, sm0kebamb0o approved these changes

2022-11-07 16:03 UTC, sm0kebamb0o approved these changes

2022-11-13 17:47 UTC, Friend-LGA requested changes

2022-11-13 17:47 UTC, Friend-LGA commented on mamedov_antyukhov/Logger.cpp
> +#include "Logger.hpp"
Воу, оно как, совсем не заметно что у нас нет ни одного файла с таким форматом названия? `naming convention`

2022-11-13 17:47 UTC, Friend-LGA commented on mamedov_antyukhov/Logger.cpp
> +}  // namespace uni_course_cpp
Ну сколько можно. Каждый файл должен завершаться на символ новой строки. Неужели яркий красный знак "ошибка" не бросается вам в глаза?

2022-11-13 17:47 UTC, Friend-LGA commented on mamedov_antyukhov/Logger.cpp
> +std::string get_current_date_time() {
Этот метод должен быть в приватном неймспейсе
```cpp
namespace {
  // здесь приватный
}
namespace uni_course_cpp {
  // здесь все остальное
}
```

2022-11-13 17:47 UTC, Friend-LGA commented on mamedov_antyukhov/Logger.hpp
> +  Logger(){};
Для синглтона должно быть сделано следующее:
1) Конструктор и деструктор объявлены приватными.
2) Конструктор и оператор копирования удалены
3) Конструктор и оператор перемещения удалены

Стандартный конструктор записывается через `= default` а не пустые скобочки `{}`

```cpp
 public:
  Logger(const Logger& other) = delete;
  void operator=(const Logger& other) = delete;

  Logger(Logger&& other) = delete;
  void operator=(Logger&& other) = delete;

 private:
  Logger() = default;
  ~Logger() = default;
```

2022-11-13 17:47 UTC, Friend-LGA commented on mamedov_antyukhov/Logger.cpp
> +  log_file.close();
Что за прикол?
1) У вас есть аналогичный член класса, который не используется
2) Вы тут просто создаете файл и закрываете
3) В методе `log` вы ещё раз создаете файл.

Логика такая:
При создании логгера должен создаваться файл и он остается открытым все время работы программы, так как логгер постоянно пишет информацию в этот файл. Создавать его нужно не здесь, а в конструкторе логгера.

2022-11-13 17:47 UTC, Friend-LGA commented on mamedov_antyukhov/config.hpp
> +namespace config {
Весь код должен быть обернут в `namespace uni_course_cpp`

2022-11-13 17:47 UTC, Friend-LGA commented on mamedov_antyukhov/graph.cpp
> +}
1) Этот метод выглядит просто ужасно. Нужно на уровне интуиции понимать, что тут какая-то лажа
2) Добавлять в интерфейс Графа подобный метод - это не очень эффективно. Интерфейс графа должен быть универсальным и полезным, а данный метод, по факту, нужен только в одном методже при распечатке. Намного более полезно будет добавить метод, который позвращает все `id` граней по цветам

```cpp
std::unordered_map<Edge::Color, std::vector<EdgeId>> colored_edge_ids_;

const std::vector<EdgeId>& get_colored_edge_ids(Edge::Color color) const;
```

2022-11-13 17:47 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator.hpp
>  static double red_edges_probability = 0.33;
1) `naming convention` как записываются глобальные константы?
2) Если это константы, то почему они записаны как перменные?
3) Они используются только внутри `cpp` файла, вот и место им там, где они используются. В приватный неймспейс.

2022-11-13 17:47 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator.cpp
> +namespace uni_course_cpp {
Все свободные функции (которые используют только переданные в них аргументы) должны быть в приватном неймспейсе. А вы их не вынесли.

Тут в файле используются `1 и 2` как `magic number`, их тоже нужно вынести в глобальные константы в приватный неймспейс и использовать в коде
```cpp
kGraphBaseDepth = 1;
kYellowEdgeDepth = 1;
kRedEdgeDepth = 2;
```

2022-11-13 17:47 UTC, Friend-LGA commented on mamedov_antyukhov/graph_printing.cpp
> +             << "}}\n}";
Видно же что код весь дублируется, так писать нельзя. Используйте цикл для обхода цветов.

2022-11-13 17:47 UTC, Friend-LGA commented on mamedov_antyukhov/main.cpp
> +    std::runtime_error("Can not create temp directory");
`throw` забыли

2022-11-14 07:28 UTC, sm0kebamb0o approved these changes

2022-11-14 15:06 UTC, Friend-LGA requested changes

2022-11-14 15:06 UTC, Friend-LGA commented on mamedov_antyukhov/graph_printing.cpp
> +  for (const auto& p : colors) {
1) Договаривались без ненужных сокращений, это что у нас, `color`, вот и пишите `color`
2) `enum class` это примитивный тип, они передаются по значению

2022-11-16 21:09 UTC, chereshnya123 commented on mamedov_antyukhov/graph_printing.cpp
> +    if (p.first == Graph::Edge::Color::Red)
Немного не понял. Я это знаю потому, что заранее завел такой вектор, где последняя пара состоит из Graph::Edge::Color::Red и строки. По этому вектору я и итерируюсь.

2022-11-17 15:24 UTC, sm0kebamb0o approved these changes

2022-11-18 18:54 UTC, sm0kebamb0o approved these changes

2022-11-19 10:40 UTC, Friend-LGA commented on mamedov_antyukhov/graph_printing.cpp
> +    if (p.first == Graph::Edge::Color::Red)
Вот именно, ты сам это придумал и так сделал. Сегодня ты сделал так, а завтра по-другому. Ты же не в камне код вытесываешь. А следовательно эта логика ненадежная, на неё нельзя опираться. Кроме того, это внешние знания тебя, как человека пишущего программу, а программа об этом не знает. Всегда должен быть интерфейс, гарантирующий конкретность тех или иных данных, а не какая-то магия.

2022-11-19 10:51 UTC, Friend-LGA requested changes
Бинарников в ПР быть не должно

2022-11-19 10:51 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator.cpp
>  bool check_probability(const double probability) {
аргументы по значению не указываются ка конст

2022-11-19 10:51 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator.cpp
> +};  // namespace
Не исправили

2022-11-19 10:51 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator.hpp
> +};  // namespace uni_course_cpp
Не исправили

2022-11-19 10:51 UTC, Friend-LGA commented on mamedov_antyukhov/logger.hpp
> +  Logger();
Идея переноса реализации конструктора была в том, чтобы избавиться в интерфейсе от лишней зависимости, а она у вас осталась.

2022-11-19 10:51 UTC, Friend-LGA commented on mamedov_antyukhov/graph_generator.hpp
>  std::vector<Graph::VertexId> get_unconnected_vertex_ids(
Не исправили

2022-11-19 15:02 UTC, sm0kebamb0o approved these changes

2022-11-20 12:34 UTC, Friend-LGA requested changes
Я бы зааппрувил, если бы вы не 3 раза подряд пропускали исправление.
Нет вам доверия, поэтому исправляйте последнюю ошибку.

2022-11-20 12:34 UTC, Friend-LGA commented on mamedov_antyukhov/logger.hpp
>  #include "config.hpp"
3ий раз повторяю... Вы конструктор перенесли в `cpp` чтобы в интерфейсе не было зависимости от конфига. Так почему он все ещё здесь?..

2022-11-20 12:34 UTC, Friend-LGA commented on mamedov_antyukhov/logger.hpp
> +  Logger();
Не исправили

2022-11-20 13:38 UTC, Friend-LGA approved these changes
Эврика!!! 🎉 🥳 🎈 
![](https://media.giphy.com/media/3ohhweiVB36rAlqVCE/giphy.gif)

2022-11-20 13:39 UTC, merged