kuznetsov_alexey/task 02
Friend-LGA/msu_course_cpp_323_2022 pull request #94
Opened 2022-11-07 13:33 UTC by KuzAlexey

2022-11-07 15:04 UTC, KuzAlexey commented
Не понимаю почему не линкуется.
Локально запускал clang-format.
И вроде мастер обновлен.

2022-11-12 15:13 UTC, Friend-LGA commented
После того как обновился на свежий мастер, ты его замерджил в свою ветку?
```
git switch your_branch_name
git merge master
```

2022-11-13 14:47 UTC, KuzAlexey commented
Сделал так, но не помогло.

2022-11-14 07:33 UTC, Friend-LGA requested changes

2022-11-14 07:33 UTC, Friend-LGA commented on kuznetsov_alexey/graph.cpp
> +  std::vector<Edge> edges;
`naming convention`

2022-11-14 07:33 UTC, Friend-LGA commented on kuznetsov_alexey/graph.cpp
> +  void add_vertex() { vertices.push_back(Vertex(vertices.size())); }
```cpp
vertices.emplace_back(get_new_vertex_id());
```
```cpp
VertexId get_new_vertex_id() {
  return vertex_id_counter_++;
}
```

2022-11-14 07:33 UTC, Friend-LGA commented on kuznetsov_alexey/graph.cpp
> +    edges.push_back(Edge(vertices.size(), from_vertex_id, to_vertex_id));
Аналогично

2022-11-14 07:33 UTC, Friend-LGA commented on kuznetsov_alexey/graph.cpp
> +  int count_vertices_ids_in_graph(const std::vector<VertexId>& v_ids) {
Убери эту функцию

2022-11-14 07:33 UTC, Friend-LGA commented on kuznetsov_alexey/graph.cpp
> +    assert(count_vertices_ids_in_graph({from_vertex_id, to_vertex_id}) >= 2);
```cpp
assert(has_vertex(from_vertex_id));
assert(has_vertex(to_vertex_id));
```
```cpp
std::unordered_map<VertexId, Vertex> vertices_;
```

2022-11-19 10:01 UTC, Friend-LGA approved these changes

2022-11-20 20:00 UTC, merged