fedotov_chuvashov/task_06
Friend-LGA/msu_course_cpp_323_2022 pull request #98
Opened 2022-11-12 13:04 UTC by Huszar0

2022-11-12 15:12 UTC, Friend-LGA requested changes

2022-11-12 15:12 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
>    }
К слову, проверка на `depth == 0` ожидаемая, а вот
`depth < 0` - это не ожидаемое поведение, а следовательно `assert`

2022-11-12 15:12 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +                                     std::mutex& mutex) const {
Что за мьютекс, в угадайку поиграть. Везде нужно называть их очевидно и выразительно.

2022-11-12 15:12 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +  mutex.unlock();
Может лучше рассчитывать вероятность прямо внутри цикла `for`, скорее всего это будет менее затратно чем лишняя блокировка.

2022-11-12 15:12 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +void generate_green_edges(Graph& graph, std::mutex& mutex) {
Аналогично

2022-11-12 15:12 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +                [&](const std::pair<Graph::VertexId, Graph::Vertex>& element) {
Захват

2022-11-12 15:12 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +  auto vertices = graph.vertices();
1) Почему копия?
2) Изменяется?

2022-11-12 15:12 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +    auto vertices = graph.vertices_at_depth(current_depth);
Аналогичные вопросы

2022-11-12 15:12 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +        vertices.begin(), vertices.end(), [&](const Graph::VertexId vertex_id) {
Аналогично

2022-11-12 15:12 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +    auto vertices = graph.vertices_at_depth(current_depth);
Аналогично

2022-11-12 15:12 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +  for (Graph::Depth current_depth = 1;
1 -`magic number`

2022-11-12 15:12 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
>    for (Graph::Depth current_depth = 1;
`magic number`

2022-11-12 20:13 UTC, Huszar0 commented on fedotov_chuvashov/graph_generator.cpp
> +  std::deque<JobCallback> task_queue;
Вставка и удаление крайних элементов у `deque` быстрее, чем у `list`

2022-11-13 15:29 UTC, Friend-LGA requested changes

2022-11-13 15:29 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +  }
Эта логика должна выполняться рекурсивно каждый раз? Выглядит как внешняя логика, которая должна выполниться только 1 раз и не имеет прямого отношения к данному методу

2022-11-13 15:29 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
>                  (graph.get_vertex_depth(root_id) - kGreyDepthDifference)) /
Использовать блокировку довольно дорого, с точки зрения эффективности, и всегда нужно думать, каким образом её можно избежать.
Вы используете `lock` из-за `graph.get_vertex_depth(root_id)`, вместо этого можно было бы передавать глубину вершины в метод, вместо той глубины, что вы сейчас передаете. Так вы уже знали бы глубину вершины и нет нужды обращаться к графу лишний раз.
Типа такого:
```cpp
const auto root_id = graph.add_vertex();
graph.add_edge(root_id, branch_root_id);
generate_branch(graph, root_id, kGraphBaseDepth, graph_mutex)
...
...
...
generate_branch(Graph& graph,
                Graph::VertexId root_id,
                Graph::Depth root_depth,
                std::mutex& graph_mutex) {
  if (root_depth == params.depth()) return;
  ...
  ...
  ...
  if (check_probabilty(probabilty_of_grey_edge)) {
    const auto child_id = graph.add_vertex();
    graph.add_edge(branch_root_id, child_id);
    generate_branch(graph, child_id, depth + 1, graph_mutex);
  }
}
```
Это очень приблизительный код. Сами подумайте и доведите до ума.

2022-11-13 18:19 UTC, Friend-LGA requested changes

2022-11-13 18:19 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +                    std::lock_guard graph_guard(graph_mutex);
Переменная изменяется? `const`

2022-11-13 18:19 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +              std::lock_guard graph_guard(graph_mutex);
Аналогично

2022-11-13 18:19 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +            std::lock_guard graph_guard(graph_mutex);
Аналогично

2022-11-13 18:19 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +              std::lock_guard graph_guard(tasks_mutex);
Аналогично

2022-11-13 18:19 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +  }
1) Нельзя оставлять неинициализированные переменные, тем более не конст
Для этого можно использовать лямбду, в `common mistakes`, кажется, это было описано
```cpp
const auto some_var = []() {
  some_logic;
  return value;
}();
```
2) Чем высчитывать глубину `child_depth = graph.get_vertex_depth(child_id);`
можно передать глубину `root_depth`, тогда новая глубина будет просто `root_depth + 1`

`root_depth` у вас должна быть известна.

2022-11-13 18:19 UTC, Friend-LGA commented on fedotov_chuvashov/graph_generator.cpp
> +  generate_children(graph, child_id, child_depth, graph_mutex);
Почему у вас логика разбита на 2 функции? Ну то есть, разбивать логику на функции - это хорошо, когда можно разделить логику. Но у вас выглядит, что выполняется практически одно и тоже в обоих методах 
```cpp
generate_branch
generate_children
```
По факту должно быть просто `generate_branch` вызывает `generate_branch` без лишних этапов.

Единственное, вы должны создать корневую вершину вне рекурсивной функции, остальная логика работает просто рекурсивно
`new_vertices_number` вызываем `generate`
он внутри добавляет одну вершину и вызывает `new_vertices_number` функций `generate` и так рекурсивно, пока они не будут сгенерированы все.

2022-11-14 06:47 UTC, Friend-LGA approved these changes

2022-11-14 06:47 UTC, merged