matveev_burikova/task_06
Friend-LGA/msu_course_cpp_323_2022 pull request #99
Opened 2022-11-13 08:59 UTC by matvlaale

2022-11-13 09:12 UTC, AnnaBurikova approved these changes

2022-11-13 16:05 UTC, AnnaBurikova approved these changes

2022-11-13 16:10 UTC, AnnaBurikova approved these changes

2022-11-13 17:05 UTC, Friend-LGA requested changes

2022-11-13 17:05 UTC, Friend-LGA commented on matveev_burikova/graph_generator.cpp
> +        std::lock_guard<std::mutex> guard(jobs_mutex);
Переменная изменяется? `const`

2022-11-13 17:05 UTC, Friend-LGA commented on matveev_burikova/graph_generator.cpp
> +    threads.emplace_back(std::thread(worker));
`emplace_back` принимает аргументы конструктора, а вы тут используете конструктор перемещения, в этом нет необходимости, просто передайте `worker` и все

2022-11-13 17:05 UTC, Friend-LGA commented on matveev_burikova/graph_generator.cpp
> +  while (has_job(jobs)) {
`jobs` у нас разделяемый ресурс, раз так было бы неплохо добавить блокировку. Но это очень не эффективно в бесконечном цикле, поэтому лучше подумать об альтернативной логике, например использовать `atomic`

2022-11-13 17:05 UTC, Friend-LGA commented on matveev_burikova/graph_generator.cpp
> +  }
Эта логика должна выполнять рекурсивно каждый раз? Выглядит как внешняя логика, которая должна выполниться только 1 раз и не имеет прямого отношения к данному методу

2022-11-13 17:05 UTC, Friend-LGA commented on matveev_burikova/graph_generator.cpp
> +  std::thread red_thread(&generate_red_edges, std::ref(graph));
А внутри этих функций не используются разделяемые ресурсы, которые требуют синхронизации? Например `add_edge`?

2022-11-13 18:53 UTC, AnnaBurikova approved these changes

2022-11-14 06:11 UTC, Friend-LGA requested changes

2022-11-14 14:38 UTC, Friend-LGA approved these changes
Исправьте и можете мерджить

2022-11-14 14:38 UTC, Friend-LGA commented on matveev_burikova/graph_generator.cpp
> +                           kInitialDepth + 1);
Почему здесь `+ 1`? Откуда это взялось? Лучше передать просто `kInitialDepth`

2022-11-14 14:38 UTC, Friend-LGA commented on matveev_burikova/graph_generator.cpp
> +    if (check_probability(1 - (current_depth - 1) * step)) {
Здесь, соответственно, видимо `- 1` не нужно, если вы извне не будете передавать `+ 1`

2022-11-14 14:38 UTC, Friend-LGA commented on matveev_burikova/graph_generator.cpp
>    std::atomic<int> jobs_atomic = new_vertices_count;
Плохое название. Переменные должны называться не технически, а логически. Например что-нибудь в духе
```cpp
jobs_count
number_of_jobs
waiting_jobs_count
```

2022-11-14 14:38 UTC, Friend-LGA commented on matveev_burikova/graph_generator.cpp
>    if (current_depth > params_.depth())
И здесь, подумайте, ваши `+ 1`, `- 1` как-то влияли на проверку? Может стоит сюда сдвиг добавить

2022-11-18 10:57 UTC, merged